var DP300_DATA = {
  "title": "Designing and Implementing Azure Database Solutions",
  "modules": {
    "Module 1": {
      "topics": {
        "Azure SQL Platform Options": {
          "What It Is": "Microsoft offers three primary SQL Server-based options in Azure: **SQL Server on Azure VM** (IaaS), **Azure SQL Database** (PaaS), and **Azure SQL Managed Instance** (PaaS). The choice depends on control vs. management overhead needed, and what compatibility your existing applications require.",

          "IaaS vs PaaS Decision": "### SQL Server on Azure VM (IaaS)\nFull control over OS and SQL Server — you manage patching, configuration, and backups. Best for:\n- Legacy applications requiring older SQL Server versions for vendor support\n- Applications needing SSIS/SSRS/SSAS on the same machine\n- Apps requiring CLR, cross-database queries, or OS-level access\n- The **SQL Server IaaS Agent Extension** provides automated backup, patching, Key Vault integration, Defender for Cloud, and disk utilization views\n\n### Azure SQL Database (PaaS)\nFully managed — no OS/SQL patching, automated backups, built-in HA. Best for:\n- New cloud-native apps and intermittent/unpredictable usage (serverless tier)\n- Simplified deployment and scaling up to 100 TB (Hyperscale)\n- Supports **DTU** (bundled) and **vCore** (decoupled) purchasing models; single database or elastic pool\n\n### Azure SQL Managed Instance (PaaS)\nNear 100% on-premises SQL Server compatibility in a fully managed instance. Best for:\n- Lift-and-shift migrations without application changes\n- Apps needing instance-scoped features: SQL Agent, CLR, cross-DB queries, Service Broker\n- Supports up to 100 databases per instance; deployed in a dedicated VNet",

          "Licensing": "| Option | Details |\n|---|---|\n| **PAYG** | Pay per minute for SQL Server license + VM cost via Marketplace images |\n| **BYOL** | Use an existing Software Assurance license on a blank VM |\n| **Azure Hybrid Benefit (AHB)** | 1 Enterprise core = 1 vCore Business Critical **or 4 vCores General Purpose**; 1 Standard core = 1 vCore General Purpose; up to 40% savings |\n| **Reserved Instances** | 1–3 year commitment, monthly billing, no upfront required |\n| **Flexible Licensing** | Toggle between PAYG and BYOL/AHB without redeployment via the IaaS Agent Extension |",

          "HA and DR Options": "### High Availability (Within a Region)\n\n| Option | SLA | Unit of Failover |\n|---|---|---|\n| Availability Zones | 99.99% | VM (3 separate datacenters) |\n| Availability Sets | 99.95% | VM (different racks, same DC) |\n| Always On AG | — | Database group |\n| FCI | — | Entire instance (requires shared storage) |\n\n### Disaster Recovery (Cross-Region)\n- Native backups to URL (Blob Storage, GRS/RA-GRS)\n- Azure Backup\n- Azure Site Recovery (VM-level — **not SQL-aware**, higher RPO)\n- Always On AG async replicas across regions\n- Auto-failover groups (SQL DB and MI)\n\n### Managed Instance Link\nDAG-based replication between on-premises SQL Server and Azure SQL MI. One-way (SQL 2016/2019) or two-way (SQL 2022). Cutover in seconds. Use cases: DR failover, read-scale offload, automated cloud backups.",

          "Exam Gotchas": "- SQL Agent, CLR, cross-DB queries, and Service Broker are **MI-only** in PaaS\n- SQL Database does **not** support: SQL Agent (use Elastic Jobs), T-SQL RESTORE, COPY_ONLY backups, or cross-DB queries natively\n- Managed Instance does **not** support: DTU model, elastic pools, Elastic Jobs, or Hyperscale\n- Always On AG unit of failover = **database group**; FCI unit = **entire instance**\n- **Hyperscale cannot be reverted** to General Purpose or Business Critical\n- Serverless autopause is **General Purpose only** (min 60 min, max 7 days)\n- AHB: 1 Enterprise core = **4 General Purpose vCores** (not 8)"
        },

        "IaaS Deployment (SQL Server on Azure VM)": {
          "What It Is": "SQL Server on Azure Virtual Machines provides the most control and highest on-premises compatibility. The Azure platform manages the hypervisor and hardware; you manage the VM, OS, SQL Server, and all configuration. The **SQL Server IaaS Agent Extension** (installed automatically from the Marketplace) provides automated backup, patching, Key Vault integration, Defender for Cloud, disk utilization views, flexible licensing, and version/edition changes.",

          "VM Families and Storage": "### VM Families\n\n| Family | Best For |\n|---|---|\n| General Purpose | Balanced CPU/memory |\n| Compute Optimized | High CPU workloads |\n| Memory Optimized | Database workloads (up to 4 TB RAM) |\n| Storage Optimized | NVMe, ephemeral storage |\n| HPC / GPU / FPGA | Specialized compute |\n\n### Storage Best Practices\n- **Data files**: Premium SSD or Ultra Disk, separate pool, **read-caching enabled**\n- **Log files**: Separate pool, **NO read-caching**\n- **TempDB**: Temporary disk (D:) for low latency, or own pool\n- **Backups**: Standard storage is sufficient\n- **OS disk**: Minimum size — no database files\n- Use **Storage Spaces** to pool disks for increased IOPS\n\n### Data Compression\n- **Page compression** (superset of row compression, ~72% fewer reads)\n- **Row compression** (basic)\n- **Columnstore archival XPRESS** (cold data)\n- Use `sp_estimate_data_compression_savings` to estimate before applying",

          "HA and DR for IaaS": "| Feature | SLA | Notes |\n|---|---|---|\n| Availability Set | 99.95% | Spread across fault/update domains, same datacenter |\n| Availability Zone | 99.99% | 3 zones per region, separate datacenters |\n| Always On AG | — | Up to 9 replicas, sync (same region) or async (cross-region) |\n| FCI | — | Entire instance fails over; requires shared storage; HA only — **not DR** |\n| Azure Site Recovery | — | VM-level block replication; higher RPO for SQL Server |\n| Native Backups to URL | — | BACKUP TO URL (Azure Blob), GRS/RA-GRS for geo-redundancy |",

          "Licensing Options for IaaS": "- **PAYG**: Marketplace image, pay per minute\n- **BYOL**: Blank VM + manual SQL install, or Azure Hybrid Benefit option\n- **Azure Hybrid Benefit**: Apply existing Windows Server + SQL Server SA licenses\n- **Reserved Instances**: 1–3 year commitment for compute savings\n- **Flexible Licensing**: Toggle between PAYG and BYOL without redeployment via the IaaS Agent Extension",

          "Exam Gotchas": "- Ephemeral storage (D: drive) is **NOT durable** — data lost on reboot/maintenance; use only for TempDB, page files, swap\n- Ultra Disk requires special configuration different from Premium SSD\n- Always On AG **synchronous commit** requires low latency (same region); cross-region must use **async**\n- **FCI is NOT a DR solution** — provides HA within a single region only; needs AG or log shipping for DR\n- Azure Site Recovery results in **higher RPO** — not recommended for transactional DBs without supplementary measures\n- Storage Spaces pools disks to increase IOPS — essential for production workloads\n- Page compression is the **superset** of row compression\n- Query Store, instant file initialization, lock pages in memory, and 'optimized for adhoc workloads' are recommended production settings"
        },

        "PaaS Deployment — Azure SQL Database": {
          "What It Is": "Azure SQL Database is a fully managed PaaS relational database service built on the SQL Server engine. It provides automatic backups, patching, high availability, and built-in intelligence. Available in single database and elastic pool deployment models with DTU or vCore purchasing.",

          "Purchasing Models and Service Tiers": "### DTU Model (Bundled Compute + Storage)\n\n| Tier | Best For | Max Storage |\n|---|---|---|\n| Basic | Light workloads | 2 GB |\n| Standard | Moderate workloads | 250 GB |\n| Premium | Intensive workloads, In-Memory OLTP | 4 TB |\n\n### vCore Model (Decoupled Compute / Storage)\n\n| Tier | Storage | Notes |\n|---|---|---|\n| General Purpose | 4 TB | Premium remote storage; provisioned or serverless |\n| Business Critical | 4 TB | Local SSD, lowest latency, In-Memory OLTP, free readable replica |\n| Hyperscale | 100 TB+ | Fast snapshots, read-scale replicas, independent storage scaling |\n\n### Serverless Compute\n- Autoscales between min/max vCores (0.5–16)\n- Autopause delay: 1 hr–7 days (or disabled)\n- Billed per second for compute; only storage billed when paused\n- **Not compatible with**: geo-replication, LTR backup, Elastic Jobs job DB, SQL Data Sync\n- Auto-pause available in **General Purpose tier only**\n\n### Elastic Pools\nShared resource pool across databases for multitenant SaaS with low average utilization. Set min/max DTU or vCore per database. Monitor for noisy neighbors.",

          "Backup, Restore, and Geo-Replication": "### Automated Backups\n- **Full**: Weekly\n- **Differential**: Every 12 hours\n- **Log**: Every 5–10 minutes\n- Default retention: **7 days** (configurable 1–35 days)\n- Long-Term Retention (LTR): up to 10 years (disabled by default)\n- Geo-redundant RA-GRS by default\n\n### Restore\n- PITR within retention window to same server\n- Geo-restore to any Azure region\n- **Cannot restore over an existing DB** — must drop or rename first\n- No T-SQL RESTORE command; No manual COPY_ONLY backups\n\n### Active Geo-Replication\n- Up to 4 readable async secondaries (same or different region)\n- Manual failover only\n\n### Auto-Failover Groups\n- Built on geo-replication\n- Provides read-write and read-only listener endpoints\n- No connection string changes on failover\n- Automatic or manual failover",

          "Elastic Features and Automatic Tuning": "### Elastic Query\nT-SQL across multiple databases using three/four-part names. Supports:\n- **Vertical partitioning**: Different schemas across databases\n- **Horizontal partitioning / sharding**: Same schema, partitioned data\n\n### Elastic Jobs\n- SQL Agent replacement for Azure SQL Database\n- Runs T-SQL across multiple targets (cross-subscription/region)\n- Parallel execution with auto-retry\n\n### Automatic Tuning\n- ML-based identification of index opportunities\n- Creates indexes, drops unused/duplicate indexes, forces last good execution plan\n- Tests indexes on a DB copy first before applying\n- **Enabled at server level**, inherited by databases (can be disabled per database)",

          "Hyperscale Details": "- **Independent scaling**: Compute and storage scale separately; storage auto-grows with no hard cap\n- **Instant backups**: File snapshots — not dependent on data size\n- **Fast restores**: Minutes regardless of database size\n- **Read-scale replicas**: `ApplicationIntent=ReadOnly`\n- **Cannot revert** to General Purpose or Business Critical after conversion\n- Rapid scale up/down in seconds/minutes",

          "Exam Gotchas": "- Default backup retention: **7 days**; max 35 days for vCore\n- Hyperscale **CANNOT be reverted** to General Purpose or Business Critical\n- Serverless auto-pause is **General Purpose only** — Hyperscale serverless does not support auto-pause\n- Elastic Jobs replace SQL Agent for SQL Database (Managed Instance still has SQL Agent)\n- Automatic tuning is **enabled at server level** and inherited by databases; can disable per database\n- Business Critical: **one free readable secondary** replica\n- Scaling operations end with a brief connection interruption — **implement retry logic**\n- Firewall rules can be set at server level or database level"
        },

        "PaaS Deployment — Azure SQL Managed Instance": {
          "What It Is": "Azure SQL Managed Instance is a fully managed SQL Server instance in the cloud, offering near 100% compatibility with on-premises SQL Server. It provides PaaS benefits (auto backups, patching, HA) while preserving instance-scoped features (SQL Agent, CLR, cross-DB queries, Service Broker, system DBs). Supports up to 100 databases per instance.",

          "Service Tiers and Network": "### Service Tiers\n\n| Tier | Max Storage | Latency | Notes |\n|---|---|---|---|\n| General Purpose | 8 TB | Higher | Premium remote storage; storage-replication HA |\n| Business Critical | 16 TB | Lowest | Local SSD; Always On AG replicas; In-Memory OLTP; free readable replica |\n\n### Network Configuration\n- Deployed in a **dedicated VNet subnet** — private IP only by default\n- **Public endpoint**: Optional (port **3342**); requires PowerShell enable by DBA + NSG port open by NetAdmin\n- On-premises connectivity via VPN Gateway (P2S/S2S) or ExpressRoute\n- DNS zone must match between primary and secondary in failover groups",

          "Managed Instance Link": "- Based on **Distributed Availability Groups (DAG)**\n- One link per database\n- **One-way replication**: SQL Server 2016/2019\n- **Two-way replication**: SQL Server 2022 (online failover, offline failback currently)\n- Use cases: DR failover to cloud, read-only workload offload, automated cloud backups\n- Cutover in seconds; no SQL version/edition restrictions beyond SQL 2016+ Enterprise/Standard/Developer\n- Does **NOT** support Filestream/Filetable",

          "Instance Pools": "- Pre-provision compute resources shared across multiple Managed Instances on the same VM\n- Fast deployment (~10 minutes)\n- Cost-efficient for migrating many small SQL Server instances\n- All instances within a pool share the same underlying VM",

          "Backups and Restore (MI-Specific)": "Same automatic backup schedule as SQL Database (Full weekly, Differential 12h, Log 5–10 min), plus:\n\n- Supports **COPY_ONLY backup to URL** (SQL Database does **not**)\n- Supports **T-SQL RESTORE from URL** (not local storage)\n- Cannot overwrite existing database during restore\n- Must disable TDE for user-initiated COPY_ONLY backups\n- Supports: `FILELISTONLY`, `HEADERONLY`, `LABELONLY`, `VERIFYONLY`\n- Cannot restore backups with: multiple log files, multiple backup sets, or In-Memory/FILESTREAM data",

          "Comparison with SQL Database": "| Feature | SQL Managed Instance | SQL Database |\n|---|---|---|\n| SQL Agent | ✅ Yes | ❌ No (use Elastic Jobs) |\n| CLR | ✅ Yes | ❌ No |\n| Cross-DB Queries | ✅ Native | ⚠️ Elastic Query only |\n| System DBs | ✅ Accessible | ❌ No |\n| T-SQL RESTORE | ✅ Yes | ❌ No |\n| COPY_ONLY Backup | ✅ Yes | ❌ No |\n| Service Broker | ✅ Yes | ❌ No |\n| DTU Model | ❌ No | ✅ Yes |\n| Elastic Pools | ❌ No | ✅ Yes |\n| Hyperscale | ❌ No | ✅ Yes |",

          "Exam Gotchas": "- SQL Agent exists in MI — **Elastic Jobs are NOT available**\n- COPY_ONLY backup to URL = **MI only** (not SQL Database)\n- T-SQL RESTORE = **MI only**\n- Public endpoint port: **3342** (not 1433)\n- Instance pools share the same VM — good for small DB consolidation\n- Link feature uses **DAG** (not log shipping); one link per database\n- DTU model is **NOT supported** by Managed Instance — vCore only\n- Failover groups require **matching DNS zones** between primary and secondary\n- Cross-DB queries work natively in MI; SQL Database requires Elastic Query\n- Elastic pools do **not exist** in MI — each instance has dedicated resources"
        },

        "Migration to Azure SQL": {
          "What It Is": "Migrating SQL Server workloads to Azure involves choosing between **offline** (full downtime) and **online** (minimal downtime) methods. The right path depends on your target platform (SQL Database vs. Managed Instance) and downtime tolerance. Assess source databases first using Azure Migrate, DMA, or Azure Arc.",

          "Migration to Azure SQL Database": "### Offline Methods\n- **DMS** (Database Migration Service): Recommended for large migrations; supports table selection; use Azure CLI/PowerShell\n- **BACPAC/SqlPackage**: Compressed file; faster than portal import; scale up target tier during import\n- **BCP**: Table-level export/import\n- **Azure Data Factory**: Data migration pipelines\n- **Portal Import Wizard**: Simple UI; slower than SqlPackage\n\n### Online Method\n**Transactional Replication** is the **only online method** for SQL Database:\n- Push subscriber only\n- Configure from SSMS/T-SQL (not portal)\n- Components: Publisher, Subscriber, Distributor, Article, Publication, Subscription\n\n### Key Considerations\n- Schema must be deployed to target **before** data migration\n- Scale up target SKU during migration, scale down after\n- Retry logic: first retry after 5s, exponential backoff to 60s max\n- Use a **new connection** to retry SELECT failures",

          "Migration to Azure SQL Managed Instance": "### Online Methods\n\n| Method | Cutover | Notes |\n|---|---|---|\n| **MI Link** | Seconds | DAG-based; SQL 2016+; supports reverse migration |\n| **Log Replay Service (LRS)** | Longer | Log shipping tech; 30-day limit; no read during migration |\n| **Azure Arc** | — | Portal-based; unified assess→migrate→monitor; built-in Copilot |\n| **Transactional Replication** | — | MI can be publisher/distributor/subscriber |\n\n### Offline Methods\n- **Native backup/restore**: Backup to URL, restore to MI; use COPY_ONLY for user backups\n- **BACPAC/SqlPackage**: NOT supported via portal — use SqlPackage CLI directly\n\n### MI Link vs LRS\n\n| | MI Link | LRS |\n|---|---|---|\n| Cutover speed | Seconds | Longer |\n| Read during migration | ✅ Yes | ❌ No (restoring state) |\n| Min SQL version | 2016+ | 2012+ |\n| Max duration | Unlimited | 30 days |\n| Reverse migration | ✅ Yes | ❌ No |",

          "Performance Recommendations": "- Monitor and mitigate source data file I/O latency before migration\n- Scale up target (Business Critical Gen5 8 vCore or Hyperscale recommended)\n- Ensure adequate network bandwidth for maximum log ingestion rate\n- Choose **highest service tier during migration**, scale down after\n- Minimize distance between BACPAC files and target region\n- Disable auto update/auto create statistics during migration\n- Partition tables and indexes; drop indexed views; recreate after migration\n- DMS: up to **10 concurrent DB migrations** per self-hosted IR node",

          "Exam Gotchas": "- Transactional Replication is the **only online migration** for SQL Database — all other methods are offline\n- MI Link uses **DAG** (not log shipping like LRS)\n- LRS has a **30-day limit** — automatically canceled after 30 days\n- COPY_ONLY backup = **MI only** (not SQL Database)\n- BACPAC import via portal **NOT supported** for Managed Instance — use SqlPackage CLI\n- Cannot restore over existing DB — must remove it first (both SQL DB and MI)\n- MI Link does **NOT** support Filestream/Filetable\n- Migration statuses: **Preparing for copy → Copying → Copy finished → Rebuilding indexes → Succeeded**\n- Azure Arc migration discovery runs automatically every weekend; can trigger manually"
        }
      }
    },
    "Module 2": {
      "topics": {
        "Authentication and Authorization": {
          "What It Is": "Azure SQL offers multiple authentication options and a hierarchical authorization model spanning Azure RBAC, server-level principals, database users, and object permissions. Security is managed through logins, users, roles, and permissions at both server and database scopes.",

          "Authentication Options": "| Method | Available On | Notes |\n|---|---|---|\n| **SQL Server Authentication** | All Azure SQL offerings | Login/password stored in SQL Server |\n| **Microsoft Entra ID** | SQL DB, SQL MI | MFA support; best practice: admin = **Entra group**, not single user |\n| **Windows Authentication** | SQL Server on Azure VM only | Not available in SQL Database or MI |\n\n### Azure RBAC (Resource Level)\nControls Azure resource operations — **decoupled** from database-level SQL permissions:\n- **SQL DB Contributor**: Manage databases; cannot read data\n- **SQL Security Manager**: Manage security policies; cannot access data\n- **SQL Server Contributor**: Manage servers/databases; cannot access data",

          "Security Principals and Roles": "### Server-Level (Logins)\n- Created in `master` database\n- New logins can be added; new server roles **cannot** be created in Azure SQL Database\n\n### Database-Level (Users)\n- Mapped to a login, or created as **contained database users** (recommended for Azure SQL DB)\n\n### Database Roles\n\n| Role | Permissions |\n|---|---|\n| db_owner | Full admin |\n| db_datareader | Read all tables/views |\n| db_datawriter | INSERT, UPDATE, DELETE on all tables/views |\n| db_ddladmin | Modify database objects |\n| db_securityadmin | Grant permissions |\n| db_backupoperator | **No effect in Azure SQL DB** |\n\n### Azure SQL-Specific Master DB Roles\n- **loginmanager**: Create logins\n- **dbmanager**: Create/delete databases",

          "Object Permissions and Ownership Chains": "### Permissions\n- `SELECT`, `INSERT`, `UPDATE`, `DELETE` — on tables/views\n- `CONTROL` (full rights), `EXECUTE` (procedures/functions), `ALTER` (change definition), `VIEW DEFINITION`, `REFERENCES` (view FK)\n\n### Ownership Chains\nIf a stored procedure and the tables it accesses share the same owner, the user only needs `EXECUTE` on the procedure — they **inherit table access** during execution.\n\n> ⚠️ **Dynamic SQL breaks ownership chains.** The user needs direct permissions on objects accessed via dynamic SQL, because it executes outside the stored procedure context.\n\n### Application Roles\n- Activated by password (not membership)\n- Permissions apply only while the role is active",

          "Transient Faults and Retry Logic": "Transient faults occur during reconfiguration events and typically resolve in under 60 seconds.\n\n**Retry pattern:**\n1. First retry after **5 seconds**\n2. Exponential backoff up to **60 seconds** maximum\n3. `SELECT` failures must be retried in a **new connection** — do not retry on the same connection",

          "Exam Gotchas": "- **Contained database users** are the recommended pattern for Azure SQL Database (not logins in master)\n- `db_backupoperator` has **no effect** in Azure SQL Database — only in SQL Server and MI\n- `securityadmin` server role should be treated as equivalent to **sysadmin** (can grant any permission)\n- **Dynamic SQL breaks ownership chains** — users need direct table permissions\n- **DENY always overrides GRANT** regardless of order\n- RBAC roles manage Azure resource operations, not database-level data access"
        },

        "Data Encryption (TDE, Always Encrypted, TLS)": {
          "What It Is": "Azure SQL provides multiple encryption layers: **TDE** for data at rest, **Always Encrypted** for client-side column encryption, and **TLS** for data in transit. Each protects against different threats and serves different compliance requirements.",

          "Transparent Data Encryption (TDE)": "Encrypts data at rest at the **page level** — encrypted when written to disk, decrypted when read into memory. **Does NOT encrypt at column or table level.**\n\n### Auto-Enabled Dates\n- Azure SQL Database: databases created after **May 2017**\n- Azure SQL MI: databases created after **February 2019**\n\n### On-Premises / VM Setup\n1. Create master key\n2. Create certificate in master\n3. Create database encryption key\n4. Enable: `ALTER DATABASE ... SET ENCRYPTION ON`\n\n### Key Types\n| Type | Notes |\n|---|---|\n| **Service-managed key** | Microsoft-provided; default |\n| **Customer-managed key (BYOK)** | Via Azure Key Vault; if CMK is removed, all DB connections close |\n\nAutomatic key rotation: server checks Azure Key Vault every **60 minutes**.",

          "Always Encrypted": "Encrypts data **within the client application** — protects from high-privileged users (DBAs, cloud admins).\n\n### Two Keys Used\n- **Column Master Key (CMK)**: Stored outside the database (Azure Key Vault, Windows cert store)\n- **Column Encryption Key (CEK)**: Stored in the database, encrypted by CMK\n\n### Encryption Types\n| Type | Ciphertext | Supports |\n|---|---|---|\n| **Deterministic** | Same value → same ciphertext | Equality, joins, grouping, indexing |\n| **Randomized** | Same value → different ciphertext | Return in results only |\n\nCannot change encryption type after column is created.\n\n**Application requirements**: Always Encrypted driver + `Column Encryption Setting=enabled` in connection string.\n\n### Secure Enclaves\nSecured memory region enabling pattern matching, comparison, and indexing on **randomized encrypted columns** — appears as a black box even with a debugger.",

          "TLS and Encrypted Connections": "Transport Layer Security encrypts **data in transit**.\n\n**Certificate requirements:**\n- Must be in the local computer certificate store\n- SQL Server service account must have access (missing access = **restart failure**)\n- Must be within valid period\n\n**Configure via SQL Server Configuration Manager:**\n1. Certificate tab → select certificate\n2. Flags tab → `ForceEncryption = Yes`\n\nTest in SSMS: Connection Properties → Encrypt connection.",

          "SQL Injection and Key Vault": "### SQL Injection\n- Caused by dynamic SQL with unsanitized user input\n- **Prevention**: Validate input, use parameterized queries\n- Advanced Threat Protection provides an extra monitoring layer\n\n### Azure Key Vault\n- Stores secrets, certificates, and keys\n- Has its **own RBAC** — subscription admin does **NOT** automatically have access\n- SQL Server supports AKV for: TDE, Backup Encryption, and Always Encrypted\n- **Setup**: Create credential → Create asymmetric key in AKV → Create asymmetric key in DB using `FROM PROVIDER`",

          "Exam Gotchas": "- TDE encrypts at the **page level**, not column level\n- Always Encrypted encrypts in the **client application**, not the database engine\n- TDE auto-enabled for SQL DB (post-May 2017) and MI (post-Feb 2019) — older databases must be enabled manually\n- Removing the customer-managed key from AKV **closes all database connections**\n- Always Encrypted keys must **never be generated on the database server**\n- Deterministic encryption supports equality/joins/indexing; **randomized does not**\n- For TLS: missing service account access to certificate causes **SQL Server restart to fail**\n- AKV has its **own RBAC** separate from subscription RBAC"
        },

        "Firewall, Network Security and Private Link": {
          "What It Is": "Azure SQL provides network security through server-level and database-level firewall rules, Virtual Network service endpoints, and Private Link for private connectivity. These layers control which IP addresses, VNets, and networks can connect to Azure SQL resources.",

          "Firewall Rules": "### Server-Level Rules\n- Allow connections to **all databases** on the server\n- Configured via Azure portal or `sp_set_firewall_rule` in **master**\n- 'Allow Azure Services and resources' setting counts as **one firewall rule**\n\n### Database-Level Rules\n- Grant access to specific IPs **per database only**\n- Configured via T-SQL **only**: `sp_set_database_firewall_rule` (run from within the user database)\n\n### Connection Evaluation Flow\n```\nConnection attempt\n  → Check database-level rules first\n  → If no match, check server-level rules\n  → If neither matches, connection is rejected\n```",

          "Virtual Network Endpoints and Private Link": "### VNet Service Endpoints\n- Allow traffic from a specific Azure VNet subnet\n- Apply at **server level** only\n- Service endpoint applies to **one region only** (the endpoint's region)\n- VNet must have outbound access to the database's public IP via service tags\n\n### Private Link\n- Connect using a private endpoint — traffic over **Azure backbone**, not the public internet\n- Provides a **private IP** on the VNet\n- Supports ExpressRoute\n- Benefits: cross-region connectivity, protection against data exfiltration",

          "Exam Gotchas": "- Server-level rules: portal or T-SQL (`sp_set_firewall_rule` in **master**)\n- Database-level rules: **T-SQL only** (`sp_set_database_firewall_rule` in **user database**)\n- Firewall checks **database-level rules first**, then server-level\n- VNet service endpoints apply to **one region only**\n- Private Link provides a private IP and keeps traffic **off the public internet**\n- 'Allow Azure Services' toggle counts as **one firewall rule**"
        },

        "Compliance Controls (Auditing, Classification, Masking, RLS)": {
          "What It Is": "Azure SQL provides compliance controls including data classification, auditing, dynamic data masking, and row-level security. These features help meet regulatory requirements by identifying sensitive data, tracking access, obfuscating data, and restricting row-level access.",

          "Data Classification": "- Performed per column using **sensitivity labels** and **information types**\n- Stored in `sys.sensitivity_classifications` (SQL Server 2019+, Azure SQL DB, MI)\n- Classification engine scans based on column **names** — a column named `column1` containing emails would **NOT** be auto-detected\n\n**Configure via:**\n- Azure portal (Data Discovery & Classification)\n- SSMS sensitivity wizard\n- T-SQL: `ADD SENSITIVITY CLASSIFICATION TO ... WITH (LABEL='PII', INFORMATION_TYPE='Email')`\n\nCustomize taxonomy in **Microsoft Defender for Cloud** — only users with **admin rights on the root management group** can manage labels.",

          "Server and Database Audit": "Tracks database events and writes to:\n- Azure Storage account\n- Log Analytics workspace\n- Event Hubs\n\n**Best practice**: Enable **server-level auditing** only — database-level only needed for specific per-DB settings.\n\n### Default Audit Groups\n- `BATCH_COMPLETED_GROUP`\n- `SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP`\n- `FAILED_DATABASE_AUTHENTICATION_GROUP`\n\nRead-only replicas are automatically audited. Audit records include `data_sensitivity_information` when combined with data classification.",

          "Dynamic Data Masking": "Obfuscates data at the **presentation layer** — data is still stored unencrypted.\n\n| Mask Function | Output Example |\n|---|---|\n| `default()` | `XXXX`, `0`, `01.01.1900` |\n| `partial(0, \"XXXX-XXXX-XXXX-\", 4)` | `XXXX-XXXX-XXXX-1234` (credit card) |\n| `email()` | `aXXX@XXXXXXX.com` |\n| `random(1, 12)` | Random number in range |\n\n- Unmasked data visible to users with the `UNMASK` permission\n- `SELECT INTO` / `INSERT INTO` from masked columns **copies masked data**",

          "Row-Level Security (RLS)": "Restricts which rows a user can see — equivalent to an automatic `WHERE` clause.\n\n**Setup flow:**\n1. Create users/roles\n2. Create inline table-valued function (TVF) with `SCHEMABINDING`\n3. Create security policy: `CREATE SECURITY POLICY`\n4. Assign predicate to policy\n\n### Predicate Types\n| Type | Affects |\n|---|---|\n| **Filter predicates** | SELECT, UPDATE, DELETE |\n| **Block predicates** | AFTER INSERT, AFTER UPDATE, BEFORE UPDATE, BEFORE DELETE |\n\n> ⚠️ Risk of **side-channel attacks** via divide-by-zero — limit unplanned queries. Best practice: separate schema for predicates.",

          "Exam Gotchas": "- Data classification is based on column **names** — may miss poorly named columns\n- Only **root management group admins** can manage sensitivity labels\n- Best practice: enable **server-level auditing only** (not database-level unless necessary)\n- Dynamic Data Masking works at the **presentation layer** — data is still stored unencrypted\n- RLS requires **inline TVF with SCHEMABINDING** + `CREATE SECURITY POLICY`\n- RLS **filter predicates** affect SELECT, UPDATE, DELETE; **block predicates** affect INSERT and UPDATE\n- Side-channel attacks are possible with RLS"
        },

        "Defender for SQL, Ledger and Purview": {
          "What It Is": "Microsoft Defender for SQL provides vulnerability assessment and threat protection. Ledger provides tamper-evidence via cryptographic hashing. Microsoft Purview provides unified data governance, automated scanning, classification, and lineage across the data estate.",

          "Microsoft Defender for SQL": "Includes **SQL Vulnerability Assessment** + **Advanced Threat Protection (ATP)**.\n\n- Vulnerability assessment uses a knowledge base of security rules — flags misconfigurations, excessive permissions, exposed sensitive data\n- Must enable at **subscription level** (recommended); requires a storage account\n\n### ATP Alert Types\n- Vulnerability to SQL injection\n- Potential SQL injection\n- Access from unusual location / data center\n- Access from unfamiliar principal\n- Access from potentially harmful application\n- Brute force SQL credentials\n\n**Required role**: SQL Security Manager, or database/server admin.",

          "Ledger": "Tamper-evidence using **cryptographic hashing (SHA-256)** — each transaction is cryptographically linked like a blockchain.\n\n| Table Type | Use Case | Allows |\n|---|---|---|\n| **Updatable ledger tables** | INSERT/UPDATE/DELETE apps | All DML; tracks history in system-versioned table |\n| **Append-only ledger tables** | Insert-only apps (accounting, SIEM) | INSERT only; UPDATE/DELETE blocked at API level |\n\n- Ledger can only be **enabled during database creation** — cannot be added later\n- `LEDGER = ON` in `CREATE TABLE` for individual tables\n- Setting 'Enable for all future tables' makes all new tables ledger tables",

          "Microsoft Purview": "Unified data governance — automated discovery, classification, and lineage across on-premises, multicloud, and SaaS.\n\n### Scanning Authentication Options\n| Method | Notes |\n|---|---|\n| System-assigned managed identity | Recommended; **not for self-hosted IR** |\n| User-assigned managed identity | Preview; **not for self-hosted IR** |\n| Service Principal | Has expiration date |\n| SQL Authentication | Always works, including self-hosted IR |\n\n**Required roles**: Data Source Administrator + Data Reader\n\n**Data lineage**: Extracted from stored procedure runs. Enable lineage extraction toggle in scan setup. Incremental scans run every **6 hours**.",

          "Exam Gotchas": "- Ledger can **only be enabled during database creation** — cannot be added later\n- Append-only ledger tables **block UPDATE and DELETE** at the API level\n- Managed identities do **NOT** work with self-hosted IR for Purview — use service principal or SQL auth\n- Vulnerability assessment requires enabling **Defender for SQL at subscription level**\n- Recommended audit groups: `BATCH_COMPLETED`, `SUCCESSFUL_DATABASE_AUTHENTICATION`, `FAILED_DATABASE_AUTHENTICATION`\n- Purview lineage extraction runs every **6 hours**\n- **Data Source Administrator + Data Reader** roles required for Purview source registration"
        }
      }
    },
    "Module 3": {
      "topics": {
        "Performance Monitoring and Tuning": {
          "What It Is": "Azure provides multiple monitoring tools — Azure Monitor, Perfmon, Extended Events, Query Performance Insight, and Database Watcher — to track metrics, identify bottlenecks, and tune performance. Establishing baselines and correlating OS metrics with SQL Server metrics is critical for proactive performance management.",

          "Azure Monitor and Metrics": "- Active metric data retained for **93 days**; can archive to Azure Storage\n- **Azure Monitor Insights** provides extra data points (storage latency, memory) stored in a **Log Analytics workspace** (queried via KQL)\n\n### Alert Types\n- **Static**: Fixed threshold\n- **Dynamic Thresholds**: Learns historical behavior, detects seasonality\n\n### Key SQL Server Performance Counters\n| Counter | Threshold / Notes |\n|---|---|\n| % Processor Time | Overall CPU usage |\n| Avg. Disk sec/Read or Write | < 20ms general; < 10ms Premium SSD |\n| Processor Queue Length | > 0 = CPU pressure |\n| Page Life Expectancy | Sudden drops = memory pressure |\n| Batch Requests/sec | Overall throughput baseline |\n| SQL Compilations/Recompilations/sec | High = plan cache churning |\n\n`sys.dm_os_wait_stats` reveals what threads are waiting on.",

          "Extended Events": "Lightweight monitoring system, successor to SQL Profiler.\n\n### Channels\n| Channel | Use Case |\n|---|---|\n| Admin | Administrator actions |\n| Operational | Common diagnostics |\n| Analytic | High-volume performance data |\n| Debug | **Microsoft support use only** |\n\n### Targets\n| Target | Mode | Notes |\n|---|---|---|\n| Event Counter | **Sync** | Counts event occurrences |\n| Event File | Async | Persists to blob storage |\n| Ring Buffer | Async | In-memory circular buffer |\n| ETW | **Sync** | Correlates with OS events |\n| Histogram | Async | Counts by column value |\n| Event Pairing | Async | Matches paired start/stop events |\n\n- Filters apply to **a single field on a single event** — need separate filter per event\n- Causality tracking adds GUID + sequence number to trace event order",

          "Query Performance Insight and Database Watcher": "### Query Performance Insight (Azure SQL DB)\n- Found under **Intelligent Performance** in Azure portal\n- Views: Long Running Queries, Top Resource Consuming Queries, Custom\n- Metrics: CPU, Data IO, Log IO, memory\n- Query IDs correlate to Query Store\n- **Does NOT show execution plans**\n\n### Database Watcher (Preview)\n- For Azure SQL DB and MI\n- Collects data into **Azure Data Explorer** or **Real-Time Analytics (Fabric)**\n- Low latency (seconds); configurable datasets and retention\n- Supports parameterized alert templates",

          "Exam Gotchas": "- Azure Monitor retains metrics for **93 days**\n- Extended Events filters apply to **a single field on a single event**\n- Most XE targets are async; **Event Counter and ETW are sync**\n- Query Performance Insight does **NOT** show execution plans\n- Database Watcher stores data in **Azure Data Explorer or Real-Time Analytics**\n- `db_backupoperator` has **no effect** in Azure SQL Database"
        },

        "Resource Configuration (Storage, VM, TempDB, Resource Governor)": {
          "What It Is": "Proper configuration of Azure storage, VM sizing, TempDB, and Resource Governor is essential for optimal SQL Server performance. Each component has specific best practices for balancing cost, performance, and resource allocation.",

          "Azure Storage for SQL Server": "| Disk Type | Latency | Best For |\n|---|---|---|\n| Ultra Disk | Sub-millisecond | Mission-critical OLTP |\n| Premium SSD | Single-digit ms | Production workloads |\n| Standard SSD | — | Dev/test environments |\n| Standard HDD | — | Backups only |\n\n### Best Practices\n- **Data files**: Separate volume, **read-cache ON**\n- **Log files**: Separate volume, **NO cache**\n- **TempDB**: D: drive for lowest latency\n- Plan extra **20% IOPS** headroom\n- Enable **instant file initialization**\n- **Storage Spaces striping**: Sums IOPS across disks; no redundancy needed (Azure provides 3x)\n- **Ultra Disk**: Scales independently — no striping needed",

          "VM Sizing and TempDB": "### Constrained Cores\nReduce vCPU count while keeping full memory/storage/I/O — reduces SQL Server licensing cost for memory-intensive but low-CPU workloads.\n\n### TempDB Configuration\n| Platform | Files | Configurable? |\n|---|---|---|\n| SQL Server on VM | Up to 8 (match CPU count for heavy workloads) | ✅ Yes |\n| Azure SQL Database | Scales with vCores (2 vCores = 4 files, max 16) | ❌ Not via T-SQL |\n| SQL Managed Instance | Always **12 files** | ❌ No |\n\n- TempDB always on **local SSD** across all platforms\n- `MIXED_PAGE_ALLOCATION=OFF`, `AUTOGROW_ALL_FILES=ON` (defaults, not configurable in Azure SQL)\n- TempDB **metadata optimization** (SQL 2019) is **NOT available** in Azure SQL",

          "MAXDOP and Resource Governor": "### MAXDOP Configuration Options\n- DB scoped config: `ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = N`\n- `sp_configure` (SQL MI)\n- Query hint: `OPTION (MAXDOP N)`\n- Resource Governor classifier (SQL MI)\n\n### Resource Governor (SQL Server + SQL MI only)\n**Not available in Azure SQL Database.**\n\n**Components:**\n- **Resource pools**: Min/max CPU%, memory%, IOPS, NUMA affinity\n- **Workload groups**: Classified by function\n- **Classifier function**: Runs at connection time to assign sessions to pools\n\n> Changes only affect **new sessions**. CPU min/max applies only during contention.",

          "Exam Gotchas": "- Ultra Disk scales independently — **no striping needed**\n- Constrained cores reduce vCPU while keeping full memory/I/O\n- TempDB in Azure SQL DB: scales with vCores (max 16); MI always **12 files**\n- TempDB **metadata optimization NOT available** in Azure SQL\n- **Resource Governor NOT available** in Azure SQL Database\n- Pool changes only affect **new sessions**\n- Classifier function runs **at connection time**\n- MAXDOP configurable via DB scoped config, `sp_configure` (MI), query hints, or Resource Governor (MI)"
        },

        "Database Optimization (Indexes, Statistics, Auto Tuning, IQP)": {
          "What It Is": "Ongoing database maintenance (indexes, statistics) combined with automatic tuning and Intelligent Query Processing features ensure optimal query performance. Azure SQL Database provides self-managing capabilities that reduce manual DBA intervention.",

          "Index Maintenance": "### Fragmentation Thresholds\n| Fragmentation Level | Action | Updates Stats? |\n|---|---|---|\n| 5–30% | **Reorganize** (online, leaf-level defrag) | ❌ No |\n| > 30% | **Rebuild** (drop/recreate) | ✅ Yes |\n\n- Online rebuild requires extra temporary space\n- **Resumable rebuild**: SQL Server 2017+\n- **MAXDOP on resumable**: SQL Server 2019+\n\n### Monitoring DMVs\n- B-tree indexes: `sys.dm_db_index_physical_stats`\n- Columnstore: `sys.dm_db_column_store_row_group_physical_stats`",

          "Statistics and Maintenance Automation": "### Statistics\n- BLOBs in user databases with data distribution info\n- `AUTO_CREATE_STATISTICS = ON` by default\n- View via `sys.stats` + `sys.dm_db_stats_properties`\n\n### Automation Options by Platform\n| Platform | Automation Tool |\n|---|---|\n| SQL Server VM | SQL Agent + Task Scheduler |\n| Azure SQL Database | Azure Automation runbooks, Elastic Jobs |\n| SQL Managed Instance | SQL Agent |\n\n### DB Scoped Configuration\n`ALTER DATABASE SCOPED CONFIGURATION`: MAXDOP, Legacy CE, Last Query Plan Stats (compat 150), Optimize for Ad Hoc\n`ALTER DATABASE`: recovery model, auto tuning, auto-create/update stats, Query Store, snapshot isolation",

          "Automatic Tuning (Azure SQL DB)": "### Force Last Good Plan\n- Engine automatically forces last known good plan when a regression is detected\n- Plan reverts if not better after **15 executions**\n- **Conditions**: previous plan had higher error rate AND estimated CPU gain > 10 seconds\n- Query Store must be enabled and **Read-Write**\n- Check via `sys.dm_db_tuning_recommendations` and `sys.database_automatic_tuning_options`\n\n### Automatic Index Management (Azure SQL DB Only)\n- Creates/drops indexes based on workload analysis\n- Monitors resource usage to avoid degradation\n- Dropped indexes are recreated automatically if performance degrades",

          "Intelligent Query Processing (Compat 150)": "| Feature | Description |\n|---|---|\n| **Adaptive Joins** | Defer join type (hash vs nested loops) based on actual rows; batch mode only |\n| **Interleaved Execution** | MSTVFs get actual row count before plan compilation (was fixed at 1/100) |\n| **Memory Grant Feedback** | Adjusts memory grant up/down based on actual usage |\n| **Table Variable Deferred Compilation** | TVs get actual row count at first compilation (was fixed at 1 row) |\n| **Batch Mode on Rowstore** | Batch processing without columnstore dependency |\n| **Scalar UDF Inlining** | UDFs transformed into subqueries for parallelism |\n| **Approx Count Distinct** | `APPROX_COUNT_DISTINCT` — ~2% error at 97% confidence |",

          "Exam Gotchas": "- **Rebuild updates statistics**; reorganize does **NOT**\n- Resumable rebuild: SQL 2017+; MAXDOP on resumable: SQL 2019+\n- Automatic plan correction forces after **15 executions** of the better query\n- Auto index management is **Azure SQL DB only**\n- Query Store must be **Read-Write** for automatic tuning\n- Adaptive joins only in **batch execution mode**\n- Scalar UDF inlining enables parallelism\n- Approx Count Distinct: **2% error, 97% confidence**"
        }
      }
    },
    "Module 4": {
      "topics": {
        "Query Performance Optimization": {
          "What It Is": "SQL Server uses a cost-based query optimizer that generates execution plans based on statistics. Understanding query plans, the Query Store, SARGability, parameter sniffing, and blocking/locking mechanics is essential for diagnosing and resolving query performance issues.",

          "Query Plans and Lightweight Profiling": "### Query Processing Flow\n```\nParse → Algebrizer (binding) → Check plan cache (query_hash) → Optimize → Execute\n```\n\n### Plan Types\n| Plan Type | How to Get | Query Executes? |\n|---|---|---|\n| Estimated | `SET SHOWPLAN_ALL ON` | ❌ No |\n| Actual | `SET STATISTICS PROFILE ON` | ✅ Yes |\n| Live Query Statistics | SSMS graphical only | ✅ Yes (refreshes every 1s) |\n\n### Lightweight Query Profiling\n- ~**2% overhead** (vs legacy ~**75%**)\n- Default in SQL Server 2019+ and Azure SQL\n- Query-level: `OPTION(USE HINT ('QUERY_PLAN_PROFILE'))`\n- Last actual plan: `sys.dm_exec_query_plan_stats` (DB scoped config `LAST_QUERY_PLAN_STATS` or trace flag 2451)",

          "Query Store": "Per-database query performance history. **Enabled by default** in Azure SQL DB.\n\n### Three Internal Stores\n- **Plan store**: Estimated execution plans\n- **Runtime stats store**: Execution statistics per plan\n- **Wait stats store**: Wait statistics per query\n\n### Key Views\nRegressed Queries, Top Resource Consuming, Overall Resource Consumption, Queries With Forced Plans, High Variation, Wait Statistics, Tracking Query\n\n### Plan Forcing\n- SSMS GUI or `sp_query_store_force_plan @query_id=N, @plan_id=N`\n- **Automatic plan correction** (`FORCE_LAST_GOOD_PLAN`) enabled by default for new Azure SQL DB",

          "SARGability and Parameter Sniffing": "### SARGable vs Non-SARGable Predicates\n| Predicate | SARGable? | Reason |\n|---|---|---|\n| `WHERE City = 'London'` | ✅ Yes | Direct column comparison |\n| `WHERE City LIKE 'M%'` | ✅ Yes | Leading constant; index seek possible |\n| `WHERE City LIKE '%M%'` | ❌ No | Leading wildcard |\n| `WHERE LEFT(City, 1) = 'M'` | ❌ No | Function applied to column |\n| `WHERE CONVERT(CHAR(10), Date, 121) = '...'` | ❌ No | Conversion applied to column |\n\n### Parameter Sniffing\n- First parameter value shapes the cached plan\n- **Solutions**: `OPTION(RECOMPILE)`, `OPTION(OPTIMIZE FOR UNKNOWN)`, conditional recompile\n\n### Locking\n- Lock escalation: > **5,000 rows** → table lock\n- Deadlock victim = **least work to roll back**\n- Deadlocks captured in `system_health` Extended Events session",

          "Exam Gotchas": "- Estimated plans do **NOT execute** the query\n- Live Query Statistics is **graphical only** (SSMS)\n- Lightweight profiling ~**2% overhead** vs legacy 75%\n- Lock escalation at **5,000 rows**\n- Deadlock victim = **least work to roll back**\n- `sys.dm_db_resource_stats` snapshots every **15 seconds** (Azure SQL DB only)\n- Missing index DMVs are **starting points**, not mandates"
        },

        "Performance-based Database Design": {
          "What It Is": "Database design decisions (normalization, data types, indexing strategy) profoundly impact performance. OLTP systems favor normalized designs minimizing transaction times, while data warehouses use denormalized star schemas for complex analytical queries.",

          "Normalization and Schemas": "### Normal Forms\n- **1NF**: Separate tables, no repeating groups, primary key\n- **2NF**: All attributes depend on the complete composite key\n- **3NF**: No transitive dependencies\n- **Denormalization**: Fewer joins (faster reads) vs update anomalies\n\n### Schema Designs\n| Schema | Description | Joins |\n|---|---|---|\n| **Star schema** | Denormalized dimensions + central fact table | Fewer, faster |\n| **Snowflake schema** | Normalized dimensions | More; saves storage |",

          "Index Types": "| Index Type | Notes |\n|---|---|\n| **Clustered** | Table data in sorted order; **one per table**; keep key narrow, unique, selective |\n| **Nonclustered** | Separate structure; key + row pointer; add included columns to cover queries |\n| **Filtered** | Partial index with WHERE clause; ideal for bit columns with skewed distribution |\n| **Unique** | No duplicates; auto-created for PK/UNIQUE constraints |\n| **Columnstore** | Column-based; batch execution mode (~900 rows/batch); huge read improvement for analytics |\n\n### Columnstore Details\n- Bulk load minimum: **102,400 rows** → compressed rowgroups\n- Smaller loads → **delta store** (B-tree) → tuple mover (async background process)\n- **Nonclustered columnstore** needed for: XML, CLR, sql_variant, ntext, text, image\n- Batch mode provides up to **5x improvement**\n- **Resumable index** (SQL 2017+): only with `ONLINE = ON`",

          "Exam Gotchas": "- Clustered index = table data in sorted order; **heap** = no clustered index\n- Columnstore bulk load minimum: **102,400 rows** — below that goes to delta store\n- Resumable index only with **ONLINE = ON**\n- Nonclustered columnstore needed for: XML, CLR, sql_variant, ntext, text, image\n- Batch mode ~**900 rows** per batch\n- Check resumable status via `sys.index_resumable_operations`\n- Filtered indexes are ideal for **bit columns** with skewed distribution"
        },

        "Evaluate Performance Improvements": {
          "What It Is": "Wait statistics, index tuning, query hints, and Azure SQL-specific DMVs form the toolkit for evaluating and improving performance. Understanding the running vs. waiting dichotomy guides troubleshooting. Query Store hints allow plan shaping without code changes.",

          "Wait Statistics and Common Waits": "Every query thread is either **running** (using CPU) or **waiting** (blocked on a resource). Wait stats reveal the bottleneck.\n\n| Wait Type | Indicates |\n|---|---|\n| `RESOURCE_SEMAPHORE` | Memory pressure / insufficient memory grant |\n| `LCK_M_X` | Blocking / lock contention |\n| `PAGEIOLATCH_SH` | Storage I/O pressure / missing indexes |\n| `SOS_SCHEDULER_YIELD` | CPU pressure |\n| `CXPACKET` | Parallelism configuration issues |\n| `PAGEIOLATCH_UP` on 2:1:1 | TempDB PFS page contention |\n| `LOG_RATE_GOVERNOR` | Azure SQL DB log rate limiting |\n| `POOL_LOG_RATE_GOVERNOR` | Elastic pool log rate limiting |\n| `INSTANCE_LOG_GOVERNOR` | SQL MI log rate limiting |\n| `HADR_SYNC_COMMIT` | **Normal** for Business Critical tier |\n| `RBIO*` | Normal for Hyperscale |\n\nDMVs: `sys.dm_os_wait_stats` (MI), `sys.dm_db_wait_stats` (SQL DB)",

          "Query Hints and Query Store Hints": "### Query Hints (in T-SQL)\n`MAXDOP`, `RECOMPILE`, `OPTIMIZE FOR`, `OPTIMIZE FOR UNKNOWN`, `FAST N`, `LOOP/MERGE/HASH JOIN`, `USE PLAN`\n\n### Query Store Hints\n`sp_query_store_set_hints` — shape plans **without modifying application code**:\n- Force recompile on a specific query\n- Limit MAXDOP for a specific query\n- Force hash join\n- Use legacy compatibility level for a specific query\n\n### Azure SQL Resource DMVs\n| DMV | Platform | Notes |\n|---|---|---|\n| `sys.dm_db_resource_stats` | SQL DB | 15-second snapshots |\n| `sys.server_resource_stats` | MI | Resource usage |\n| `sys.dm_user_db_resource_governance` | SQL DB | Governance limits |\n| `sys.dm_instance_resource_governance` | MI | Governance limits |",

          "Index Tuning and Performance Scenarios": "### Index Tuning Approach\n1. Evaluate existing index usage (`sys.dm_db_index_operational_stats`, `sys.dm_db_index_usage_stats`)\n2. Eliminate unused indexes\n3. Craft indexes for the most expensive queries\n4. Test in non-production environment\n5. Implement via change control\n\n### Running vs Waiting Diagnosis\n- **High CPU** → running: check `sys.dm_exec_requests`, Query Store top consumers\n- **Waiting** → resources: check wait stats, `sys.dm_os_waiting_tasks`",

          "Exam Gotchas": "- `sys.dm_db_resource_stats` snapshots every **15 seconds** (SQL DB **only**)\n- `sys.server_resource_stats` for **MI**\n- `CXPACKET` = parallelism configuration issue\n- `PAGEIOLATCH_UP` on 2:1:1 = TempDB **PFS contention** — add more TempDB files\n- Query Store hints do **not require** app code changes\n- Wait stats accumulate from **instance startup** (not a rolling window)\n- `HADR_SYNC_COMMIT` is **normal** for Business Critical tier\n- Log governance: `LOG_RATE_GOVERNOR` (SQL DB), `POOL_LOG_RATE_GOVERNOR` (elastic pool), `INSTANCE_LOG_GOVERNOR` (MI)"
        }
      }
    },
    "Module 5": {
      "topics": {
        "Automate Database Deployment": {
          "What It Is": "Azure offers **declarative** (ARM templates/Bicep — specify what to create, Azure determines order and dependencies) and **imperative** (PowerShell/Azure CLI — specify a sequence of commands) deployment models. ARM templates are idempotent JSON documents. Bicep is a concise DSL that transpiles to ARM JSON (~60% less verbose).",

          "ARM Templates and Bicep": "### ARM Templates (JSON)\n- Declarative and **idempotent** (deploy repeatedly with the same result)\n- Deploy to: Resource Group, Subscription, Management Group, or Tenant\n- PowerShell: `New-AzResourceGroupDeployment -TemplateUri`\n- CLI: `az deployment group create --template-file`\n- Remote linked templates need a **SAS token in the query-string** for relative paths\n\n### Bicep\n- ~**60% less verbose** than equivalent ARM JSON\n- Declarative DSL; **not** a general-purpose language\n- Transpiles to ARM JSON; deploy: `New-AzResourceGroupDeployment -TemplateFile ./main.bicep`\n- Azure CLI **cannot** deploy remote Bicep files directly — must transpile to JSON first\n- Keywords: `param`, `var`, `resource`; use `parent:` for nested resources",

          "PowerShell and Azure CLI": "| Task | PowerShell | Azure CLI |\n|---|---|---|\n| Login | `Connect-AzAccount` | `az login` |\n| List subscriptions | `Get-AzSubscription` | `az account list` |\n| Create SQL server | `New-AzSqlServer` | `az sql server create` |\n| Create SQL database | `New-AzSqlDatabase` | `az sql db create` |\n| Create firewall rule | `New-AzSqlServerFirewallRule` | `az sql server firewall-rule create` |\n| Create SQL MI | `New-AzSqlInstance` | `az sql mi create` |\n\n`New-AzSqlInstance` **requires** `-SubnetId` (MI is deployed in a dedicated VNet subnet).",

          "CI/CD and Governance": "### Azure Pipelines\n- Deploy ARM templates via PowerShell tasks or dedicated ARM deployment tasks\n- CI = frequent code commits, automated build/test\n- CD = automated delivery to infrastructure\n\n### Azure Policy\n- Enforce governance: region limits, naming standards, allowed resource sizes\n- Applied at Management Group / Subscription / Resource Group\n- Grouped into **initiatives**\n\n### Resource Tags\n- Key-value pairs, up to **15 per resource**\n- Include in billing reports for cost tracking\n- Stored as **plain text** — never store sensitive values",

          "Exam Gotchas": "- ARM templates are **idempotent**\n- Bicep is ~**60% less verbose** than JSON\n- Azure CLI **cannot** deploy remote Bicep files directly\n- `New-AzSqlInstance` **requires** `-SubnetId`\n- Tags stored as **plain text** — no secrets\n- Azure Policy can **block deployment** if resources don't comply\n- Bicep **transpiles** to ARM JSON; it is not a general-purpose language"
        },

        "Create and Manage SQL Agent Jobs": {
          "What It Is": "SQL Server Agent schedules maintenance tasks like backups, integrity checks, index maintenance, and statistics updates. Maintenance Plans (SSIS packages) create multi-step workflows. Operators, notifications, and alerts enable proactive monitoring via Database Mail.",

          "Maintenance Plan Activities": "| Task | Notes |\n|---|---|\n| Check DB Integrity | `DBCC CHECKDB` — the **only** way to check full database corruption |\n| Shrink Database | **NOT recommended** — causes significant fragmentation |\n| Reorganize Index | Online; leaf-level defrag; 5–30% fragmentation |\n| Rebuild Index | Drops/recreates; > 30% fragmentation; **updates statistics** |\n| Update Statistics | Default sampling sufficient for most cases |\n| Backup Database | Full + Differential + Transaction Log |\n| Cleanup History | Removes old history records from msdb |\n| Maintenance Cleanup | Removes old backup files from specified folders (**not subfolders**) |\n\n**Restore order**: Full → most recent Differential → Transaction Logs since that Differential\n\n**Best practice**: Backup retention window > consistency check window.",

          "Operators, Notifications, and Alerts": "### Operators\n- Aliases for individuals or groups\n- Best practice: use **email distribution groups** (not individual addresses)\n\n### Notifications\n- Per-job: completion, success, or failure\n- Best practice: **notify only on failure**\n\n### Alerts\n| Alert Type | Based On |\n|---|---|\n| Error log | Error severity ≥ 16 |\n| Performance condition | CPU > 90%, etc. |\n| WMI event | Custom WMI query |\n\nResponse: **notify an operator** OR **execute another job** (or both). Requires **Database Mail** to be enabled.",

          "Proxy Accounts and Multiserver": "- **Proxy accounts**: Stored credentials for specific job steps (e.g., backup to a network share)\n- **Job schedules**: Jobs ↔ Schedules = **many-to-many** relationship; stored in **msdb**\n- **Multiserver jobs**: Primary server distributes jobs to target servers; define once, deploy everywhere",

          "Exam Gotchas": "- Shrink DB **NOT recommended** — causes fragmentation\n- Consistency check window must be **within backup retention window**\n- Proxy accounts = credentials for **specific job steps** (not jobs)\n- Jobs ↔ Schedules are **many-to-many** (stored in msdb)\n- Alerts can notify an operator **OR** execute another job\n- Operators: use **email distribution groups**\n- Maintenance Plans = **SSIS packages**\n- `DBCC CHECKDB` is the **only** way to check an entire database for corruption"
        },

        "Manage Azure PaaS Tasks Using Automation": {
          "What It Is": "Azure SQL Database does not have SQL Agent, so alternatives are needed: **Elastic Jobs** (T-SQL scheduler for SQL DB), **Azure Automation** (PowerShell/Python runbooks), and **Logic Apps** (low-code workflows with connectors). Each has different capabilities and use cases.",

          "Elastic Jobs (Azure SQL DB)": "T-SQL execution across multiple databases — the SQL Agent replacement for Azure SQL DB.\n\n### Components\n- **Job Agent**: The runtime resource\n- **Job Database**: Stores job metadata (**S1+ tier recommended**)\n- **Target Group**: Defines which servers/pools/databases to target\n- **Job Steps**: T-SQL commands to execute\n\n### Key Behaviours\n- Need a credential in **master** for server/elastic pool targets\n- Scripts must be **idempotent** — auto-retry on failure\n- Cross-subscription and cross-region targeting supported\n\n### Monitoring\n- Portal, PowerShell (`Get-AzSqlElasticJobExecution`)\n- T-SQL: `jobs.job_executions`",

          "Azure Automation": "**Runbooks**: PowerShell or Python. Import `Az.Sql` and `Az.Accounts` modules.\n\n- Use **system-assigned managed identity** (`Connect-AzAccount -Identity`) with RBAC permissions\n- Runbooks **restart from the beginning** if interrupted\n\n### Hybrid Runbooks\n- Manage on-premises or Azure VMs from the cloud\n\n### Monitoring\n- **Activity Log**: `Get-AzLog`, filter by `Microsoft.Automation/automationAccounts/jobs/write`\n- **Metric alerts** with action groups (email, webhook, runbook)\n- **Log Analytics**: Requires **Diagnostic settings** to be configured first",

          "Logic Apps": "Prebuilt connectors for integration with SQL Server, Office 365, and more.\n\n| Connector Type | Notes |\n|---|---|\n| Standard SQL connector | SQL Server, Azure SQL DB, Azure SQL MI |\n| Built-in connector (Standard plan) | No triggers; Execute Query action only |\n\n- **Triggers** return **only 1 row**\n- **Actions**: Get row, Insert, Delete, Execute Query, Run stored procedure",

          "Exam Gotchas": "- Elastic Jobs = **T-SQL only**; auto-retry on failure\n- Job DB recommended at **S1 or higher**\n- Target server credentials needed **in master**\n- Runbooks **restart from the beginning** if interrupted\n- Must import `Az.SQL` module for SQL cmdlets in Automation\n- System identity needs **RBAC permissions**\n- Log Analytics for Automation needs **Diagnostic settings** configured\n- Logic Apps triggers return **only 1 row**\n- Built-in connector has **no triggers**"
        }
      }
    },
    "Module 6": {
      "topics": {
        "HADR Strategies & Options": {
          "What It Is": "High Availability and Disaster Recovery (HADR) planning starts with defining **RTO** (max time to restore service) and **RPO** (max acceptable data loss). IaaS uses SQL-native features (FCI, AG, Log Shipping). PaaS has built-in HA (99.99% SLA, ADR) plus geo-replication and auto-failover groups.",

          "RTO, RPO, and HADR Options": "### Definitions\n- **RTO** (Recovery Time Objective): Maximum time available to bring resources online after an outage\n- **RPO** (Recovery Point Objective): Maximum acceptable data loss, measured in time\n\nOverall RTO = slowest component in the chain.\n\n### IaaS HADR Features\n| Feature | Level | Shared Storage | Notes |\n|---|---|---|---|\n| **Always On FCI** | Instance | ✅ Required | Full stop/start on failover; no data loss |\n| **Always On AG** | Database group | ❌ No | Up to 9 replicas; sync or async; readable secondaries |\n| **Log Shipping** | Database | ❌ No | Simplest; backup/copy/restore workflow |\n\n### Azure Platform Features\n| Feature | SLA | Notes |\n|---|---|---|\n| Availability Sets | 99.95% | Anti-affinity within same datacenter |\n| Availability Zones | 99.99% | Separate datacenters in same region |\n| Azure Site Recovery | ~2h RTO | VM-level replication; **not SQL-aware** |",

          "PaaS HADR": "### Built-In HA\n- **99.99% SLA** on Business Critical and Hyperscale\n- **Accelerated Database Recovery (ADR)** — on by default; **cannot be disabled**\n- Auto page repair; DB state cannot be `OFFLINE` or `EMERGENCY`\n\n### Active Geo-Replication (SQL DB Only)\n- Async readable secondary in same or different region\n- Manual failover only; same service tier required\n- Cross-subscription available programmatically\n\n### Auto-Failover Groups (SQL DB & MI)\n- Provides **read-write** and **read-only** listener endpoints\n- Automatic failover (configurable) — `GracePeriodWithDataLossHours` defaults to **1 hour**\n- **MI**: Only one failover group per instance",

          "Hybrid Solutions": "- AG secondary replica in Azure (IaaS-based)\n- Requires Active Directory DS + DNS + sufficient network bandwidth\n- Connect via **ExpressRoute** or **Site-to-Site VPN**\n- Transactional replication: on-premises publisher → MI subscriber",

          "Exam Gotchas": "- **FCI** = instance-level, no data loss, but **full stop/start** on failover\n- **AG** = database-level, no shared storage needed\n- Availability Sets and Availability Zones **cannot be combined**\n- Azure Site Recovery is **not SQL-aware** — may miss RPO targets\n- **Active geo-replication = SQL Database only** (not MI)\n- MI = auto-failover groups only; **one per MI** instance\n- `GracePeriodWithDataLossHours` default = **1 hour**\n- DB state `OFFLINE`/`EMERGENCY` **not supported** in PaaS\n- **ADR cannot be disabled** in Azure SQL"
        },

        "Implement IaaS & PaaS HADR": {
          "What It Is": "Deploying WSFC in Azure requires PowerShell (not the wizard), a cloud witness, and an Internal Load Balancer (ILB) for AG listeners. Distributed AGs span regions without a shared WSFC. Azure Site Recovery provides VM-level DR. Monitoring uses Azure Status, Service Health, and DMVs.",

          "WSFC in Azure": "- WSFC wizard **cannot be used in Azure** — use PowerShell: `New-Cluster -StaticAddress`\n- **Cloud witness** recommended (Windows Server 2016+)\n- **Workgroup Cluster** (WS 2016+): AG only; no Active Directory required\n- **DNN** (Distributed Network Name) is the default in WS 2019+ for FCI — **no ILB needed** for FCI with DNN\n- IP addresses configured in Azure (not inside VM — shows as DHCP)\n- `Test-Cluster` validates; warnings are acceptable if expected",

          "AG Configuration": "- `Enable-SqlAlwaysOn` **requires SQL Server restart**\n- **ILB required** for AG listener connectivity (Standard LB for Availability Zones)\n- Each listener IP needs a unique **probe port** (e.g., port 59999)\n- Multi-subnet deployments: ILB per subnet/region\n\n### Distributed AG\n- **Enterprise Edition only**, SQL Server 2016+\n- AG of AGs (Global Primary + Forwarder)\n- No WSFC connection between the two AGs\n- Each AG maintains its **own quorum**",

          "Azure Site Recovery Details": "- **Mobility extension** installed on each VM\n- **Crash-consistent**: snapshot every 5 minutes\n- **App-consistent**: configurable (VSS-based)\n- Multi-VM consistency is configurable but **affects performance**\n- **Test failover**: Validate recovery without impacting production\n- After failover, replica VMs are **unprotected** — must reprotect manually\n- Can be used to protect against **ransomware**",

          "Monitoring Availability": "| Tool | Use Case |\n|---|---|\n| Azure Status Dashboard | Global Azure outages; RSS feed available |\n| Azure Service Health | Planned maintenance, advisories, personalized alerts |\n| Resource Health | View why a specific resource is unavailable |\n| `sys.dm_database_replica_states` | Business Critical replica health |\n| `az sql mi/db list` / `Get-AzSQLDatabase` | Programmatic status checks |",

          "Exam Gotchas": "- WSFC wizard **cannot** be used in Azure — use PowerShell\n- **DNN** default in WS 2019+ for FCI — no ILB needed\n- **ILB required** for AG listener\n- Probe port must be **unique per listener**\n- Distributed AG = **Enterprise only**, AG of AGs\n- ASR requires **mobility extension** on VMs\n- Crash-consistent every **5 minutes**\n- Replicas are **unprotected after ASR failover** — must reprotect\n- Cluster validation warnings are acceptable if expected"
        },

        "Back Up and Restore Databases": {
          "What It Is": "SQL Server backup types: Full, Differential, Transaction Log. Recovery models: FULL, BULK_LOGGED, SIMPLE. Backup to URL uses Azure Blob Storage. PaaS backups are fully automated. MI supports COPY_ONLY backup to URL. ADR speeds recovery significantly.",

          "Backup Types and Recovery Models": "### Backup Types\n| Type | Description |\n|---|---|\n| **Full** | All allocated pages |\n| **Differential** | Pages changed since last full |\n| **Transaction Log** | Granular PITR; **clears the log**; requires FULL recovery model |\n| **COPY_ONLY** | Does **not** break the log chain |\n\n### Recovery Models\n| Model | Log Backups | PITR |\n|---|---|---|\n| **FULL** | ✅ Required | ✅ Yes |\n| **BULK_LOGGED** | ✅ Required | ⚠️ Partial |\n| **SIMPLE** | ❌ Not allowed | ❌ No |\n\n### Restore Order\n```\nFull backup\n  → Most recent Differential\n  → Transaction Logs since that Differential (each with NORECOVERY, last with RECOVERY)\n```",

          "Backup to URL (IaaS)": "- Requires Azure Storage account + container\n- URL format: `https://ACCOUNTNAME.blob.core.windows.net/ContainerName/File.bak`\n\n### Authentication\n| Method | Notes |\n|---|---|\n| **SAS token** (block blob) | Preferred from SQL Server 2016+; cheaper, better security |\n| **Access key** (page blob) | Legacy method |\n\n### Automated Backups via IaaS Agent Extension\n- **Windows VMs only**\n- Do **NOT** combine with instance-level transaction log backups (breaks the log chain)\n\n### Azure Backup\n- SQL-aware VSS backups; works alongside native SQL Server backups",

          "PaaS Backup and Restore": "### Automatic Backup Schedule\n- **Full**: Weekly\n- **Differential**: Every 12 hours\n- **Log**: Every 5–10 minutes\n- Geo-redundant **RA-GRS** blobs\n\n### Retention\n- Default: **7 days** | Maximum: **35 days** | LTR: up to **10 years**\n\n### Restore Rules\n- Creates a **new database** — cannot restore over an existing DB\n- Deleted databases can be restored to the last available point\n- ⚠️ **Server deletion = all backups are permanently deleted**\n\n### MI-Specific\n- COPY_ONLY backup to URL (SQL Database does **not** support)\n- T-SQL RESTORE from URL\n- Cannot restore MI backups to SQL Database",

          "Accelerated Database Recovery (ADR)": "- Enabled by default in Azure SQL — **cannot be disabled**\n- Uses **Persisted Version Store (PVS)** and aggressive log truncation\n- Enables **instant transaction rollback** regardless of transaction size\n- Also available in SQL Server 2019+",

          "Exam Gotchas": "- PaaS restore = **new database** — cannot overwrite existing\n- **Server deletion = backups permanently gone** — no recovery\n- COPY_ONLY backup = **MI only**\n- ADR is on by default and **cannot be disabled**\n- Block blob only from SQL Server 2016+\n- Automated backups (IaaS Agent Extension) are **Windows-only**\n- Do **NOT** combine IaaS automated backups with instance-level log backups\n- `SIMPLE` recovery = **no log backups, no PITR**\n- Default backup retention: **7 days** | Max: **35 days** | LTR: **10 years**"
        }
      }
    }
  }
};
