var DP600_DATA = {
  "title": "Designing and Implementing Analytics Solutions Using Microsoft Fabric",
  "modules": {
    "Module 1": {
      "topics": {
        "Microsoft Fabric & OneLake": {
          "What It Is": "Microsoft Fabric is an end-to-end, unified SaaS analytics platform that provides a single, integrated environment where data professionals and business users can collaborate on data projects. It is built on a unified data lake called OneLake, which ensures that all data is stored in a single open format and is accessible to all compute engines within the platform without the need for data movement.",
          "Fabric Workloads": "Microsoft Fabric offers a diverse range of integrated workloads to support the entire data lifecycle.\n\nData Engineering uses lakehouses and Spark for large-scale processing, while Data Factory provides pipelines and dataflows for orchestration and ingestion. The Data Warehouse workload provides enterprise-scale relational capabilities with full T-SQL support, and Real-Time Intelligence enables the ingestion and analysis of streaming data. Additionally, Data Science workloads leverage notebooks and machine learning, while Power BI provides the consumption layer for reporting and analytics.",
          "Administration and Governance": "Fabric administration is centralized through the Admin portal, where administrators can manage groups, permissions, data sources, gateways, and monitor usage and performance.\n\nGovernance is enhanced through the use of domains to group workspaces by business area and the OneLake catalog to help users discover and manage data assets. Integration with Microsoft Purview allows for advanced data classification, sensitivity labeling, and lineage tracking across the entire tenant.",
          "OneLake and Shortcuts": "OneLake serves as the centralized, tenant-wide storage layer for Microsoft Fabric, acting as a single logical lake that eliminates data silos. It is built on Azure Data Lake Storage Gen2 and stores data in open formats like Delta-Parquet, ensuring that all compute engines can access the same data without duplication.\n\nOneLake supports shortcuts, which allow users to reference data in external or internal locations—such as Amazon S3 or other OneLake locations—without physically copying it, maintaining data consistency and reducing storage costs.",
          "Discovery and Streaming": "The OneLake catalog provides a searchable inventory of all data assets across the tenant, allowing users to browse by workspace or domain and view metadata like ownership, refresh status, and endorsement status.\n\nFor streaming data, the Real-Time hub serves as a centralized catalog for discovering and managing eventstreams and KQL tables. This hub enables users to connect to diverse streaming sources and build real-time analytics solutions that respond to events as they happen.",
          "AI Capabilities": "Microsoft Fabric is designed to be AI-ready, providing powerful tools like Copilot to assist users with code generation, data transformation, and report creation.\n\nAdvanced intelligence is provided through Fabric IQ, which includes Fabric IQ for business ontologies, Foundry IQ for enterprise knowledge, and Work IQ for collaboration signals.\n\nFurthermore, Fabric data agents allow users to interact with their data through conversational interfaces, using natural language to query lakehouses, warehouses, and semantic models.",
          "Exam Gotchas": "OneLake provides a single source of truth that is accessible to all Fabric engines, eliminating the need for data duplication. Shortcuts provide access to data without duplicating it, but they are not suitable for point-in-time snapshots or when compliance requires physical separation.\n\nWorkspace roles apply to all items in a workspace, while item permissions allow for more granular, per-item access control.\n\nThe OneLake Catalog is for batch and stored data, whereas the Real-Time Hub is for streaming and in-motion data.\n\nUsing Copilot requires a Fabric capacity of F2 or higher, and Trial SKUs do not support Copilot in all scenarios."
        },
        "Lakehouse": {
          "What It Is": "A Lakehouse in Microsoft Fabric combines the flexibility and scalability of a data lake with the analytical power and ACID transaction support of a data warehouse. By using the Delta Lake format in OneLake, it allows for the storage of structured, semi-structured, and unstructured data in a single, unified location.",
          "Storage Areas": "A lakehouse is organized into two primary areas: the Tables area and the Files area.\n\nThe Tables area contains managed Delta Lake tables that provide schema enforcement, ACID transactions, and direct SQL accessibility.\n\nThe Files area is used for storing raw or semi-structured data in its native format, such as CSV, JSON, or Parquet, providing maximum flexibility for data exploration and staging.",
          "Access and Querying": "Users can interact with a lakehouse through several different modes depending on their requirements.\n\nThe Lakehouse explorer provides a management interface for files and tables, while the SQL analytics endpoint offers read-only T-SQL access to Delta tables for analysts. Data engineers and scientists typically use Spark notebooks to perform read/write operations using PySpark, Spark SQL, or Scala.\n\nFor high-performance reporting, Power BI uses Direct Lake mode to read Delta files directly from OneLake.",
          "Ingestion and Transformation": "Data can be brought into a lakehouse through various methods, including direct uploads, the Load to Table feature for Parquet and CSV files, and automated pipelines.\n\nMore complex ETL processes can be handled using Dataflows Gen2 for a low-code experience or Spark notebooks for programmatic, large-scale transformations. Shortcuts also allow users to integrate external data into their lakehouse without the need for physical movement.",
          "Schemas and Security": "Lakehouses support schemas, with a `dbo` schema being created by default, allowing for better organization of tables.\n\nSecurity is managed through a combination of workspace roles, item-level sharing, and granular security controls like RLS and CLS on the SQL analytics endpoint.",
          "Exam Gotchas": "Tables are Delta-formatted, SQL-queryable, and schema-enforced, whereas Files are raw and do not support direct SQL access. The SQL endpoint is strictly read-only; you cannot perform DML (INSERT, UPDATE, DELETE) operations through it. The Load to Table feature is specifically designed to support Parquet and CSV files. If resource thresholds are exceeded or unsupported operations are used, Power BI can fall back from Direct Lake to DirectQuery mode. Cross-Workspace Queries require the use of the four-part naming convention (`workspace.lakehouse.schema.table`)."
        },
        "Data Warehouse": {
          "What It Is": "A Fabric Data Warehouse is a fully managed, enterprise-scale relational database that provides full T-SQL capabilities, including both DDL and DML support. It is designed to handle structured analytical workloads with multi-table ACID compliance while storing all data in the open Delta format on OneLake.",
          "Capabilities and Tooling": "The warehouse supports a wide array of T-SQL operations, such as `CREATE`, `ALTER`, `INSERT`, `UPDATE`, `DELETE`, and `MERGE`, making it ideal for transactional ETL.\n\nUsers can interact with the warehouse using the web-based SQL query editor, the Visual Query Editor for a no-code experience, or external tools like SSMS and Azure Data Studio.",
          "Dimensional Modeling": "The warehouse is optimized for dimensional modeling, using star schemas to organize data into fact and dimension tables. This structure enables efficient querying and provides a robust foundation for Power BI semantic models.\n\nModeling includes the use of surrogate keys to insulate the warehouse from source system changes and the implementation of slowly changing dimensions (SCD) to track historical attribute changes.",
          "Ingestion and Querying": "Data can be ingested into the warehouse using the `COPY INTO` command for bulk loading from files, `OPENROWSET` for querying external files, or through Data Factory pipelines and Dataflows.\n\nOnce loaded, data can be queried using T-SQL or joined with data in other warehouses and lakehouses through cross-database queries using three-part naming.",
          "Security and Monitoring": "Security is managed through workspace roles, item permissions, and granular SQL security features like row-level security (RLS), column-level security (CLS), and dynamic data masking.\n\nPerformance and usage are monitored through Query Insights, which provides 30-day historical data, and Dynamic Management Views (DMVs) for real-time tracking.",
          "Exam Gotchas": "The Warehouse provides full read/write T-SQL capabilities, whereas the Lakehouse SQL endpoint is read-only. Fabric does not enforce referential integrity via FK constraints at the engine level; this must be managed in the ETL logic. Table Clones are zero-copy operations that only consume additional storage for changed data. Query Insights retains historical query data for 30 days. Only Workspace Admins have the authority to terminate active sessions with the KILL command. Cross-Database Queries use three-part naming (`database.schema.table`) to join data across warehouses and lakehouses within the same workspace."
        },
        "Real-Time Intelligence": {
          "What It Is": "Real-Time Intelligence is an integrated suite of Fabric components designed to ingest, process, store, and act on streaming data with minimal latency. It enables organizations to move from batch-based historical analysis to real-time, event-driven decision making.",
          "Core Components": "The suite includes Eventstreams for capturing and transforming data in motion, and Eventhouses for high-performance, time-series storage using KQL databases.\n\nKQL Querysets provide a dedicated workspace for running and managing KQL queries, while Real-Time Dashboards offer automatically refreshing visualizations.\n\nFor automated responses, Activator monitors data against predefined rules and triggers actions like notifications or workflows.",
          "Ingestion and Transformation": "Data can be ingested into the Real-Time Intelligence ecosystem via Eventstreams, which can filter, aggregate, and route data to various destinations. Alternatively, data can be directly ingested into KQL databases within an Eventhouse.\n\nTransformations can occur in-motion via Eventstream processing or after landing via KQL update policies.",
          "KQL and Analytics": "Kusto Query Language (KQL) is the primary engine for analysis, optimized for high-volume, time-series data. KQL supports a pipeline-based syntax that allows for efficient filtering, aggregation, and pattern matching.\n\nReal-Time Dashboards and Power BI provide the visualization layer, allowing users to monitor both current trends and historical patterns.",
          "Exam Gotchas": "Eventstream transformations happen *during* stream processing (in-motion), while update policies happen *after* data lands in a KQL database. The Real-Time Hub is for streaming and event data, whereas the OneLake Catalog is for batch and stored data. Power BI connects to Eventhouses via DirectQuery, not Direct Lake. Eventhouses are optimized for append-only streaming and are not intended for frequent UPDATE or DELETE operations. KQL is strictly case-sensitive for all identifiers, including table names, column names, and operators. In KQL, you should place the smaller table first in a join to optimize performance."
        }
      }
    },
    "Module 2": {
      "topics": {
        "Analytical Data Store Options": {
          "What It Is": "Microsoft Fabric provides three primary analytical data stores: the Lakehouse, the Warehouse, and the Eventhouse. While all three are built on the OneLake foundation and support open formats like Delta and Parquet, they are optimized for different data patterns, query languages, and workload requirements.",
          "Comparing the Stores": "Lakehouse: This is the most versatile option, designed for flexible analytics and data engineering. It supports structured, semi-structured, and unstructured data. The primary development tool is Apache Spark (Python, Scala, SQL, R), and it supports batch ingestion via Spark notebooks, pipelines, and dataflows. It provides a dual-access model: read/write access via Spark and read-only T-SQL access through the SQL analytics endpoint.\n\nWarehouse: This is optimized for structured analytics and enterprise BI reporting. It provides full transactional T-SQL capabilities, including complete DDL and DML support (such as `MERGE`). The primary development tool is T-SQL, and it is the preferred choice for SQL-first teams building star schemas and dimensional models.\n\nEventhouse: This is purpose-built for real-time analytics on streaming and time-series data. It handles high-volume, append-heavy workloads with minimal latency. The primary development tool is Kusto Query Language (KQL), and it is ideal for monitoring telemetry, logs, and IoT sensor data.",
          "Decision Framework": "When choosing a data store, consider several key factors. The **data format** (structured vs. unstructured) and **write pattern** (transactional vs. streaming) are critical. **Query language preference** (T-SQL vs. Spark vs. KQL) and the **team's existing skill set** also play a major role. Finally, the **workload type**—whether it is batch analytics, exploratory data science, or real-time monitoring—will ultimately determine the best fit.",
          "AI Readiness": "Each store supports different AI scenarios.\n\nThe Lakehouse is the natural home for machine learning training and feature stores, especially when using Spark.\n\nThe Warehouse provides the structured, governed data that Copilot and data agents rely on for answering natural language questions.\n\nThe Eventhouse enables real-time AI scoring and anomaly detection on live, streaming event data.",
          "Exam Gotchas": "All three stores write to OneLake, meaning data can be accessed across workloads via shortcuts or cross-database queries without duplication. The SQL analytics endpoint on a lakehouse is strictly read-only for T-SQL users. Only the Warehouse provides full multi-table ACID transaction support through T-SQL. The Eventhouse is optimized for append-only streaming and is not intended for frequent `UPDATE` or `DELETE` operations. Many real-world solutions use multiple stores together (e.g., a Lakehouse for staging and a Warehouse for curated BI)."
        },
        "Dimensional Modeling": {
          "What It Is": "Dimensional modeling organizes analytical data into fact tables (numeric measures of business events) and dimension tables (descriptive attributes providing context). This separation makes data intuitive for analysts and optimized for query engines. In Fabric, dimensional models can be implemented in both warehouses and lakehouses.",
          "Schema Types": "Star Schema: Central fact table with dimension tables radiating outward. Fewer joins, faster queries, recommended for most analytics and Power BI semantic models. Denormalized dimensions add minor storage redundancy but vastly simplify queries.\n\nSnowflake Schema: Normalized dimensions split into related sub-tables (e.g., product to subcategory to category). Use when dimensions are extremely large or need hierarchies at different grains. More joins = more complex queries.",
          "Fact Table Design": "Define the grain first what one row represents (e.g., one row per sales order line).\n\nThree types: Transaction (one row per event), Periodic Snapshot (regular interval summary), Accumulating Snapshot (tracks process milestones).\n\nMeasures: Additive (summable across all dimensions), Semi-additive (not across time), Non-additive (store underlying values instead). Factless fact tables capture occurrences without numeric measures (e.g., attendance).",
          "Dimension Table Design": "Use surrogate keys (autogenerated integers) instead of natural keys to insulate from source changes and support SCD tracking. Denormalize dimension attributes for performance.\n\nConformed dimensions are shared across multiple fact tables (e.g., a single date dimension). Role-playing dimensions reference the same physical table multiple times in one fact table (e.g., Order Date, Ship Date, Delivery Date). Junk dimensions consolidate many small, low-cardinality attributes into one table.",
          "Slowly Changing Dimensions": "Type 0: Retain original (never change). Type 1: Overwrite (no history). Type 2: Add new row with start/end dates and current flag (full history, most common). Type 3: Add new column (current vs. previous only). Type 6: Hybrid of Types 1, 2, and 3.",
          "Exam Gotchas": "Always define the grain before picking dimensions and measures. Surrogate keys insulate from source system changes and enable SCD Type 2. Star is recommended over snowflake for most Fabric workloads. Fabric warehouses don't enforce foreign key constraints use naming conventions and loading logic instead."
        },
        "Dataflows Gen2": {
          "What It Is": "Dataflows Gen2 provide a Power Query-based, low-code ETL experience in Microsoft Fabric. Transformations are built visually in the Power Query Online editor, recorded as applied steps, and run on managed Fabric compute. Ideal for teams comfortable with Power Query in Excel or Power BI Desktop.",
          "Key Capabilities": "Connects to 300+ data sources. 300+ visual transformations (filter, merge, pivot, group by). Loads to lakehouses (Delta tables), warehouses, SQL databases, ADLS Gen2, Azure Data Explorer, Snowflake, and more.\n\nUpdate methods: Replace (full snapshot), Append (incremental rows), Incremental refresh (time-windowed buckets).\n\nCopilot for Dataflow Gen2 generates transformations via natural language prompts.",
          "Performance Optimization": "Modern Query Evaluator enabled by default. Query folding pushes transformations to the data source for execution (check via View Native Query). Folding-friendly: filters, column selects, sorts, group bys, merges from same source. Folding breakers: custom M columns, pivots, merges across sources.\n\nFilter and select columns early. Use staging dataflows to separate extraction from transformation. Preview-only steps run during authoring but excluded from production refresh.",
          "M Language": "Every visual transformation generates M code. Direct M editing useful for custom functions, parameterized queries, error handling (try...otherwise), and advanced logic not supported visually.",
          "Exam Gotchas": "Know what breaks query folding (custom columns, pivots) and what doesn't (filters, selects, group bys).\n\nIncremental refresh supported for lakehouse, warehouse, and Azure SQL Database destinations only. A destination is optional a dataflow can run without one and be consumed by pipelines or Power BI directly.\n\nDataflows for simple-to-moderate transformations notebooks for complex logic and large-scale Spark workloads."
        },
        "Notebooks": {
          "What It Is": "Fabric notebooks provide an interactive, code-based environment running on Apache Spark. Supports PySpark (Python), Spark SQL, Scala, and R. Cells execute independently, results appear inline ideal for iterative development and complex transformations.",
          "Data Shaping & Cleaning": "Core patterns (Spark SQL and PySpark): Remove duplicates via SELECT DISTINCT or ROW_NUMBER() OVER (PARTITION BY ...). Handle nulls with COALESCE or drop rows. Filter rows with WHERE. Select/rename columns for consistent naming. Add calculated columns (quantity * unit_price). Conditional columns with CASE WHEN. Convert data types with CAST.",
          "Combining & Aggregating": "Joins: INNER, LEFT, RIGHT, FULL OUTER, CROSS. Aggregations: GROUP BY with COUNT, SUM, AVG, HAVING.\n\nWindow functions: ROW_NUMBER, RANK, LAG, LEAD, running SUM keep all rows while computing across related rows. CTEs break complex queries into named steps. Pivot transforms rows to columns.",
          "Writing Delta Tables": "Write modes: CREATE OR REPLACE TABLE (overwrite) or INSERT INTO (append). Partitioning: use for tables >1 TB, target 1 GB per partition, common columns year/month/region. File sizing: target 128 MB to 1 GB per Parquet file.\n\nOptimize Write (default) consolidates small files. Run OPTIMIZE and VACUUM for maintenance.\n\nDelta features: ACID transactions, schema enforcement, V-Order (disabled by default).",
          "Exam Gotchas": "Pinning a default lakehouse sets the Hive metastore context tables are referenced by name without full paths. %%sql magic command switches to Spark SQL within PySpark. Optimize Write is on by default V-Order is off by default. Only partition tables >1 TB avoid high-cardinality partition columns."
        },
        "T-SQL Transformation": {
          "What It Is": "T-SQL in Fabric Warehouse provides full read-write capabilities SELECT, INSERT, UPDATE, DELETE, MERGE, CREATE TABLE AS SELECT (CTAS). The lakehouse SQL analytics endpoint is read-only for T-SQL.",
          "Core Transformations": "Filter and shape with WHERE, CASE, COALESCE/ISNULL, CAST/CONVERT. Combine data with INNER JOIN, GROUP BY, HAVING. Window functions: ROW_NUMBER, RANK, LAG, LEAD, SUM() OVER for analytical calculations without collapsing rows. CTEs for step-by-step transformations.",
          "Views": "Reusable named SELECT statements that always reflect current source data. Benefits: reusability, abstraction (hide joins), security (restrict columns/rows). Use ALTER VIEW to modify. Organize into schemas (gold, reporting).\n\nViews vs. tables: views are always fresh with no storage cost tables are precomputed and faster for performance-critical dashboards.",
          "Stored Procedures": "Named blocks of T-SQL supporting write operations, parameters, multi-step logic, and TRY...CATCH error handling.\n\nLoading patterns: Full refresh (delete + reload), Incremental load (watermark column), Merge/Upsert (MERGE for insert + update in one operation).\n\nPipeline integration: Data Factory pipelines can call stored procedures on a schedule.",
          "Dimensional Table Implementation": "Create dimension tables with IDENTITY surrogate keys and SCD Type 2 columns (effective_date, end_date, is_current). Create fact tables with foreign keys to dimensions and numeric measures.\n\nLoad dimensions via INSERT...SELECT (initial) or MERGE (Type 1) or expire + insert (Type 2). Load facts by joining staging to dimension tables on surrogate keys.\n\nTable clones: CREATE TABLE ... AS CLONE OF for zero-copy dev/test.",
          "Exam Gotchas": "Lakehouse SQL endpoint is read-only only warehouses support write via T-SQL. No FK enforcement in Fabric warehouses maintain referential integrity through loading logic. CTAS is for one-time materialization stored procedures for recurring transformations. Table clones are zero-copy they share underlying data files until modified."
        }
      }
    },
    "Module 3": {
      "topics": {
        "DAX Calculations & Model Components": {
          "What It Is": "Semantic models are enhanced through three types of DAX (Data Analysis Expressions) calculations: **Calculated Tables**, **Calculated Columns**, and **Measures**. These allow for the creation of sophisticated logic, from adding new dimensions to performing complex, dynamic aggregations.",
          "Calculation Types": "Calculated Tables: These are created with DAX formulas that return a table object. They are useful for duplicating existing tables to handle multiple relationships (e.g., creating a 'Ship Date' table from a 'Date' table) or for generating specialized tables like date tables using `CALENDARAUTO`.\n\nCalculated Columns: These add a new column to an existing table, with the formula evaluated in **row context** during data refresh. While useful for adding attributes like 'Fiscal Year,' they increase model size and should be used sparingly in favor of Power Query or measures.\n\nMeasures: These are dynamic aggregations evaluated in **filter context** at query time. Measures do not store values in the model, making them highly efficient for large datasets. They are the primary tool for business metrics like 'Total Revenue' or 'Profit Margin.'\n\nIterator Functions: Functions like `SUMX`, `AVERAGEX`, and `RANKX` evaluate an expression row-by-row over a specified table. They are essential for complex calculations that require row-level logic before aggregation.",
          "Key Concepts": "Calculated columns operate in row context (the current row), while measures operate in filter context (the set of rows currently filtered by slicers or visuals).\n\nIn complex models, measures can use the `USERELATIONSHIP` function to activate inactive relationships, allowing a single dimension (like Date) to support multiple roles (like Order Date and Ship Date).",
          "Exam Gotchas": "Measures are more efficient than calculated columns because they do not consume storage and are computed only when needed. Use iterators when you need to perform a calculation on each row (e.g., `Quantity * UnitPrice`) before aggregating the result. Calculated Tables are useful for creating role-playing dimensions to solve multiple relationship challenges."
        },
        "Designing for Scale & Storage Modes": {
          "What It Is": "Designing for scale involves making strategic decisions about how data flows into the model and how it is structured to support growing volumes of data and increasing numbers of concurrent users.",
          "Storage Modes": "The choice of storage mode directly impacts query performance, data freshness, and feature availability: Direct Lake (Default), Import Mode, DirectQuery, and Composite Mode.",
          "Star Schema & Relationships": "A well-designed star schema is fundamental to performance.\n\nRelationships should connect dimension tables to fact tables using a one-to-many pattern, with filters flowing from the dimension to the fact. For complex models, designers must manage inactive relationships using `USERELATIONSHIP` and handle many-to-many scenarios using bridge tables.",
          "Scaling Settings": "To support large-scale environments, several advanced settings can be configured: Large Semantic Model Storage Format, XMLA Endpoint, Query Scaleout, and Direct Lake Fallback.",
          "Exam Gotchas": "In Fabric, start with Direct Lake and only move to other modes if specific requirements (like non-Fabric sources) necessitate it. Standard star schemas use single-direction filtering from dimension to fact to ensure predictable performance. In production, you may choose to 'Disallow Fallback' to enforce consistent performance, even if it means some queries return errors. Enabling OneLake Integration allows downstream Fabric items (like notebooks) to consume the semantic model data directly as Delta tables."
        },
        "Performance Optimization": {
          "What It Is": "Optimization involves diagnosing bottlenecks and applying targeted fixes to ensure reports and AI-powered experiences (Copilot, Agents) remain responsive.",
          "Diagnostic Tools": "Performance Analyzer, DAX Studio, and Best Practice Analyzer (BPA).",
          "Optimization Strategies": "DAX Tuning (using Variables, avoiding expensive FILTER), Reducing Cardinality, and implementing Aggregations.",
          "Troubleshooting Workflow": "Identify (Performance Analyzer) $\\rightarrow$ Isolate (DAX Studio) $\\rightarrow$ Fix & Verify.",
          "Exam Gotchas": "In Direct Lake, a large number of small files can degrade performance; use `OPTIMIZE` in Spark to compact them. High-cardinality columns (like GUIDs or high-precision timestamps) are major contributors to slow models and high memory usage.\n\nWhen correctly configured, the engine automatically uses aggregations, so users don't need to know they exist. Using `VAR` in DAX can often cut execution time in half by preventing the engine from recalculating the same expression multiple times."
        },
        "Semantic Model Security": {
          "What It Is": "Semantic model security controls which data users can see when they query a model. Implementing security ensures that data visibility is restricted to only authorized users, protecting sensitive information across all consumption paths.",
          "Row-Level Security (RLS)": "RLS restricts *which rows* are visible based on DAX filter expressions. Includes Static RLS, Dynamic RLS (using `USERPRINCIPALNAME()`), and the Security Table Pattern.",
          "Object-Level Security (OLS)": "OLS restricts access to *specific tables or columns*. When an object is secured with OLS, it and its metadata are completely hidden from unauthorized users. Must be implemented using external tools like Tabular Editor.",
          "Testing and Management": "Use the **View as** feature for testing. Manage role membership in the Power BI service, preferably by mapping roles to Microsoft Entra security groups. Properly configured RLS and OLS ensure that Copilot and Fabric data agents only access and surface authorized data.",
          "Exam Gotchas": "If a user is assigned to multiple roles, they see the **union** of all rows permitted by those roles. Workspace roles (Admin, Member, Contributor) bypass RLS entirely. Only users with Viewer permissions are subject to RLS.\n\nWhen an object is secured with OLS, it is completely invisible to unauthorized users, including its metadata. When implementing RLS, ensure that relationship chains are not broken, as this can cause unintended data visibility."
        },
        "Development Lifecycle Management": {
          "What It Is": "Lifecycle management (LCM) provides a structured process—**Develop $\\rightarrow$ Validate $\\rightarrow$ Deploy $\\rightarrow$ Monitor**—to manage semantic models from creation to production.",
          "Develop": "Use Reusable Assets (Shared Semantic Models, Power BI Templates) and Version Control (Power BI Desktop Projects/TMDL for Git integration).",
          "Validate": "Use Programmatic Validation (XMLA endpoint and SemPy in Fabric notebooks) and External Tools (Tabular Editor, DAX Studio).",
          "Deploy": "Use Deployment Pipelines (Dev $\\rightarrow$ Test $\\rightarrow$ Prod) and Deployment Rules (to adjust configurations automatically).",
          "Monitor": "Use Scheduled Refresh and the Fabric Monitoring Hub.",
          "Exam Gotchas": "Git is for tracking *what* changed and facilitating collaboration, while Deployment Pipelines are for managing *where* content is deployed across environments.\n\nSemPy allows for automated, repeatable validation in notebooks, which is more scalable than manual checks.\n\nAlways configure deployment rules *before* the first deployment to ensure environments are correctly configured upon promotion."
        }
      }
    },
    "Module 4": {
      "topics": {
        "AI-Ready Semantic Layer": {
          "What It Is": "Preparing a semantic model for AI consumption involves grounding AI tools like Copilot and data agents with clear naming, thorough documentation, and linguistic modeling so that Retrieval-Augmented Generation (RAG) produces accurate natural-language answers.",
          "Key Details": "Grounding: The process of providing AI with contextual information (table names, column names, relationships, descriptions, linguistic schema) to improve response accuracy. This involves the RAG (Retrieval-Augmented Generation) process.\n\nLinguistic Modeling: Configured via Q&A Setup. Includes **Synonyms** (e.g., 'Revenue' maps to 'Sales') and **Linguistic Relationships** (e.g., 'Customers purchase Products').\n\nPrep for AI Features: Includes AI Data Schema (controls visibility), AI Instructions (business rules/terminology), and Verified Answers (predefined visual responses).\n\nApproved for Copilot: A setting in the Power BI service that removes friction-treatment banners from Copilot answers.",
          "Architectural Logic": "AI tools lack inherent business knowledge; they rely entirely on the grounding data retrieved during the RAG process. The semantic model serves as the critical interface between data engineering (upstream) and AI consumption (downstream). High-quality grounding (clear names, rich descriptions, and linguistic modeling) directly improves the quality of AI-generated answers.",
          "Exam Gotchas": "Grounding is per-model context (descriptions, synonyms); Ontology is organization-wide shared business vocabulary (Fabric IQ). Descriptions are truncated at 200 characters for grounding—put the most important context first.\n\nCopilot may aggregate a column without an explicit measure, potentially mismatching business logic. Always use explicit measures for key metrics.\n\nHiding a field in the model removes it from AI consideration entirely (both columns and tables). Verified answers are predefined visual responses that bypass AI generation to ensure consistency for common questions.\n\nChanges persist on the semantic model and sync via Git/pipelines, but require a model refresh in the service after deployment."
        },
        "Fabric IQ (Ontology)": {
          "What It Is": "Fabric IQ is a workload that creates **ontologies**—organization-wide, machine-understandable vocabularies of business concepts (entities, properties, relationships) bound to OneLake data (lakehouse tables or eventhouse streams).",
          "Key Details": "Build-Bind-Query Workflow: 1. **Build** (Define entity types, properties, and relationship types); 2. **Bind** (Map ontology definitions to OneLake sources); 3. **Query** (Use Graph (GQL), Query Builder, or Data Agents).\n\nEntity Type Components: Includes Name, Properties (Attributes: Static or Time Series), and a Key (required before binding).\n\nRelationship Types: Directional connections between two different entity types.\n\nData Binding Types: Static Bindings (lakehouse tables for static data) and Time Series Bindings (eventhouse tables for streaming, timestamped observations).\n\nCreation Paths: Generate from Semantic Model (using Direct Lake model) or Build from OneLake (manual creation).\n\nData Agents: Conversational Q&A powered by Azure OpenAI. Can use up to five data sources (lakehouses, warehouses, KQL databases, semantic models, or ontologies).\n\nGraph in Microsoft Fabric: Native graph storage using a labeled property graph model (nodes and edges), queried via GQL.",
          "Architectural Logic": "Fabric IQ separates business meaning from physical data structures. The ontology defines *what* a 'Patient' is, while bindings map that concept to *where* the data lives in OneLake. This enables federated queries across lakehouse (static) and eventhouse (time-series) data using a consistent business vocabulary.",
          "Exam Gotchas": "Full automated generation (including data bindings) is only supported when using a Direct Lake semantic model with inbound public access. In dual-binding scenarios, static bindings must be configured before time-series bindings. A key (string or integer) must be defined before an entity can be bound to data.\n\nUse Graph (GQL) for complex multi-hop traversal; use Query Builder for simple filtering and exploration. An agent can use up to five data sources in any combination.\n\nSemantic models are for reporting domains; ontologies are for organization-wide standardization and AI consumption."
        }
      }
    },
    "Module 5": {
      "topics": {
        "Fabric Security Model": {
          "What It Is": "Microsoft Fabric's layered security model evaluates access sequentially across Microsoft Entra ID, Fabric access, and data security — the data security layer has four controls (workspace roles, item permissions, compute permissions, OneLake security) that narrow from workspace-wide to per-table/folder, implementing the principle of least privilege.",
          "Key Details": "Three levels of access evaluation (sequential): 1. Microsoft Entra ID authentication; 2. Fabric access; 3. Data security. Four primary access controls at the data security level: 1. Workspace roles (broadest); 2. Item permissions; 3. Compute/granular permissions (T-SQL DCL); 4. OneLake security (narrowest).\n\nWorkspace roles (4): Admin, Member, Contributor, and Viewer. Note that Viewers see items but have NO underlying OneLake data access by default.\n\nItem permissions: Read permission grants access to metadata and associated reports, but NO data access to SQL or OneLake. Additional permissions include Read all SQL endpoint data and Read all Apache Spark and subscribe to events. Both grant access to ALL data in the lakehouse by default.\n\nCompute/granular permissions (T-SQL DCL): Supports GRANT, DENY, and REVOKE for SELECT, INSERT, UPDATE, and DELETE. DENY always supersedes GRANT.\n\nOneLake security roles (RBAC within a lakehouse item): Includes Data (tables/folders), Permission (Read/ReadWrite), Members, and Constraints. Only workspace Admin and Member roles can create/modify these. Admin/Member/Contributor workspace roles **bypass** OneLake security.\n\nDefaultReader role: Every lakehouse has a DefaultReader role. Users granted 'Read all Apache Spark' are automatically added. ALWAYS remove them from DefaultReader when adding to a custom restricted role.",
          "Architectural Logic": "The layered model follows the principle of least privilege by starting broad (workspace role for collaboration) and narrowing as needed (item permissions for specific items, compute permissions for engine-specific control, OneLake security for within-item table/folder access). Each layer is independently configurable but works additively — access is the intersection of what the workspace role, item permissions, compute permissions, and OneLake security give. Because Admin/Member/Contributor bypass OneLake security, use workspace roles for broad collaboration and OneLake security specifically for restricting Viewers and Read-permission users who should only see subsets of data.",
          "Implementation Workflow": "1. Assign workspace role for broad collaboration (Admin/Member/Contributor/Viewer). 2. Refine with item permissions — share individual items with Read + additional data permissions when a user needs limited access. 3. Apply granular permissions — T-SQL DCL (GRANT/DENY/REVOKE) for SQL endpoint access; OneLake security roles for Spark/API access to restrict to specific tables/folders. Remove users from DefaultReader when adding to a custom restricted roles. 4. Validate — users with only Viewer role see items but cannot access data until OneLake security roles grant table/folder access.",
          "Exam Gotchas & Distinctions": "Viewers see items listed but have NO underlying OneLake data access by default. Use OneLake security roles to grant data access to viewers. Automatically created in every lakehouse, the DefaultReader role is a common trap; always remove users from it when assigning custom roles. Admin/Member/Contributor workspace roles bypass OneLake security. Read item permission alone does not grant data access; users need Read all SQL endpoint data OR Read all Apache Spark to access actual data. OneLake security is cross-engine: Enforced consistently across Spark, SQL, and OneLake APIs. DENY always supersedes GRANT."
        },
        "Data Warehouse Security": {
          "What It Is": "Fabric data warehouse provides four T-SQL-based data protection features — Dynamic Data Masking (DDM), Row-Level Security (RLS), Column-Level Security (CLS), and SQL granular permissions (SELECT/INSERT/UPDATE/DELETE) — all enforced at the SQL engine level.",
          "Key Details": "Dynamic Data Masking (DDM): Masks column values in query results without altering stored data. Includes functions: default(), email(), partial(), and random(). Applied via ALTER TABLE.\n\nRow-Level Security (RLS): Filters rows at query time based on group membership or execution context. Implemented via an inline table-valued function (security predicate) and a security policy. Applies to SELECT, UPDATE, and DELETE, but NOT INSERT.\n\nColumn-Level Security (CLS): Restricts access to specific columns at query time. Implemented by granting SELECT on the table and then denying SELECT on specific columns. More granular and efficient than Views.\n\nSQL Granular Permissions (DCL): Fundamental permissions include SELECT, INSERT, UPDATE, and DELETE. Applied via GRANT, DENY, and REVOKE. DENY always supersedes GRANT. Use QUOTENAME() in dynamic SQL to prevent injection.",
          "Architectural Logic": "All four features (DDM, RLS, CLS, granular permissions) are enforced at the SQL engine level and operate transparently — queries return masked/filtered/hidden data without application changes. This makes them suitable for securing existing applications that cannot be rewritten. Use DDM to obscure data, RLS to filter rows by identity, and CLS to hide sensitive columns. Use views when you also need row-level filtering and data transformation in a single object.",
          "Implementation Workflow": "1. DDM: `ALTER TABLE [table] ALTER COLUMN [column] ADD MASKED WITH (FUNCTION = '[function]')` 2. RLS: a. Create filter predicate function with `SCHEMABINDING`. b. Create security policy with `ADD FILTER PREDICATE`. 3. CLS: `GRANT SELECT ON [table] TO [role]` $\\rightarrow$ `DENY SELECT ON [table]([column]) TO [role]` 4. Granular permissions: `GRANT/DENY/REVOKE [SELECT|INSERT|UPDATE|DELETE|ALTER|CONTROL] ON [object] TO [user/role]` 5. Dynamic SQL: Use `sp_executesql` with `QUOTENAME()` for safe object name parameterization.",
          "Exam Gotchas & Distinctions": "DDM does not change stored data; it only masks query results. Users with query permissions can infer actual data through inference attacks. RLS side-channel attacks: Risk of information leakage through crafted WHERE clauses that cause exceptions. DENY always supersedes GRANT. CLS is transparent (users query the same table), more granular, efficient, and auto-adapts to table changes. Views are more flexible (can combine row filtering, column filtering, and data transformation in one object). Policy must be ON for RLS to be active. RLS predicate functions must be created WITH SCHEMABINDING. Filter predicates do not apply to INSERT operations — only SELECT, UPDATE, DELETE."
        },
        "Microsoft Purview (Fabric Governance)": {
          "What It Is": "Microsoft Purview provides advanced cross-platform data governance — Data Map, Unified Catalog, Information Protection, Data Loss Prevention, and Audit — extending beyond Fabric's built-in governance capabilities through a registered connection between the Fabric tenant and Microsoft Purview.",
          "Key Details": "Built-in Fabric governance (no Purview license required): Admin Portal, Domains, Workspaces, Capacity, Metadata scanning, Data tags (sensitivity/retention), Workspace roles, Data-level controls, OneLake data hub, Endorsement, Data lineage, Monitoring Hub, and Capacity Metrics App.\n\nPurview pillars (require Purview license + Fabric registration): Data Map (scans assets), Unified Catalog (searchable catalog), Information Protection (classify/label/protect), Data Loss Prevention (detect/monitor/control movement), and Audit (automated logging).\n\nPurview hub in Fabric: Surfaces Purview's governance findings (sensitivity labels, endorsement, domains) within the Fabric UI.",
          "Architectural Logic": "Purview sits outside Fabric as a cross-platform governance layer. It connects to Fabric via a registered tenant connection and scanning process — Purview does not access Fabric data continuously; it scans metadata on a schedule to populate the Data Map and Unified Catalog. Use Purview over built-in Fabric governance when the organization needs cross-platform data estate visibility, DLP, advanced auditing, or Information Rights Management encryption.",
          "Implementation Workflow": "1. Register Fabric tenant: In Purview Portal > Data Map > register data source > select Fabric. 2. Configure authentication: Set up managed identity or other authentication for Purview in Microsoft Entra ID. 3. Create scan: In Purview, create a scan using the Fabric data source to capture metadata. 4. Access Purview hub: In Fabric settings > Microsoft Purview hub to view governance reports and insights. 5. Apply Purview tools: Configure Information Protection, DLP policies, and Audit logging as needed.",
          "Exam Gotchas & Distinctions": "Fabric built-in vs. Purview: Built-in features work without extra licensing and cover basic governance. Purview adds cross-platform scanning, Data Map/Unified Catalog, DLP, IRM, and advanced audit. The Purview hub in Fabric is a gateway, not a replacement for the Purview Portal. The connection must be registered in Purview first. Fabric compliance certifications include HIPAA BAA, ISO/IEC 27017, 27018, 27001, and 27701."
        },
        "Analytics Data Governance": {
          "What It Is": "Governing analytics data in Fabric involves sensitivity labels (classification with downstream inheritance), endorsement (Promoted/Certified/Master data trust signals), documentation (descriptions, tags, lineage, domains), and AI-specific governance (Approved for Copilot gate, endorsement-prioritized AI agent data selection) — all aggregated in the OneLake catalog.",
          "Key Details": "Sensitivity labels: Classify data (Public, General, Confidential, etc.) with Purview. Labels propagate downstream (lakehouse $\\rightarrow$ SQL endpoint $\\rightarrow$ semantic model $\\rightarrow$ report). Labels are preserved on export to Excel, PDF, and .pbix, but NOT on CSV or TXT.\n\nEndorsement levels: Promoted (team-level trust), Certified (organization-authorized), and Master data (authoritative single source of truth, applies ONLY to data items like lakehouses/semantic models).\n\nDocumentation: Use item descriptions (first 200 characters are critical for AI), tags, domains, and data lineage.\n\nAI Governance: Includes AI Data Schema (visibility), AI Instructions (context/rules), Verified Answers (predefined responses), and the Approved for Copilot gate (removes friction).",
          "Architectural Logic": "Governance signals flow from source items downstream through inheritance. The OneLake catalog aggregates these signals into a single searchable/governable surface. AI agents process these signals programmatically — they cannot 'know' which data is trustworthy or sensitive without explicit metadata. Sensitivity labels provide the access boundary, while endorsement provides trust ranking for AI prioritization.",
          "Exam Gotchas": "A single label on a source (e.g., lakehouse) propagates automatically through the entire chain. Master data distinction: Only applies to data items (lakehouses, semantic models) — not reports, notebooks, or pipelines. Reports inherit the status from their semantic model. Changes can take up to 24 hours (most within 1 hour). Verified answers are predefined visual responses for specific trigger phrases. AI instructions provide broad business context. Power BI dashboards do NOT support endorsement. Sensitivity labels are NOT preserved on CSV or TXT exports."
        }
      }
    }
  }
};
