var DP600_DATA = {
  title: "Designing and Implementing Analytics Solutions Using Microsoft Fabric",
  modules: {
    "Module 1": {
      topics: {
        "Microsoft Fabric": {
          core: "Microsoft Fabric is a unified SaaS analytics platform where all data is stored in a single open format (Delta-Parquet) in OneLake, accessible by all compute engines (Data Engineering, Warehouse, Data Factory, Power BI, Real-Time Intelligence, Data Science, Databases, Industry Solutions, IQ) without data movement.",
          tech: "<ul><li>OneLake foundation: Built on ADLS Gen2; all engines write in Delta-Parquet format; open formats (Delta, Parquet, CSV, JSON) supported</li><li>Workspaces: Logical containers for organizing items; support licensing type, OneDrive access, ADLS Gen2 connection, Git integration, Spark workload settings; roles: Admin, Member, Contributor, Viewer</li><li>Admin portal: Manage groups/permissions, configure data sources/gateways, monitor usage/performance; enable Fabric for entire org or specific security groups</li><li>OneLake catalog: Searchable discovery across tenant; shows metadata: name, type, owner, last refresh, workspace, sensitivity labels, endorsement status</li><li>Domains: Group data by business area; used for organization and governance</li><li>Data mesh support: Decentralized data ownership with centralized governance</li><li>Copilot: Generates code, SQL, KQL, DAX, reports; explains and fixes code</li><li>Fabric IQ (preview): Models business data via ontologies, semantic models, and graphs</li><li>Data agents: Conversational Q&A across lakehouses, warehouses, semantic models, ontologies</li><li>Data lineage: Visual view of data flow and dependencies across workspace items</li></ul>",
          archLogic: "Fabric solves the problem of fragmented analytics tooling (separate data lakes, warehouses, ETL tools, BI platforms) by unifying all compute engines on a single open-format data lake (OneLake). This eliminates data duplication, reduces governance gaps, and ensures the same governed data powers both reports and AI workloads. The SaaS model eliminates infrastructure management. Workspaces provide logical isolation and access control, while OneLake provides physical unification.",
          gotchas: "OneLake vs. separate storage: OneLake is a single logical lake. Workspace roles (Admin/Member/Contributor/Viewer) apply to all items; item permissions allow per-item sharing. Fabric IQ = business data; Foundry IQ = enterprise knowledge; Work IQ = collaboration signals. Copilot requires F2 or higher."
        },
        "OneLake": {
          core: "OneLake is the tenant-wide, single-logical-lake storage layer built into every Fabric environment, automatically available with no setup, eliminating data silos.",
          tech: "<ul><li>Storage foundation: Azure Data Lake Storage Gen2 (ADLS Gen2)</li><li>Default table format: Delta Lake (open Parquet files with transaction log)</li><li>OneLake catalog: Searchable inventory across tenant with metadata: name, type, owner, last refresh, workspace, sensitivity labels, endorsement</li><li>Shortcuts: References to external/internal data without copying (OneLake, ADLS Gen2, Amazon S3, Dataverse)</li><li>Ingestion: Mirroring (continuous replication), Pipelines (orchestration), Dataflows (Power Query), Streaming (Eventstream), Direct upload</li><li>Real-Time Hub: Centralized catalog for discovering streaming data (eventstreams, KQL tables) and Azure/Fabric events</li><li>Purview integration: Integrates with Microsoft Purview for data governance (classification, sensitivity labels, lineage)</li></ul>",
          archLogic: "OneLake implements a single copy architecture that eliminates the traditional problem of data silos. In traditional environments, each team maintains its own copy of data for its tools, creating inconsistency and storage waste. OneLake provides a unified storage layer that all compute engines access directly. When data changes, everyone sees the updated version immediately. Shortcuts extend this by providing access to external data without copying, while maintaining data consistency.",
          gotchas: "Shortcuts provide access without duplication; not suitable for point-in-time snapshots or high-latency connections. OneLake catalog is for batch/stored data; Real-Time Hub is for data-in-motion."
        },
        "Lakehouse": {
          core: "A lakehouse in Fabric combines flexible data lake storage with data warehouse analytical capabilities, storing structured, semi-structured, and unstructured data in OneLake with both Apache Spark and a read-only SQL analytics endpoint.",
          tech: "<ul><li>Storage areas: Tables (Managed Delta Lake tables) and Files (Raw/semi-structured files)</li><li>Delta Lake: Provides ACID transactions, schema enforcement, and time travel</li><li>Access modes: Lakehouse Explorer (management) and SQL analytics endpoint (read-only T-SQL)</li><li>Schemas: Enabled by default; organize tables by business domain; support four-part namespace queries</li><li>Compute: Spark notebooks for read/write, SQL analytics endpoint for read-only T-SQL, Power BI Direct Lake (no import/refresh)</li><li>Security: Workspace roles, item-level sharing, and SQL analytics endpoint RLS/CLS</li></ul>",
          archLogic: "The lakehouse solves the two-tier problem where organizations maintained both a data lake (for scale, flexibility, low cost) and a data warehouse (for ACID, schema, query performance). By bringing Delta Lake (ACID, schema enforcement, time travel) directly to the data lake storage, the lakehouse eliminates the need to manage separate systems for raw exploration and structured analytics. Use a lakehouse when you need to handle mixed data formats, evolving schemas, medallion architecture, or Python/Spark-based data science.",
          gotchas: "Tables are Delta-formatted and SQL-queryable; Files are raw and not SQL-accessible. SQL analytics endpoint is read-only (no INSERT/UPDATE/DELETE). Direct Lake falls back to DirectQuery if memory thresholds are exceeded."
        },
        "Data Warehouse": {
          core: "A Fabric data warehouse is a fully managed, enterprise-scale relational database built on Delta format in OneLake, providing full read-write T-SQL (DDL and DML) with multi-table ACID compliance.",
          tech: "<ul><li>Storage: Open Delta format on OneLake accessible by other Fabric workloads</li><li>T-SQL: Full DDL (CREATE, ALTER, DROP) and DML (INSERT, UPDATE, DELETE, MERGE) with ACID compliance</li><li>Ingestion: COPY INTO (bulk load), OPENROWSET (query files without creating tables), Pipelines, and Dataflows</li><li>Cross-database queries: Three-part naming (database.schema.table) to join warehouse and lakehouse tables</li><li>Table clones: Zero-copy reference at a point in time</li><li>Security: Workspace roles, item permissions, and granular SQL security (object-level, RLS, CLS, Dynamic Data Masking)</li><li>Monitoring: Query Insights (30-day retention) via system views</li></ul>",
          archLogic: "The warehouse bridges traditional relational data warehousing with modern data lake architecture by storing all data in Delta format on OneLake while providing the full T-SQL surface that SQL professionals expect. Unlike the lakehouse (read-only SQL endpoint), the warehouse supports full DDL/DML, enabling transactional ETL patterns. Use warehouse over lakehouse when the workload requires multi-table ACID transactions, slowly changing dimension updates, or a SQL-first team that needs full DDL/DML.",
          gotchas: "Warehouse = full read-write T-SQL; Lakehouse endpoint = read-only. Fabric warehouse does NOT enforce foreign key constraints. Table clones are zero-copy. Query Insights retention is 30 days."
        },
        "Real-Time Intelligence": {
          core: "Provides an integrated suite (Eventstreams, Eventhouses, Real-Time Hub, KQL Querysets, Real-Time Dashboards, Activator) to ingest, process, store, query, visualize, and act on streaming data with minimal latency.",
          tech: "<ul><li>Eventstreams: Continuous data flows with real-time transformations (filter, aggregate, join) and multiple destinations</li><li>Eventhouse: KQL databases storing time-series data with automatic indexing and partitioning by ingestion time</li><li>KQL (Kusto Query Language): Designed for time-series analysis; uses pipeline operators (take, where, summarize, project)</li><li>Real-Time Dashboards: Auto-refreshing tiles based on KQL queries</li><li>Activator: Monitors streaming data against user-defined rules to trigger actions (notifications, Power Automate, pipelines)</li><li>Real-Time Hub: Central catalog for streaming data discovery</li></ul>",
          archLogic: "Real-Time Intelligence is designed for latency-sensitive workloads where data value decreases rapidly with time. Unlike batch pipelines that process on schedules, RTI operates on continuous data flows. Each component handles a specific stage — capture (Eventstreams/Hub), store (Eventhouse), analyze (KQL), visualize (Dashboards), act (Activator). The system uses append-only immutable events as its core data model.",
          gotchas: "Real-Time Intelligence is event-driven, not batch-scheduled. Eventhouses are used for streaming data that needs to be queryable within seconds. Eventstream transformations happen in-flight; KQL update policies happen after landing."
        }
      }
    },
    "Module 2": {
      topics: {
        "Lakehouse": {
          core: "A Fabric lakehouse combines data lake scalability with data warehouse query capabilities, storing structured, semi-structured, and unstructured data in OneLake and offering both Apache Spark (read/write) and a read-only SQL analytics endpoint.",
          tech: "<ul><li>Areas: Tables (managed Delta tables) and Files (unstructured/non-Delta data)</li><li>Access paths: Spark (Python, Scala, SQL, R) for read/write; SQL analytics endpoint for read-only T-SQL queries</li><li>Storage format: Delta Lake (Parquet with transaction log)</li><li>Transaction support: Single-table ACID through Delta Lake only; no multi-table transactions</li><li>Write support: Spark notebooks, pipelines, dataflows, Spark job definitions</li><li>Read support: Spark + T-SQL via SQL analytics endpoint; Power BI via Direct Lake mode</li><li>AI integration: Spark MLlib, scikit-learn run natively; Semantic Link (SemPy) bridges Power BI semantic models and lakehouse data</li></ul>",
          archLogic: "The lakehouse solves the problem of having separate data lakes (for data science) and data warehouses (for BI) that require data duplication. By using Delta format on OneLake and providing both Spark and SQL access to the same copy, it enables data engineers to transform data with notebooks and analysts to query the same data with T-SQL or Power BI Direct Lake—without moving data. Use lakehouse over warehouse when data includes unstructured formats, schemas are evolving, or the team works in Python/Spark.",
          gotchas: "SQL analytics endpoint is read-only: no DDL/DML. Single-table vs. multi-table ACID: Lakehouse provides single-table ACID via Delta; warehouse provides multi-table ACID via T-SQL. Direct Lake on lakehouse falls back to DirectQuery if the query exceeds memory/resource thresholds."
        },
        "Warehouse": {
          core: "A Fabric warehouse is an enterprise-scale relational data store built on Delta format in OneLake, providing full read-write T-SQL with multi-table ACID transactions for structured, governed analytical workloads.",
          tech: "<ul><li>Storage format: Delta (Parquet with transaction log) on OneLake</li><li>Transaction support: Full multi-table ACID (multiple tables commit or roll back together)</li><li>Write support: T-SQL (INSERT, UPDATE, DELETE, MERGE, COPY INTO, CTAS), pipelines, dataflows</li><li>Read support: T-SQL (SELECT, views, stored procedures, functions); Power BI via Direct Lake</li><li>Tooling support: SSMS, VS Code with MSSQL extension, Visual Query Editor</li><li>No foreign key enforcement: Fabric warehouses do not enforce FK constraints</li></ul>",
          archLogic: "The warehouse provides a schema-on-write environment prioritizing data quality and governance. Unlike the lakehouse's flexible schema-on-read, the warehouse validates data types and constraints at load time, catching errors early. Use warehouse over lakehouse when the workload requires multi-table ACID transactions, slowly changing dimension updates, or a SQL-first team that needs full DDL/DML.",
          gotchas: "Warehouse vs. lakehouse SQL analytics endpoint: The warehouse is read-write; the lakehouse endpoint is read-only. Both support Direct Lake for Power BI. No foreign key enforcement. Direct Lake: Warehouse supports Direct Lake with no scheduled import refresh. COPY INTO: Available in warehouse for high-speed ingestion from files in ADLS Gen2 or OneLake."
        },
        "Eventhouse": {
          core: "An eventhouse is a real-time analytics store in Fabric, using Kusto Query Language (KQL) and built on a workspace of KQL databases, optimized for streaming ingestion, time-series data, and high-volume event-based workloads.",
          tech: "<ul><li>Architecture: A workspace of KQL databases sharing capacity and resources</li><li>Primary query language: Kusto Query Language (KQL); also supports a subset of T-SQL</li><li>Write support: Streaming ingestion, batch ingestion, Eventstream, SDKs, Kafka, Logstash, dataflows</li><li>Read support: KQL, T-SQL (subset), Power BI via DirectQuery (not Direct Lake)</li><li>Storage format: Columnar store with automatic indexing and compression</li><li>Partitioning: Automatic time-based partitioning and indexing by ingestion time</li></ul>",
          archLogic: "The eventhouse solves the problem of real-time analytics on streaming data—a gap in batch-oriented stores like the lakehouse and warehouse. Its automatic time-based partitioning and columnar storage with built-in indexing enable sub-second queries on append-heavy event data. Use eventhouse over lakehouse/warehouse when data arrives continuously, needs to be queryable within seconds, and involves time-window analysis.",
          gotchas: "Power BI connection: Eventhouse uses DirectQuery (not Direct Lake) because the columnar format is not Delta/Parquet-based. Append-only: The eventhouse is not designed for UPDATE/DELETE. KQL vs. T-SQL: KQL provides the richest analytics experience for time-series. Always-On: Must be explicitly enabled; adds cost but eliminates cold-start latency."
        },
        "Dimensional Modeling": {
          core: "Dimensional modeling organizes data into fact tables (numeric measures of business events) and dimension tables (descriptive attributes), prioritizing query performance and user comprehension over storage normalization.",
          tech: "<ul><li>Fact tables contain: Dimension keys, Measures (numeric, aggregatable values), Attributes/degenerate dimensions</li><li>Fact table types: Transaction, Periodic Snapshot, Accumulating Snapshot</li><li>Factless fact tables: Capture occurrences without numeric measures</li><li>Aggregate fact tables: Precomputed summaries at higher granularity/lower dimensionality</li><li>Measure types: Additive, Semi-additive, Non-additive</li><li>Grain: Defines what one fact row represents. Always define grain BEFORE identifying dimensions and measures.</li><li>Dimension tables contain: Surrogate key, Natural key/business key, Dimension attributes</li><li>Schema organization: Use schemas (dim, fact, staging, gold, reporting) to separate objects by role</li></ul>",
          archLogic: "Dimensional modeling solves the problem that normalized transactional schemas are inefficient for analytical queries (too many joins, unintuitive for business users). The star schema denormalizes dimensions so that queries need only one join per dimension, matching how users naturally ask questions. The tradeoff is storage redundancy from denormalization, but the storage cost is negligible compared to query performance gains.",
          gotchas: "Grain-first rule: The most common design error is identifying dimensions/measures before defining the grain. Star vs. snowflake for Power BI: Snowflake dimensions require a view to flatten joins. Degenerate dimensions: Attributes stored directly in the fact table are not separate dimension tables. Semi-additive measures: Inventory levels and account balances cannot be summed across time."
        },
        "Slowly Changing Dimensions (SCD)": {
          core: "SCD patterns define how dimension tables respond when source system attribute values change, balancing historical accuracy against implementation complexity.",
          tech: "<ul><li>Type 0 (Retain original): Never allows changes. Use for fixed reference data.</li><li>Type 1 (Overwrite): Replaces the old value with the new value; no history maintained.</li><li>Type 2 (Add new row): Inserts a new row for each change; maintains full version history. Requires start_date, end_date, is_current flag.</li><li>Type 3 (Add new column): Stores current and previous value in separate columns.</li><li>Type 6 (Hybrid): Combines Type 1, Type 2, and Type 3.</li><li>Selection guide: Fixed reference data = Type 0; Corrections = Type 1; Full historical accuracy = Type 2; Current vs. previous only = Type 3; Current + historical context = Type 6</li></ul>",
          archLogic: "SCD patterns resolve the conflict between transactional systems (which overwrite data) and analytical systems (which must describe the past accurately). Without an SCD strategy, overwriting a customer's region would retroactively change all historical analysis. Type 2 is the most common for audit-critical attributes because it preserves the context that existed at the time of each fact event.",
          gotchas: "Type 2 fact loading nuance: Joining on is_current = 1 gives the current attribute values for all historical facts. For historical accuracy, join on effective date range instead. Don't apply Type 2 to every attribute. Type 1 + Type 2 on the same dimension: A dimension can mix SCD types. Surrogate key replacement: When a Type 2 change occurs, the surrogate key changes."
        },
        "Dataflows Gen2": {
          core: "Dataflows Gen2 provide a cloud-based, low-code Power Query ETL experience in Fabric for connecting, transforming, and loading data into lakehouses, warehouses, and other destinations without writing code.",
          tech: "<ul><li>Interface: Power Query Online (visual, no-code/low-code)</li><li>Destinations: Fabric Lakehouse, Fabric Warehouse, Azure SQL Database, ADLS Gen2, Azure Data Explorer, Snowflake, SharePoint Files</li><li>Update methods: Replace (drops and recreates), Append (adds new rows), Incremental refresh (refreshes only new/changed data)</li><li>Query folding: Pushes M steps to source as native queries</li><li>Copilot for Dataflow Gen2 (requires F2 or higher)</li></ul>",
          archLogic: "Dataflows Gen2 democratize data preparation by extending Power Query skills to enterprise-scale cloud ETL. The separation of transformation logic from execution engine makes transformations repeatable, auditable, and reusable across multiple destinations. Use dataflows over notebooks when the team is comfortable with Power Query and transformations are simple to moderate.",
          gotchas: "Dataflows Gen1 (Power BI) vs. Gen2 (Fabric): Gen1 is legacy; Gen2 supports multiple external destinations and Copilot. KQL destination: Append only - Replace and Incremental Refresh not supported. Query folding check: Folding breaks at a step and all subsequent steps run locally."
        },
        "Notebooks": {
          core: "Fabric notebooks are interactive, web-based coding environments powered by Apache Spark for scalable, code-first data transformation using PySpark (Python), Spark SQL, Scala, or R.",
          tech: "<ul><li>Languages: PySpark, Spark SQL, Scala, R</li><li>Spark session: Starts automatically on first cell execution; persists until stopped or times out</li><li>Lakehouse attachment: Pin a default lakehouse for table access by name</li><li>Delta table features: ACID transactions, Schema enforcement, OPTIMIZE, VACUUM, V-Order, Optimize Write</li><li>Partitioning guidelines: Benefit when table exceeds 1 TB; target partition size >= 1 GB</li><li>Write modes: overwrite, append</li></ul>",
          archLogic: "Notebooks solve the problem of complex, large-scale data transformation that low-code tools cannot handle. By providing the full Apache Spark engine with multiple language support, notebooks enable data engineers and scientists to implement custom logic on datasets larger than what a single machine can process. Use notebooks over Dataflows Gen2 when transformations require complex joins, window functions, conditional logic, ML libraries, or large datasets.",
          gotchas: "Notebooks vs. Dataflows Gen2: Notebooks are code-based, handle complex logic; Dataflows are visual/low-code. Spark session sharing: Variables and temp views created in one cell are available in subsequent cells. Partitioning thresholds: Partition only when table > 1 TB. V-Order disabled by default. OPTIMIZE vs. VACUUM: OPTIMIZE compacts files but keeps all versions; VACUUM deletes old files."
        },
        "T-SQL Transformations": {
          core: "T-SQL in a Fabric warehouse provides a full read-write, multi-table ACID transactional environment for transforming structured relational data using DDL, DML, views, stored procedures, and dimensional table patterns.",
          tech: "<ul><li>Key commands: CTAS (CREATE TABLE AS SELECT), MERGE (upsert), COPY INTO (bulk load)</li><li>Views: Named SELECT statement; no data storage; always reflects current source state</li><li>Stored procedures: Named block of T-SQL with write operations, parameters, error handling</li><li>Loading patterns: Full refresh, Incremental load (watermark column), Merge (upsert)</li><li>Table clones: Zero-copy reference at a point in time</li><li>No foreign key enforcement</li></ul>",
          archLogic: "T-SQL in the warehouse provides the transactional integrity and governance that dimensional modeling requires. Stored procedures and views encapsulate transformation logic into reusable, parameterizable, and automatable components. Use T-SQL over notebooks when the team is SQL-first and the transformation pattern involves DML operations, transactional consistency, or scheduled incremental refreshes.",
          gotchas: "Warehouse vs. lakehouse SQL analytics endpoint: The warehouse supports full read-write T-SQL; the lakehouse endpoint is read-only. Views vs. Tables: Views are virtual; Tables are materialized. Views vs. Stored Procedures: Views are read-only SELECT; stored procedures support writes, parameters, multi-step logic. No FK enforcement: Fact-to-dimension integrity depends entirely on the ETL process."
        }
      }
    },
    "Module 3": {
      topics: {
        "DAX Calculations": {
          core: "DAX (Data Analysis Expressions) is a formula language in Power BI semantic models for creating calculated tables, calculated columns, and measures—three calculation types with distinct evaluation behavior, storage characteristics, and use cases.",
          tech: "<ul><li>Calculated Tables: DAX formula returning a table object. Use cases: duplicate a table for role-playing dimensions, create date tables, enable what-if analysis.</li><li>Calculated Columns: DAX formula returning a scalar per row, evaluated in row context. Use RELATED() for lookups across relationships.</li><li>Explicit Measures: DAX formulas evaluated at query time using filter context; do not store values.</li><li>Iterator Functions (X-functions): SUMX, AVERAGEX, COUNTX, MINX, MAXX, RANKX.</li><li>Storage comparison: Calculated Columns evaluate at refresh and store value per row. Measures evaluate at query time with no storage.</li></ul>",
          archLogic: "DAX provides a layered calculation architecture: calculated tables add structural data, calculated columns add row-level attributes, and measures define dynamic aggregations. This separation keeps the model efficient—measures don't store data, while calculated columns/tables do. The key design principle: prefer measures over calculated columns whenever possible.",
          gotchas: "Calculated Columns vs. Measures: Calculated columns store values (increase model size, evaluated at refresh). Measures are computed at query time (no storage). RELATED vs. LOOKUPVALUE: RELATED uses existing relationships (fast). LOOKUPVALUE scans the table (slow). SUM vs. SUMX: Identical for single-column aggregation. Row context vs. Filter context: Calculated columns use row context; Measures use filter context."
        },
        "Storage Modes": {
          core: "Storage mode choice (Direct Lake, Import, DirectQuery, or Composite) determines query performance, data freshness, available Fabric features, and model size limits in a semantic model, with Direct Lake as the default for Fabric-native workloads.",
          tech: "<ul><li>Direct Lake (default for Fabric): Reads Delta tables from OneLake into memory on demand. No scheduled refresh needed.</li><li>Import Mode: Copies data into compressed in-memory format. Fastest query performance. Data freshness depends on refresh schedule.</li><li>DirectQuery Mode: Sends queries to source at query time—no data stored.</li><li>Composite Mode: Mixes storage modes per table in the same model.</li><li>Large Semantic Model Storage Format: Removes 10-GB upload limit. Required for XMLA read/write and query scaleout.</li></ul>",
          archLogic: "Direct Lake is the cornerstone of Fabric's scalable semantic model architecture. It avoids both the staleness of Import (requires refresh) and the latency of DirectQuery (depends on source query speed) by reading Delta files directly from OneLake. The tradeoff is fallback risk: certain DAX patterns or query complexity can trigger DirectQuery fallback.",
          gotchas: "Direct Lake vs. DirectQuery: Direct Lake reads columnar Parquet directly (fast, no refresh). DirectQuery translates to source SQL. Direct Lake fallback is configurable: Allowed vs. Disallowed. Large Model Format prerequisite: Required for XMLA read/write AND Query Scaleout. OneLake Integration only exports Import tables."
        },
        "Star Schema Design": {
          core: "Star schema design in semantic models organizes fact tables (measures) and dimension tables (context) with single-direction one-to-many relationships for clean filter propagation, performant queries, and reliable AI consumption.",
          tech: "<ul><li>Relationship types: One-to-many, Many-to-many (bridge table), Cross-source (composite model)</li><li>Filter direction: Single-direction (dimension → fact) is the standard. Bi-directional filtering necessary for many-to-many; use sparingly.</li><li>Referential integrity: Assume Referential Integrity setting tells engine to use INNER joins instead of LEFT OUTER joins.</li><li>Inactive relationships + USERELATIONSHIP: Activate inactive relationship in DAX with CALCULATE.</li><li>Snowflake handling: Flatten into star (preferred) or preserve snowflake (only when hierarchy has many levels).</li></ul>",
          archLogic: "A well-designed star schema gives both Power BI and AI tools clear filter paths from dimensions to facts. Single-direction filtering keeps behavior predictable and performant. The relationship design decision is the semantic model equivalent of foreign keys in a database—but with cardinality and cross-filter direction as additional dimensions.",
          gotchas: "Referential Integrity setting: INNER vs. LEFT OUTER join behavior. Violations cause silent data loss. USERELATIONSHIP is a CALCULATE modifier. Snowflake flattening is preferred. Bi-directional filtering is expensive."
        },
        "Performance Optimization": {
          core: "Semantic model performance optimization follows a systematic diagnose-fix-verify workflow using Performance Analyzer to identify bottlenecks, then targets DAX optimization, cardinality reduction, aggregation implementation, and visual simplification.",
          tech: "<ul><li>Performance Analyzer: Built into Power BI Desktop and service. Breaks visual load time into: DAX query, Visual display, Direct query, Other.</li><li>DAX Optimization: Variables (VAR/RETURN), FILTER vs. column predicate, KEEPFILTERS.</li><li>Cardinality Reduction: Remove unused columns, reduce time precision, bucket continuous values.</li><li>Aggregations: User-defined (manually create summary table) or Automatic (ML based on query log).</li><li>Visual design best practices: ≤8 visuals per page; reduce measures/data points per visual.</li></ul>",
          archLogic: "Performance optimization follows a measure, fix, verify workflow because guessing at bottlenecks wastes effort. The VertiPaq engine compresses data column-by-column, so high-cardinality columns and complex filter patterns are the primary bottlenecks. The key architectural insight: Import model performance depends on model size and DAX efficiency; Direct Lake performance depends on Delta file structure and DAX complexity.",
          gotchas: "Performance Analyzer vs. DAX Studio: PA identifies which visual is slow; DAX Studio provides engine-level diagnostics. FILTER dimension tables, not fact tables. User-defined aggregations require composite model."
        },
        "Semantic Model Security": {
          core: "Row-level security (RLS) restricts which rows a user sees via DAX filter expressions on dimension tables; object-level security (OLS) hides entire tables or columns from specific roles, configured via external tools like Tabular Editor.",
          tech: "<ul><li>RLS implementation: Static (hardcoded filter) or Dynamic (uses USERPRINCIPALNAME()). Security table pattern: Dedicated table mapping users to data partitions using CONTAINS.</li><li>USERNAME() vs. USERPRINCIPALNAME(): USERNAME() returns DOMAIN\\username in Desktop, user@domain.com in service. USERPRINCIPALNAME() returns user@domain.com consistently.</li><li>OLS implementation: Cannot configure in Power BI Desktop natively—requires Tabular Editor. Permission values: None (hidden) or Read (visible).</li><li>Testing roles: Desktop (Modeling > View as), Service (Semantic model > More options > Security > Test as role).</li><li>Role membership: Supported: individual users, Microsoft Entra security groups, distribution groups, service principals. NOT supported: Microsoft 365 groups.</li></ul>",
          archLogic: "RLS and OLS serve different security dimensions. RLS filters rows (who sees which records), OLS restricts table/column visibility (who sees which schema elements). Both apply to all consumption paths. Dynamic RLS with USERPRINCIPALNAME() is the recommended pattern because it decouples security from model maintenance.",
          gotchas: "RLS vs. OLS: RLS filters rows; OLS hides entire tables or columns. USERNAME() vs. USERPRINCIPALNAME(): USERNAME() returns different formats in Desktop vs. service. Workspace role bypass: Admin/Member/Contributor see ALL data regardless of RLS/OLS."
        },
        "Development Lifecycle": {
          core: "Managing the semantic model lifecycle in Fabric involves four stages—Develop (reusable assets, version control), Validate (XMLA/SemPy), Deploy (deployment pipelines), Monitor (refresh, monitoring).",
          tech: "<ul><li>Reusable Assets: Shared semantic model, Power BI template (.pbit), Data source file (.pbids).</li><li>Version Control: Power BI Project (.pbip) saves as plain text files (TMDL). Fabric Git Integration: Bidirectional sync with Azure DevOps/GitHub.</li><li>XMLA Endpoint & SemPy: SemPy Python library for automated validation. XMLA enables external tools (Tabular Editor, DAX Studio, ALM Toolkit).</li><li>Deployment Pipelines: Default stages: Development → Test → Production. Customizable (2-10 stages). Deployment rules: Data source rules and parameter rules.</li><li>Monitor: Scheduled refresh, Pipeline-based refresh, Monitoring Hub, Refresh history, Lineage view.</li></ul>",
          archLogic: "The lifecycle follows a Develop → Validate → Deploy → Monitor workflow that addresses common problems at scale. Reusable assets establish consistency. .pbip projects with TMDL text files make semantic model changes reviewable through Git. SemPy provides programmatic validation that can be automated in notebooks.",
          gotchas: ".pbip vs. .pbix: .pbip stores as TMDL text files (diff-friendly, mergeable). .pbix is binary. Git Integration vs. Deployment Pipelines: Git is for version control/collaboration. Deployment Pipelines are for environment promotion. Deployment rules configure BEFORE first deploy."
        }
      }
    },
    "Module 4": {
      topics: {
        "AI-Ready Semantic Layer": {
          core: "Preparing a semantic model for AI consumption involves grounding AI tools like Copilot and data agents with clear naming, thorough documentation (descriptions within 200 characters), linguistic synonyms/relationships, and explicit Prep for AI configuration.",
          tech: "<ul><li>Grounding: Contextual information that AI retrieves before generating a response.</li><li>RAG process: User submits prompt → Copilot preprocesses by collecting grounding data → sends to Azure OpenAI → generates response → postprocesses with responsible AI filters.</li><li>What AI consumes: Table names, Column names, Relationships, Measure definitions, Descriptions (first 200 characters), Linguistic schema, Data categories.</li><li>Gold layer design: One entity per table, Star schema structure, Business-friendly table names.</li><li>Prep for AI features: AI data schema, AI instructions, Verified answers.</li><li>Approved for Copilot: Removes friction treatments from Copilot answers.</li></ul>",
          archLogic: "AI tools have no inherent business knowledge — they rely entirely on grounding data retrieved during the RAG preprocessing step. The quality of AI output is directly tied to grounding data quality. The semantic model sits at the critical junction between data engineering and AI consumption.",
          gotchas: "Grounding vs. ontology: Grounding is per-model context; ontology is organization-wide. Hidden fields: Hiding a field removes it from AI consideration entirely. First 200 characters truncation: Descriptions are truncated at 200 characters for grounding. Copilot nondeterministic: Same prompt can produce different responses."
        },
        "Fabric IQ (Ontology)": {
          core: "Fabric IQ creates ontologies — organization-wide, machine-understandable vocabularies of business concepts bound to OneLake data sources, enabling natural language queries through data agents and visual graph traversal.",
          tech: "<ul><li>Ontology item: Fabric artifact containing entity types, properties, relationship types, and data bindings.</li><li>Build-bind-query workflow: 1. Define entity types, properties, and relationship types. 2. Bind ontology to lakehouse tables (static) and eventhouse streams (time-series). 3. Query via Graph (GQL), Query Builder, or data agents.</li><li>Entity type components: Name, Properties, Key (required before binding).</li><li>Data binding: Static bindings (lakehouse tables) and Time series bindings (eventhouse tables).</li><li>Data agents: Conversational Q&A powered by Azure OpenAI. Configure with up to five data sources.</li><li>Graph in Microsoft Fabric: Native graph storage using labeled property graph model. Queried via GQL.</li></ul>",
          archLogic: "Fabric IQ separates business meaning from physical data structures. The ontology defines what a 'Patient' is and how it relates to 'Departments' without requiring knowledge of table schemas. Data binding maps these conceptual definitions to actual OneLake sources without moving or duplicating data.",
          gotchas: "Ontology vs. semantic model: Semantic models serve specific reporting domains; ontologies standardize concepts organization-wide. Direct Lake required for full generation. Static binding first in dual-binding. Entity key requirement: Keys are required before binding."
        }
      }
    },
    "Module 5": {
      topics: {
        "Fabric Security Model": {
          core: "Microsoft Fabric's layered security model evaluates access sequentially across Microsoft Entra ID, Fabric access, and data security — the data security layer has four controls (workspace roles, item permissions, compute permissions, OneLake security) that narrow from workspace-wide to per-table/folder.",
          tech: "<ul><li>Three levels of access evaluation (sequential): 1. Microsoft Entra ID authentication, 2. Fabric access, 3. Data security.</li><li>Four primary access controls at the data security level: 1. Workspace roles (apply to all items), 2. Item permissions (apply to a single item), 3. Compute/granular permissions (T-SQL DCL), 4. OneLake security (RBAC within an item).</li><li>Workspace roles (4): Admin, Member, Contributor, Viewer.</li><li>Item permissions: Read (metadata only), Read all SQL endpoint data, Read all Apache Spark and subscribe to events.</li><li>OneLake security roles: Four components: Data, Permission (Read/ReadWrite), Members, Constraints.</li><li>DefaultReader role: Every lakehouse has an auto-created DefaultReader role.</li></ul>",
          archLogic: "The layered model follows the principle of least privilege by starting broad (workspace role for collaboration) and narrowing as needed. Because Admin/Member/Contributor bypass OneLake security, use workspace roles for broad collaboration and OneLake security specifically for restricting Viewers and Read-permission users.",
          gotchas: "Viewer role and OneLake data: Viewers see items listed but have NO underlying OneLake data access by default. DefaultReader: ALWAYS remove from DefaultReader before adding to a custom restricted role. Admin/Member/Contributor bypass OneLake security. DENY supersedes GRANT."
        },
        "Data Warehouse Security": {
          core: "Fabric data warehouse provides four T-SQL-based data protection features — Dynamic Data Masking, Row-Level Security, Column-Level Security, and SQL granular permissions — all enforced at the SQL engine level.",
          tech: "<ul><li>Dynamic Data Masking (DDM): Masks column values in query results without altering stored data. Functions: default(), email(), partial(), random().</li><li>Row-Level Security (RLS): Filters rows via security predicates. Two-step: create filter predicate function, then create security policy.</li><li>Column-Level Security (CLS): GRANT SELECT on entire table, then DENY SELECT on specific column.</li><li>SQL granular permissions (DCL): GRANT, DENY, REVOKE. DENY always supersedes GRANT.</li></ul>",
          archLogic: "All four features are enforced at the SQL engine level and operate transparently — queries return masked/filtered/hidden data without application changes. Use DDM when the requirement is to obscure but still indicate the type of data. Use RLS when different users should see different rows. Use CLS when specific columns are too sensitive for certain roles.",
          gotchas: "DDM does not change stored data. RLS side-channel attacks. DENY supersedes GRANT. CLS vs. Views: CLS is transparent, more granular, more efficient. SECURITY POLICY with STATE = ON/OFF. INSERT not affected by filter predicates."
        },
        "Microsoft Purview": {
          core: "Microsoft Purview provides advanced cross-platform data governance — Data Map, Unified Catalog, Information Protection, Data Loss Prevention, and Audit — extending beyond Fabric's built-in governance capabilities.",
          tech: "<ul><li>Built-in Fabric governance: Admin Portal, Domains, Workspaces, Metadata scanning, Endorsement, Data lineage, Monitoring Hub.</li><li>Purview tools (require Purview license): Data Map, Unified Catalog, Information Protection, DLP, Audit.</li><li>Purview hub in Fabric: Displays reports and insights about Fabric items. Acts as a centralized gateway.</li></ul>",
          archLogic: "Purview sits outside Fabric as a cross-platform governance layer. It connects to Fabric via a registered tenant connection and scanning process. The Purview hub in Fabric is the integration point: it surfaces Purview's governance findings within the Fabric UI.",
          gotchas: "Fabric built-in vs. Purview: Built-in features work without extra licensing. Purview adds cross-platform scanning, DLP, IRM encryption, advanced audit. Purview hub is a gateway. Connection must be registered in Purview first."
        },
        "Analytics Data Governance": {
          core: "Governing analytics data in Fabric involves sensitivity labels, endorsement, documentation, and AI-specific governance — all aggregated in the OneLake catalog.",
          tech: "<ul><li>Sensitivity labels: Metadata tags that travel with data on export. Downstream inheritance: Labels applied at source propagate automatically. NOT preserved on CSV or TXT.</li><li>Endorsement levels: Promoted (any user with write permissions), Certified (organization-authorized reviewer), Master data (admin-designated; applies ONLY to data items).</li><li>OneLake catalog: Explore tab, Govern tab, Secure tab.</li><li>AI consumption governance: Sensitivity labels define boundaries, Endorsement signals trust, Descriptions provide context.</li><li>Approved for Copilot: Removes friction treatments. Prep for AI: AI data schema, AI instructions, Verified answers.</li></ul>",
          archLogic: "Governance signals flow from source items downstream through inheritance. The OneLake catalog aggregates these signals into a single searchable/governable surface. AI agents process these signals programmatically — they cannot know which data is trustworthy or sensitive without explicit metadata.",
          gotchas: "Label propagation vs. manual labeling: One label on a lakehouse propagates downstream through the entire chain. Master data vs. Certified: Certified signals quality; Master data signals authoritative source of truth. Labels not preserved on CSV/TXT. Endorsement exception: Power BI dashboards do NOT support endorsement."
        }
      }
    }
  }
};
