var DP300_DATA = {
  "title": "Designing and Implementing Azure Database Solutions",
  "modules": {
    "Module 1": {
      "topics": {
        "Azure SQL Platform Options": {
          "What It Is": "Microsoft offers three primary SQL Server-based options in Azure: SQL Server on Azure VM (IaaS), Azure SQL Database (PaaS single DB/elastic pool), and Azure SQL Managed Instance (PaaS full instance). The choice depends on how much control vs. management overhead you need, and what compatibility your existing applications require.",
          "IaaS vs PaaS Decision": "IaaS (SQL Server on Azure VM) gives you full control over OS and SQL Server — you manage patching, configuration, and backups. It is best for legacy applications requiring older SQL versions, applications needing SSIS/SSRS/SSAS on the same machine, or apps requiring CLR, cross-database queries, or OS-level access. The SQL Server IaaS Agent Extension provides automated backup, patching, Key Vault integration, Defender for Cloud, and disk utilization views.<br><br>PaaS (SQL Database) is fully managed — no OS/SQL patching, automated backups, built-in HA. Best for new cloud-native apps, intermittent/unpredictable usage (serverless tier), simplified deployment, and scaling up to 100 TB (Hyperscale). SQL Database supports DTU (bundled) and vCore (decoupled) purchasing models, single database or elastic pool deployment, and serverless compute with autopause.<br><br>PaaS (Managed Instance) is near 100% compatible with on-premises SQL Server in a fully managed instance. Best for lift-and-shift migrations without application changes, apps needing instance-scoped features (SQL Agent, CLR, cross-DB queries, Service Broker). Supports up to 100 databases per instance, General Purpose and Business Critical service tiers, and dedicated VNet deployment.",
          "Licensing": "Pay-as-you-go (PAYG) via Marketplace images: pay per minute for SQL Server license plus VM cost. Bring Your Own License (BYOL): use existing SA license on blank VM or AHB option. Azure Hybrid Benefit (AHB): 1 EA core = 1 vCore Business Critical or 8 vCores General Purpose; 1 Std core = 1 vCore General Purpose; up to 40% savings. Reserved Instances: 1-3 year commitment, monthly billing, no upfront required. Flexible Licensing: toggle between PAYG and BYOL/AHB without redeployment via the IaaS Agent Extension.",
          "HA and DR Options": "**HA within a region:** Availability Zones (99.99%, 3 zones), Availability Sets (99.95%, different racks), Always On Availability Groups (up to 9 replicas, sync/async, unit=DB group), Failover Cluster Instance (unit=instance, requires shared storage).<br><br>**DR across regions:** Native backups to URL (Blob Storage, GRS/RA-GRS), Azure Backup, Azure Site Recovery (VM-level, higher RPO), Always On AG async replicas across regions, auto-failover groups for SQL DB and MI.<br><br>**Managed Instance Link:** DAG-based replication between on-prem SQL Server and MI; one-way (2016/2019) or two-way (2022); supports DR, read-scale, automated backups; seconds cutover.",
          "Exam Gotchas": "SQL Database and SQL Managed Instance share the same base code but differ in instance-scoped features: SQL Agent, CLR, cross-DB queries, Service Broker are MI-only. SQL Database does NOT support SQL Agent (use elastic jobs), T-SQL RESTORE, COPY_ONLY backups, or cross-DB queries natively. Managed Instance does NOT support DTU model, elastic pools, elastic jobs, or Hyperscale. Always On AG unit of failover = database group; FCI unit = entire instance. Hyperscale cannot be reverted to standard tier. Serverless autopause is GP-only (min 60 min, max 7 days)."
        },
        "IaaS Deployment (SQL Server on Azure VM)": {
          "What It Is": "SQL Server running on Azure Virtual Machines provides the most control and highest compatibility with on-premises SQL Server. The Azure platform manages the hypervisor and hardware, while you manage the VM, OS, SQL Server, and all configuration. The SQL Server IaaS Agent Extension is automatically installed when deploying from Marketplace and provides automated backup, patching, Key Vault integration, Defender for Cloud, disk utilization views, flexible licensing, and version/edition changes.",
          "VM Families and Storage": "**VM Families:** General Purpose (balanced CPU/memory), Compute Optimized (high CPU), Memory Optimized (database workloads, up to 4 TB RAM), Storage Optimized (NVMe, ephemeral), GPU, FPGA Accelerated, High Performance Compute.<br><br>**Storage Best Practices:** Data files on Premium SSD or Ultra Disk with separate pool and read-caching enabled. Log files on separate pool with NO read-caching. TempDB on temporary disk (D:) for low latency, or own pool. Backups can use Standard storage. OS disk should be minimum needed with no database files. Use Storage Spaces to pool disks for increased IOPS and striping.<br><br>**Data Compression:** Page compression (superset of row compression, ~72% fewer reads), Row compression (basic), Columnstore archival XPRESS (cold data). Use sp_estimate_data_compression_savings to estimate savings before implementing.<br><br>**Table Partitioning:** partition function → partition scheme → table; enables partition elimination and targeted maintenance.",
          "HA and DR for IaaS": "**Availability Set:** 99.95%, spread across fault/update domains, same datacenter.<br>**Availability Zone:** 99.99%, 3 zones per region, separate datacenters.<br>**Always On AG:** Up to 9 replicas, sync commit (low latency, same region) or async commit (cross-region), unit of failover = database group.<br>**FCI:** Unit of failover = entire instance, requires shared storage (S2D or file share), HA only within single region — NOT a DR solution.<br>**Azure Site Recovery:** VM-level block replication, best for stateless workloads, higher RPO for SQL Server.<br>**Native Backups:** To URL (Blob Storage), GRS/RA-GRS for geo-redundancy.",
          "Licensing Options for IaaS": "PAYG: Marketplace image, pay per minute. BYOL: blank VM + manual SQL install or AHB option. Azure Hybrid Benefit: apply existing Windows Server + SQL Server SA licenses. Reserved Instance: 1-3 year commitment. Flexible Licensing via Agent Extension: toggle between PAYG and BYOL without redeployment.",
          "Exam Gotchas": "Ephemeral storage (temporary disk D:\\) is NOT durable — data lost on reboot/maintenance; use only for TempDB, page files, swap. Ultra Disk requires special configuration different from Premium SSD. Always On AG synchronous commit requires low latency between replicas (same region); cross-region must use async. FCI is NOT a DR solution — it provides HA only within a single region; needs AG or log shipping for DR. Azure Site Recovery for SQL Server results in higher RPO; not recommended for transactional DBs without supplementary measures. Storage Spaces pools disks to increase IOPS — essential for production workloads. Page compression is superset of row compression. Query Store, instant file initialization, lock pages in memory, optimized for adhoc workloads are all recommended production settings."
        },
        "PaaS Deployment — Azure SQL Database": {
          "What It Is": "Azure SQL Database is a fully managed PaaS relational database service built on the SQL Server engine. It provides automatic backups, patching, high availability, and built-in intelligence. Available in single database and elastic pool deployment models with DTU or vCore purchasing.",
          "Purchasing Models and Service Tiers": "**DTU Model** (bundled compute+storage): Basic (light, 2 GB), Standard (moderate, 250 GB), Premium (intensive, 4 TB, local SSD, In-Memory OLTP).<br><br>**vCore Model** (decoupled compute/storage): General Purpose (4 TB, Premium remote storage, higher latency, provisioned or serverless), Business Critical (4 TB, local SSD, lowest latency, In-Memory OLTP, readable replica), Hyperscale (100 TB+, Premium storage, fast snapshots, read-scale, unlimited size).<br><br>**Serverless:** Autoscales between min/max vCores (0.5-16), autopause delay 1hr-7 days (or disabled), billed per second for compute, only storage when paused. NOT compatible with geo-replication, LTR backup, elastic jobs job DB, SQL Data Sync sync DB. Auto-pause only available in General Purpose tier.<br><br>**Elastic Pools:** Shared resource pool across databases for multitenant SaaS with low avg utilization. Min/max DTU or vCore per database. Monitor for noisy neighbors.",
          "Backup, Restore, and Geo-Replication": "**Automatic backups:** Full (weekly), Differential (12h), Log (5-10 min). Default retention 7 days (configurable 1-35 days for vCore). LTR up to 10 years (disabled by default). Geo-redundant RA-GRS by default.<br><br>**Restore:** PITR within retention window to same server; geo-restore to any Azure region. Cannot restore over existing DB — must drop or rename first. No T-SQL RESTORE command. No manual COPY_ONLY backups.<br><br>**Geo-replication:** Up to 4 readable async secondaries (same or different region), manual failover only.<br><br>**Failover Groups:** Built on geo-replication; provides read-write and read-only listener endpoints; no connection string changes on failover; automatic or manual failover.",
          "Elastic Features and Automatic Tuning": "**Elastic Query:** T-SQL across multiple databases using three/four-part names; supports vertical partitioning (different schemas) and horizontal partitioning/sharding (same schema).<br><br>**Elastic Jobs:** SQL Agent replacement for SQL Database; runs T-SQL across multiple targets; cross-subscription/region; parallel execution.<br><br>**Automatic Tuning:** ML-based identification of index opportunities; creates indexes, drops unused/duplicate indexes, forces last good execution plan; tests indexes on a DB copy first before applying. Enabled at server level, inherited by databases.",
          "Hyperscale Details": "Independent scaling of compute and storage (storage auto-grows, no max). Instant backups (file snapshots) — not dependent on data size. Fast restores in minutes regardless of size. Multiple read-scale replicas (ApplicationIntent=ReadOnly). CANNOT revert to standard service tier after conversion. Rapid scale up/down in seconds/minutes.",
          "Exam Gotchas": "Default backup retention: 7 days; can increase to 35 days for vCore. Hyperscale CANNOT be reverted to General Purpose or Business Critical. Serverless pause only in GP tier — Hyperscale serverless exists but auto-pause is GP-only. Elastic jobs replace SQL Agent for SQL Database (Managed Instance still has SQL Agent). Automatic tuning is enabled at server level and inherited by databases; can disable per database. DTU model is simpler but less flexible — storage bound to compute. Read-scale replicas in Business Critical: one free readable secondary; Hyperscale can have more. Scaling operation ends with brief connection interruption — implement retry logic. Firewall rules at server level; can also set at database level with contained DB users."
        },
        "PaaS Deployment — Azure SQL Managed Instance": {
          "What It Is": "Azure SQL Managed Instance is a fully managed SQL Server instance in the cloud, offering near 100% compatibility with on-premises SQL Server. It provides the benefits of PaaS (auto backups, patching, HA) while preserving instance-scoped features (SQL Agent, CLR, cross-DB queries, Service Broker, system DBs) needed for most existing applications. Supports up to 100 databases per instance.",
          "Service Tiers and Network": "**General Purpose:** Premium remote storage, higher latency, storage replication HA. **Business Critical:** Local SSD, lowest latency, Always On AG replicas HA, In-Memory OLTP, readable replica. BC max 16 TB, GP max 8 TB.<br><br>**Network:** Deployed in dedicated VNet subnet — private IP only by default. Public endpoint optional (port 3342, requires PowerShell enable by DBA + NSG port open by NetAdmin — Separation of Duties). On-prem connectivity via VPN Gateway (P2S/S2S) or ExpressRoute. DNS zone must match between primary and secondary in failover groups.",
          "Managed Instance Link": "Based on Distributed Availability Groups (DAG). One link per database. One-way replication: SQL Server 2016/2019. Two-way replication: SQL Server 2022 (online failover, offline failback currently). Hybrid uses: DR (failover to cloud), offload read-only workloads, automated backups in Azure. Cutover in seconds. No SQL version/edition restrictions beyond 2016+ Enterprise/Standard/Developer. Does NOT support Filestream/Filetable.",
          "Instance Pools": "Pre-provision compute resources shared across multiple instances. Fast deployment (up to 10 min). All instances share same VM. Cost-efficient for migrating small SQL Server instances.",
          "Backups and Restore (MI-Specific)": "Same automatic schedule as SQL Database (full weekly, diff 12h, log 5-10 min). Supports COPY_ONLY backup to URL (SQL Database does NOT). Supports T-SQL RESTORE from URL (but not local storage). Cannot overwrite existing database during restore. Must disable TDE for user-initiated COPY_ONLY backups. Restore supports: FILELISTONLY, HEADERONLY, LABELONLY, VERIFYONLY. Cannot restore backups with multiple log files, multiple backup sets, or In-Memory/FILESTREAM.",
          "Comparison with SQL Database": "SQL Agent: MI = yes, SQL DB = no (elastic jobs). CLR: MI = yes, SQL DB = no. Cross-DB queries: MI = native, SQL DB = elastic query. System DBs: MI = accessible, SQL DB = no. T-SQL RESTORE: MI = yes, SQL DB = no. COPY_ONLY backup: MI = yes, SQL DB = no. Service Broker: MI = yes, SQL DB = no. DTU model: MI = no, SQL DB = yes. Elastic pools: MI = no, SQL DB = yes. Hyperscale: MI = no, SQL DB = yes.",
          "Exam Gotchas": "SQL Agent exists in Managed Instance — elastic jobs are NOT available. COPY_ONLY backup to URL is NOT supported by SQL Database; Managed Instance only. T-SQL RESTORE is available only in Managed Instance (not SQL Database). Public endpoint port: 3342 (not 1433). Instance pools share same VM across instances — good for small DB consolidation. Link feature uses DAG (not log shipping); one link per database. DTU model is NOT supported by Managed Instance — vCore only. Failover groups require matching DNS zones between primary and secondary. Cross-DB queries work natively in MI; SQL DB needs elastic query. Elastic pools do not exist in MI — each instance has dedicated resources."
        },
        "Migration to Azure SQL": {
          "What It Is": "Migrating SQL Server workloads to Azure involves choosing between offline methods (full downtime) and online methods (minimal downtime). The right migration path depends on your target platform (SQL Database vs Managed Instance) and business requirements for downtime tolerance. Assess source databases first using Azure Migrate, DMA, or Azure Arc (automatic weekly assessments, trigger-on-demand, readiness reports with right-sized target recommendations).",
          "Migration to Azure SQL Database": "**Offline methods:** DMS (recommended for large migrations, supports table selection, use Azure CLI/PowerShell), BACPAC/SqlPackage (compressed file, faster than portal import, scale up target tier during import), BCP (table-level export/import), Azure Data Factory (data migration), portal Import Wizard (simple UI, slower than SqlPackage).<br><br>**Online method:** Transactional replication is the ONLY online method for SQL Database. Push subscriber only. Configure from SSMS/T-SQL (not portal). Replication components: Publisher, Subscriber, Distributor, Article, Publication, Subscription.<br><br>Schema must be deployed to target before data migration. Scale up target SKU during migration, scale down after. Enable retry logic: first retry after 5s, exponential backoff to 60s max; new connection for SELECT retries.",
          "Migration to Azure SQL Managed Instance": "**Online methods:** Managed Instance Link (DAG-based, seconds cutover, SQL 2016+, best for business-critical, supports reverse migration), Log Replay Service/LRS (log shipping tech, more control, 30-day limit, useful when DMS can't be used), Azure Arc (portal-based, unified assessment→target→migrate→monitor, built-in Copilot), Transactional replication (MI can be publisher/distributor/subscriber).<br><br>**Offline methods:** Native backup/restore (backup to URL, restore to MI, COPY_ONLY for user backups), BACPAC/SqlPackage (NOT supported via portal, use SqlPackage CLI directly).<br><br>Link vs LRS: Link has seconds cutover, read during migration, SQL 2016+, unlimited duration, reverse migration. LRS has longer cutover, no read during migration (restoring state), SQL 2012+, all editions, public endpoint OK, max 30 days, no reverse migration.",
          "Performance Recommendations": "Monitor and mitigate source data file I/O latency. Scale up target (BC Gen5 8 vCore or Hyperscale recommended). Ensure adequate network bandwidth for max log ingestion rate. Choose highest service tier during migration, scale down after. Minimize distance between BACPAC files and target region. Disable auto update/auto create statistics during migration. Partition tables and indexes; drop indexed views; recreate after migration. For DMS: up to 10 concurrent DB migrations per self-hosted IR; scale out IR for more concurrency.",
          "Connectivity for Hybrid": "Point-to-Site VPN: encrypted, moderate latency, low cost. Site-to-Site VPN: encrypted, moderate latency, moderate cost. ExpressRoute: private (not over internet), lowest latency, highest cost.",
          "Exam Gotchas": "Transactional replication is the ONLY online migration for SQL Database — all other methods are offline. Managed Instance Link uses DAG (not log shipping like LRS). LRS has a 30-day limit — automatically canceled after 30 days. COPY_ONLY backup only on Managed Instance, not SQL Database. BACPAC import via portal NOT supported for Managed Instance — use SqlPackage CLI. Remove database before restore — cannot restore over existing DB in either SQL DB or MI. Link does NOT support Filestream/Filetable. DMS recommended for large migrations — use Azure CLI for automation. Migration statuses: Preparing for copy → Copying → Copy finished → Rebuilding indexes → Succeeded. Retry logic required: first retry after 5s, exponential backoff to 60s. Azure Arc migration discovery runs automatically every weekend; can trigger manually."
        }
      }
    },
    "Module 2": {
      "topics": {
        "Authentication and Authorization": {
          "What It Is": "Azure SQL offers multiple authentication options (SQL Auth, Microsoft Entra ID, Windows Auth) and a hierarchical authorization model spanning Azure RBAC, server-level principals, database users, and object permissions. Security is managed through logins, users, roles, and permissions at both the server and database scopes.",
          "Authentication Options": "**SQL Server Authentication:** Login/password stored in SQL Server. Supported by all Azure SQL offerings.<br><br>**Microsoft Entra ID Authentication:** More secure, supports MFA (push notification, text, access code). Best practice: make the admin a Microsoft Entra *group* (not single user). Use Universal Authentication with MFA in SSMS.<br><br>**Windows Authentication:** Only on SQL Server and SQL Server on Azure VM (not SQL Database or Managed Instance).<br><br>**Azure RBAC (Resource Level):** SQL DB Contributor (manage DBs, cannot read data), SQL Security Manager (manage security policies, cannot access data), SQL Server Contributor (manage servers/DBs, cannot access data). RBAC is decoupled from database-level SQL permissions.",
          "Security Principals and Roles": "**Logins:** Server-level in `master` database. New logins can be added but new server roles cannot be created in Azure SQL Database.<br><br>**Users:** Database-level. Can be mapped to a login or created as contained users (recommended for Azure SQL DB).<br><br>**Database Roles:** db_owner (full admin), db_datareader (read all), db_datawriter (write all), db_ddladmin (modify objects), db_securityadmin (grant permissions), db_backupoperator (no effect in Azure SQL DB). DENY always overrides GRANT.<br><br>**Master DB Roles (Azure SQL only):** loginmanager (create logins), dbmanager (create/delete databases).<br><br>**Server Roles (SQL Server/MI):** sysadmin, serveradmin, securityadmin (treat as sysadmin), processadmin, setupadmin, bulkadmin, diskadmin, dbcreator.",
          "Object Permissions and Ownership Chains": "**Permissions:** SELECT, INSERT, UPDATE, DELETE on tables/views. CONTROL (full rights), EXECUTE (procedures/functions), ALTER (change definition), VIEW DEFINITION, REFERENCES (view FK).<br><br>**Ownership Chains:** If a stored procedure has the same owner as the tables it accesses, the user only needs EXECUTE on the procedure — they inherit table access during execution.<br><br>**Dynamic SQL breaks ownership chains** — user needs direct permissions on objects accessed via dynamic SQL because it executes outside the stored procedure context.<br><br>**Application Roles:** Activated by password (not membership). Permissions apply until deactivated.<br><br>**Principle of Least Privilege:** Users and applications should only have the minimum permissions needed.",
          "Transient Faults and Retry Logic": "Transient faults occur during reconfiguration, usually <60 seconds. Retry logic: first retry after 5 seconds, exponential backoff to 60 seconds max. SELECT failures must be retried in a *new connection* — do not retry in the same connection.",
          "Exam Gotchas": "Contained database users are the recommended pattern for Azure SQL Database (not logins in master). db_backupoperator has no effect in Azure SQL Database — only in SQL Server and MI. securityadmin server role should be treated as equivalent to sysadmin. Dynamic SQL breaks ownership chains — users need direct table permissions. DENY always overrides GRANT. RBAC roles manage Azure resource operations, not database access."
        },
        "Data Encryption (TDE, Always Encrypted, TLS)": {
          "What It Is": "Azure SQL provides multiple encryption layers: Transparent Data Encryption (TDE) for data at rest, Always Encrypted for client-side column encryption, and TLS for data in transit. Each protects against different threats and serves different compliance requirements.",
          "Transparent Data Encryption (TDE)": "Encrypts data at rest at the *page level* — data encrypted when written to disk, decrypted when read into memory. Does NOT encrypt at column/table level. Protects against restoring backups to unsecured servers or copying database/log files.<br><br>**Auto-enabled:** Azure SQL DB (post-May 2017), Azure SQL MI (post-Feb 2019). For older DBs, must be manually enabled.<br><br>**On-premises/VM setup:** Create master key → Create certificate in master → Create database encryption key → Enable encryption (`ALTER DATABASE ... SET ENCRYPTION ON`). Certificate must be manually backed up. For Always On AG: certificate must be restored to all replicas.<br><br>**Key types:** Service-managed key (Microsoft-provided) vs Customer-managed key/BYOK (via Azure Key Vault). If CMK is removed from AKV, database connections are closed and access is denied. Automatic key rotation: server checks AKV every 60 minutes.",
          "Always Encrypted": "Encrypts data *within the client application* — protects from high-privileged users (DBAs, cloud admins). Uses two keys: Column Master Key (CMK) and Column Encryption Key (CEK).<br><br>**Deterministic encryption:** Same value → same ciphertext — supports equality, joins, grouping, indexing.<br><br>**Randomized encryption:** More secure — same value → different ciphertext each time — only supports returning in results. Cannot change encryption type after creation.<br><br>Application needs: Always Encrypted driver + `Column Encryption Setting=enabled` in connection string. Use `SqlCommandColumnEncryptionSetting` to minimize metadata lookups.<br><br>**Secure Enclaves:** Secured region of memory in SQL Server process — enables pattern matching, comparison, and indexing on randomized encrypted columns. Appears as a black box — no data/code visible even with debugger.",
          "TLS and Encrypted Connections": "Transport Layer Security encrypts data in transit. Certificate requirements: local computer certificate store, SQL Server service account must have access (or restart fails), within valid period. Configure via SQL Server Configuration Manager: Certificate tab → select cert, Flags tab → ForceEncryption = Yes. Test in SSMS: Connection Properties → Encrypt connection.",
          "SQL Injection and Key Vault": "**SQL Injection:** Caused by dynamic SQL with unsanitized user input. Prevent: validate input, use parameterized queries. Advanced Threat Protection provides an extra layer.<br><br>**Azure Key Vault:** Stores secrets/certificates/keys. Has its own RBAC — subscription admin does NOT automatically have access. SQL Server supports AKV for TDE, Backup Encryption, and Always Encrypted. Configuration: create credential → create asymmetric key in AKV → create asymmetric key in DB using `FROM PROVIDER`.",
          "Exam Gotchas": "TDE encrypts at the page level, not column level. Always Encrypted encrypts in the client application. TDE is auto-enabled for Azure SQL DB (post-May 2017) and MI (post-Feb 2019). Customer-managed key removal closes all database connections and denies access. Always Encrypted keys must never be generated on the database server. Deterministic encryption supports equality/joins/indexing; randomized does not. Dynamic SQL breaks ownership chains. For TLS: missing service account access to certificate causes SQL Server restart to fail. AKV has its own RBAC separate from subscription RBAC."
        },
        "Firewall, Network Security and Private Link": {
          "What It Is": "Azure SQL provides network security through server-level and database-level firewall rules, Virtual Network service endpoints, and Private Link for private connectivity. These layers control which IP addresses, VNets, and networks can connect to Azure SQL resources.",
          "Firewall Rules": "**Server-level:** Allow connections to all databases on the server. Configured via Azure portal or `sp_set_firewall_rule` in master. The 'Allow Azure Services' setting counts as a single firewall rule.<br><br>**Database-level:** Grant/block specific IPs per database. Configured via `sp_set_database_firewall_rule` T-SQL only (in user database).<br><br>**Connection flow:** Checks database-level rule first → if no match, checks server-level rules. If neither exists and connecting via SSMS, user is prompted to create a rule.",
          "Virtual Network Endpoints and Private Link": "**VNet Endpoints:** Allow traffic from a specific Azure VNet. Apply at server level only. Service endpoint applies to one region only (the endpoint's region). VNet must have outbound access to the database's public IP via service tags.<br><br>**Private Link:** Connect using a private endpoint — traffic over Azure backbone, not public internet. Provides private IP on VNet. Supports ExpressRoute. Benefits: cross-region connectivity, protection against data leakage.",
          "Exam Gotchas": "Server-level firewall rules can be configured via portal or T-SQL (sp_set_firewall_rule in master). Database-level firewall rules are T-SQL only (sp_set_database_firewall_rule in user database). Firewall checks database-level rules first, then server-level. VNet service endpoints apply to only one region. Private Link provides a private IP on VNet and keeps traffic off the public internet."
        },
        "Compliance Controls (Auditing, Classification, Masking, RLS)": {
          "What It Is": "Azure SQL provides compliance controls including data classification, auditing, dynamic data masking, and row-level security. These features help meet regulatory requirements by identifying sensitive data, tracking access, obfuscating data, and restricting row-level access.",
          "Data Classification": "Performed per column using sensitivity labels and information types. Stored in `sys.sensitivity_classifications` (SQL Server 2019+, Azure SQL DB, MI). Classification engine scans based on column *names* — a column named `column1` containing emails would NOT be auto-detected.<br><br>Configure via: Azure portal (Data Discovery & Classification), SSMS sensitivity wizard, or T-SQL `ADD SENSITIVITY CLASSIFICATION TO ... WITH (LABEL='PII', INFORMATION_TYPE='Email')`. Customize taxonomy in Microsoft Defender for Cloud — only users with admin rights on root management group can manage labels.",
          "Server and Database Audit": "Tracks database events to: Azure Storage account, Log Analytics workspace, or Event Hubs. Server-level policy covers all databases. Best practice: enable only server-level unless a specific database needs different settings.<br><br>**Default groups:** BATCH_COMPLETED_GROUP, SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP, FAILED_DATABASE_AUTHENTICATION_GROUP. Read-Only replicas are automatically audited. Audit includes `data_sensitivity_information` field when combined with classification. May skip events during high activity.",
          "Dynamic Data Masking": "Obfuscates data at the presentation layer. Unmasked data visible to high-privileged users with UNMASK permission.<br><br>**Functions:** default() — XXXX/0/01.01.1900; partial(0,\"XXXX-XXXX-XXXX-\",4) — credit card; email() — aXXX@XXXXXXX.com; random(1,12) — random number; partial(1,\"XXXXXXX\",0) — custom string.<br><br>SELECT INTO / INSERT INTO from masked columns copies masked data. Export by user without UNMASK creates masked data. Masked data can be identified via inference — combine with other security features.",
          "Row-Level Security (RLS)": "Restricts rows based on group membership/authorization context — equivalent to a WHERE clause. Uses inline table-valued function with SCHEMABINDING + security policy.<br><br>**Filter predicates:** Restrict SELECT, UPDATE, DELETE (INSERT is N/A). **Block predicates:** Restrict AFTER INSERT, AFTER UPDATE, BEFORE UPDATE, BEFORE DELETE.<br><br>Create flow: Create users → Create inline TVF → Create security policy → Assign predicate. Risk of side-channel attacks via divide-by-zero — limit unplanned queries. Best practice: separate schema for predicates, avoid type conversions, avoid excessive joins.",
          "Exam Gotchas": "Data classification is based on column names — may miss poorly named columns. Only root management group admins can manage sensitivity labels. Best practice: enable only server-level auditing unless a specific database needs different settings. Dynamic Data Masking works at the presentation layer — data is still stored unencrypted. RLS requires inline TVF with SCHEMABINDING + CREATE SECURITY POLICY. RLS filter predicates affect SELECT, UPDATE, DELETE. Block predicates affect INSERT and UPDATE. Side-channel attacks possible with RLS."
        },
        "Defender for SQL, Ledger and Purview": {
          "What It Is": "Microsoft Defender for SQL provides vulnerability assessment and threat protection. Ledger provides tamper-evidence via cryptographic hashing. Microsoft Purview provides unified data governance, automated scanning, classification, and lineage across the data estate.",
          "Microsoft Defender for SQL": "Includes SQL vulnerability assessment + Advanced Threat Protection. Vulnerability assessment uses a knowledge base of security rules — flags misconfigurations, excessive permissions, exposed sensitive data. Must enable at subscription level (recommended). Requires a storage account.<br><br>**Advanced Threat Protection alerts:** Vulnerability to SQL injection, Potential SQL injection, Access from unusual location/data center, Access from unfamiliar principal, Access from potentially harmful application, Brute force SQL credentials.<br><br>To manage settings: must be in SQL security manager role or database/server admin role. Recommended audit groups: BATCH_COMPLETED_GROUP, SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP, FAILED_DATABASE_AUTHENTICATION_GROUP.",
          "Ledger": "Tamper-evidence using cryptographic hashing (SHA-256) — each transaction cryptographically linked like a blockchain.<br><br>**Updatable ledger tables:** For INSERT/UPDATE/DELETE apps — uses system-versioned history table to track changes.<br><br>**Append-only ledger tables:** For insert-only apps (accounting, SIEM) — blocks all UPDATE/DELETE at the API level.<br><br>Enable ledger only during database creation — cannot modify afterward. Setting 'Enable for all future tables' makes all tables ledger tables. Can also enable per-table with `LEDGER = ON` in CREATE TABLE.",
          "Microsoft Purview": "Unified data governance — automated discovery, classification, and lineage across on-premises, multicloud, SaaS.<br><br>**Scanning auth:** System-assigned managed identity (recommended, not for self-hosted IR), User-assigned managed identity (preview, not for self-hosted IR), Service Principal (has expiration), SQL Authentication. Self-hosted IR requires service principal or SQL authentication.<br><br>**Firewall options:** Allow Azure connections, self-hosted IR, managed virtual network.<br><br>**Required roles:** Data Source Administrator + Data Reader to register and manage sources.<br><br>**Data lineage:** Extracted from stored procedure runs. Enable lineage extraction toggle in scan setup. Runs incremental scans every 6 hours.",
          "Exam Gotchas": "Ledger can only be enabled during database creation — cannot be added later. Append-only ledger tables block UPDATE and DELETE at the API level. Updatable ledger tables use system-versioned history. Managed identities do NOT work with self-hosted IR for Purview — use service principal or SQL auth. Vulnerability assessment requires enabling Defender for SQL at subscription level. ATP recommended audit groups: BATCH_COMPLETED, SUCCESSFUL_DATABASE_AUTHENTICATION, FAILED_DATABASE_AUTHENTICATION. Purview lineage extraction runs every 6 hours. Data Source Administrator + Data Reader roles required for Purview source registration."
        }
      }
    },
    "Module 3": {
      "topics": {
        "Performance Monitoring and Tuning": {
          "What It Is": "Azure provides multiple monitoring tools (Azure Monitor, Perfmon, Extended Events, Query Performance Insight, Database Watcher) to track performance metrics, identify bottlenecks, and tune database and server performance. Establishing baselines and correlating OS metrics with SQL Server metrics is critical for proactive performance management.",
          "Azure Monitor and Metrics": "Azure Monitor collects standard metrics (CPU, network, disk R/W). Active data retained for **93 days**; can archive to Azure Storage. **Azure Monitor Insights** provides extra data points (storage latency, memory) stored in **Log Analytics workspace** (queried via KQL).<br><br>**Metric Alerts:** Static (fixed threshold) or Dynamic Thresholds (learns historical behavior, detects seasonality). **Action groups:** Automation Runbook, Azure Function, Email/SMS/Push/Voice, ITSM, Logic App, Webhook, Secure Webhook.<br><br>**Critical SQL Server counters:** % Processor Time, Avg. Disk sec/Read/Write (<20ms, Premium SSD <10ms), Processor Queue Length (>0 = CPU pressure), Page Life Expectancy (sudden drops indicate issues), Batch Requests/sec, SQL Compilations/Recompilations/sec. **Wait statistics** via sys.dm_os_wait_stats identify bottlenecks.",
          "Extended Events": "Lightweight monitoring, successor to Profiler. **Channels:** Admin, Operational, Analytic, Debug (Microsoft support only). **Targets:** Event Counter (sync, count occurrences), Event File (async, persists to blob), Ring Buffer (async, in-memory circular), ETW (sync, correlates with OS), Histogram (async, counts by column), Event Pairing (async, matches paired events).<br><br>Filters apply to **a single field on a single event** — need separate filters per event. Causality tracking adds GUID + sequence number. Sessions created via SSMS, templates, or T-SQL `CREATE EVENT SESSION`. Can be scoped to server or database.",
          "Query Performance Insight and Database Watcher": "**Query Performance Insight:** Found under Intelligent Performance in Azure SQL DB. Filters: Long Running Queries, Top Resource Consuming Queries, Custom. Metrics: CPU, Data IO, Log IO, memory. Query IDs correlate to Query Store. Does NOT show execution plans.<br><br>**Database Watcher (Preview):** For Azure SQL DB and MI. Collects data into Azure Data Explorer or Real-Time Analytics (Fabric). Configurable targets, datasets, frequency, retention. Low latency (seconds). Supports parameterized alert templates.",
          "Exam Gotchas": "Azure Monitor retains metrics for 93 days. Extended Events filters apply to a single field on a single event. Most targets are async; Event Counter and ETW are sync. Query Performance Insight does NOT show execution plans. Database Watcher stores data in Azure Data Explorer or Real-Time Analytics. Wait statistics available across all Azure SQL platforms. db_backupoperator has no effect in Azure SQL DB."
        },
        "Resource Configuration (Storage, VM, TempDB, Resource Governor)": {
          "What It Is": "Proper configuration of Azure storage, VM sizing, TempDB, and Resource Governor is essential for optimal SQL Server performance. Each component has specific best practices for balancing cost, performance, and resource allocation.",
          "Azure Storage for SQL Server": "**Blob Storage:** Object-based, used for backups (BACKUP TO URL). **File Storage:** File share for FCI. **Managed Disks:** Ultra Disk (sub-ms, mission-critical), Premium SSD (single-digit ms, production), Standard SSD (dev/test), Standard HDD (backups).<br><br>**Best practices:** Separate volumes for data (read-cache ON) and log (NO cache). Plan extra 20% IOPS. Use D: drive for TempDB. Enable instant file initialization. Move trace/error logs to data disks. **Striping with Storage Spaces:** Sums IOPS/volume, no redundancy (Azure provides 3x). Ultra Disk scales independently — no striping needed.",
          "VM Sizing and Constrained Cores": "**Constrained cores:** Reduce vCPU count while keeping full memory/storage/I/O — reduces licensing cost for non-CPU-intensive workloads.<br><br>**VM resizing:** Requires restart; may need deallocation depending on source/target type.<br><br>**TempDB:** Proportional fill distributes data by file size. SQL Server: up to 8 files, match CPUs for heavy workloads. Azure SQL DB: scales with vCores (2 vCores = 4 files), max 16, NOT configurable via T-SQL. SQL MI: always 12 files. TempDB always on local SSD. MIXED_PAGE_ALLOCATION=OFF, AUTOGROW_ALL_FILES=ON (defaults not configurable). Metadata optimization (SQL 2019) NOT available in Azure SQL.",
          "MAXDOP and Resource Governor": "**MAXDOP:** Higher = more parallel threads, faster but more memory pressure. Configure via DB scoped config, sp_configure (MI), query hints, Resource Governor (MI).<br><br>**Resource Governor (SQL Server + SQL MI only):** Granular control over CPU, I/O, memory. Components: Resource pools (min/max CPU%, memory%, IOPs, NUMA affinity), Workload groups (classified by function), Classifier function (runs at connection time). Changes only affect NEW sessions (except external pools for ML). All pool settings except min/max CPU% are hard limits. CPU min/max only applies during contention.",
          "Exam Gotchas": "Ultra Disk scales independently — no striping needed. Premium SSD benefits from striping; don't configure redundancy. Constrained cores reduce vCPU count while keeping full memory/I/O. TempDB in Azure SQL DB scales with vCores (max 16), MI always has 12. TempDB metadata optimization NOT available in Azure SQL. Resource Governor NOT available in Azure SQL Database. Pool changes only affect new sessions. Classifier function runs at connection time. MAXDOP configurable via DB scoped config, sp_configure (MI), query hints, or Resource Governor (MI)."
        },
        "Database Optimization (Indexes, Statistics, Auto Tuning, IQP)": {
          "What It Is": "Ongoing database maintenance (indexes, statistics) combined with automatic tuning and Intelligent Query Processing features ensure optimal query performance. Azure SQL Database provides self-managing capabilities that reduce manual DBA intervention.",
          "Index Maintenance": "**Fragmentation:** Logical order ≠ physical order. Causes extra I/O.<br><br>**Reorganize** (online, leaf-level defrag, compacts by fillfactor): 5-30% fragmentation. Does NOT update statistics.<br><br>**Rebuild** (online or offline, drops/recreates): >30% fragmentation. Updates statistics. Online requires more space. Resumable rebuild: SQL 2017+. MAXDOP on resumable: SQL 2019+.<br><br>DMV for B-tree: sys.dm_db_index_physical_stats. Columnstore: sys.dm_db_column_store_row_group_physical_stats.",
          "Statistics and Maintenance Automation": "**Statistics:** BLOBs in user DB with data distribution info. AUTO_CREATE_STATISTICS=ON by default. Consider manual stats when: DTA suggests, multiple columns not in same index, subset queries, missing stats. View via sys.stats + sys.dm_db_stats_properties.<br><br>**Automation:** SQL Server VM = SQL Agent + Task Scheduler. Azure SQL DB = Azure Automation runbooks, remote SQL Agent, Elastic Jobs. SQL MI = SQL Agent.<br><br>**DB Scoped Config:** ALTER DATABASE SCOPED CONFIGURATION: MAXDOP, Legacy CE, Last Query Plan Stats (compat 150), Optimize for Ad Hoc. ALTER DATABASE: recovery model, auto tuning, auto create/update stats, Query Store, snapshot isolation. Compatibility level controls QO behavior.",
          "Automatic Tuning (Azure SQL DB)": "**Automatic plan correction (FORCE_LAST_GOOD_PLAN):** Engine forces last known good plan when regression detected. Plan reverts after 15 executions if not better. Conditions: previous plan had higher error rate, estimated CPU gain >10 seconds. Query Store must be enabled and Read-Write. Check via sys.dm_db_tuning_recommendations and sys.database_automatic_tuning_options.<br><br>**Automatic index management:** Azure SQL DB only. Creates/drops indexes based on workload. Monitors resources to avoid degradation. Dropped indexes recreated automatically if performance degrades.",
          "Intelligent Query Processing (Compat 150)": "**Adaptive Joins:** Defer join type (hash vs nested loops) based on actual rows, batch mode only.<br><br>**Interleaved Execution:** MSTVFs get actual row count before plan compilation (vs fixed 1/100 rows).<br><br>**Memory Grant Feedback:** Adjusts memory grant up/down based on actual usage.<br><br>**Table Variable Deferred Compilation:** TVFs get actual row count at first compilation (vs fixed 1 row).<br><br>**Batch Mode on Rowstore:** Batch processing without columnstore dependency.<br><br>**Scalar UDF Inlining:** UDFs transformed into subqueries for parallelism.<br><br>**Approximate Count Distinct:** APPROX_COUNT_DISTINCT — ~2% error rate at 97% confidence.",
          "Exam Gotchas": "Rebuild updates statistics; reorganize does NOT. Resumable rebuild: SQL 2017+. MAXDOP on resumable: SQL 2019+. Automatic plan correction forces after 15 executions of better query. Auto index management is Azure SQL DB only. Query Store must be Read-Write. Adaptive joins only in batch execution mode. Scalar UDF inlining enables parallelism. Approx Count Distinct: 2% error, 97% confidence. Legacy CE can be set per database while still using IQP at compat 140/150."
        }
      }
    },
    "Module 4": {
      "topics": {
        "Query Performance Optimization": {
          "What It Is": "SQL Server uses a cost-based query optimizer that generates execution plans based on statistics. Understanding query plans (estimated, actual, live), the Query Store, SARGability, parameter sniffing, and blocking/locking mechanics is essential for diagnosing and resolving query performance issues.",
          "Query Plans and Lightweight Profiling": "**Processing flow:** Parse → Algebrizer (binding) → Check plan cache (query_hash) → Optimize → Execute.<br><br>**Plan types:** Estimated (SET SHOWPLAN_ALL ON, no execution), Actual (SET STATISTICS PROFILE ON, includes runtime stats), Live Query Statistics (animated, graphical only, refreshes every 1s).<br><br>**Lightweight profiling:** ~2% overhead (vs legacy 75%). Default in SQL 2019+ and Azure SQL. Query-level: `OPTION(USE HINT ('QUERY_PLAN_PROFILE'))`. `LAST_QUERY_PLAN_STATS` DB scoped config or trace flag 2451 for last actual plan via `sys.dm_exec_query_plan_stats`.",
          "Query Store": "Per-database, enabled by default in Azure SQL DB. Three stores: Plan, Runtime Stats, Wait Stats. Key views: Regressed Queries, Overall Resource Consumption, Top Resource Consuming, Queries With Forced Plans, High Variation, Wait Statistics, Tracking Query. Plan forcing: SSMS or `sp_query_store_force_plan`. Automatic plan correction (FORCE_LAST_GOOD_PLAN) enabled by default for new Azure SQL DB.",
          "SARGability and Parameter Sniffing": "**SARGable predicates** allow index seeks. Non-SARGable: `LIKE '%term'`, functions on columns, implicit conversions. Missing indexes: Clustered Index Scan or Nonclustered Seek + Key Lookup. DMV: `sys.dm_db_missing_index_details`.<br><br>**Parameter sniffing:** First parameter value shapes cached plan. Solutions: `RECOMPILE` hint, `OPTIMIZE FOR UNKNOWN`, conditional recompile.<br><br>**Locking:** Lock escalation >5,000 rows → table lock. Deadlock victim = least work to roll back. Deadlocks in `system_health` XE session.",
          "Exam Gotchas": "Estimated plans do NOT execute. Live Query Statistics is graphical only. Lightweight profiling ~2% overhead vs legacy 75%. Lock escalation at 5,000 rows. Deadlock victim = least work to roll back. sys.dm_db_resource_stats snapshots every 15 seconds (Azure SQL DB only). Missing index DMVs are starting points, not a mandate."
        },
        "Performance-based Database Design": {
          "What It Is": "Database design decisions (normalization, data types, indexing strategy) profoundly impact performance. OLTP systems favor normalized designs minimizing transaction times, while data warehouses use denormalized star schemas for complex queries. Proper indexing and data type selection are critical.",
          "Normalization and Schemas": "**1NF:** Separate tables, no repeating groups, primary key. **2NF:** All attributes depend on complete composite key. **3NF:** No transitive dependencies. **Denormalization:** Tradeoff — fewer joins (faster reads) vs update anomalies.<br><br>**Star schema:** Denormalized dimensions, central fact table. Fewer joins, faster queries. **Snowflake schema:** Normalized dimensions. Saves storage, more joins.",
          "Index Types": "**Clustered:** Table data in sorted (logical) order, one per table. Keep key narrow, unique, selective.<br><br>**Nonclustered:** Separate structure, key + row pointer. Add included columns to cover queries.<br><br>**Filtered:** WHERE clause on index, ideal for bit columns with skewed distribution.<br><br>**Unique:** No duplicates. Auto-created for PK/UNIQUE constraints.<br><br>**Columnstore:** Column-based, batch execution mode (~900 rows). Bulk load min: 102,400 rows into compressed rowgroups. Smaller loads → delta store (b-tree) → tuple mover (async). Nonclustered columnstore for unsupported types (XML, CLR, sql_variant). Batch mode up to 5x improvement. Resumable index (SQL 2017+) only with ONLINE=ON.",
          "Exam Gotchas": "Clustered index = table data; heap = no clustered index. Columnstore bulk load min 102,400 rows — below that goes to delta store. Resumable index only with ONLINE=ON. Nonclustered columnstore needed for XML, CLR, sql_variant, ntext, text, image. Batch mode ~900 rows per batch. sys.index_resumable_operations for status. Filtered indexes ideal for bit columns."
        },
        "Evaluate Performance Improvements": {
          "What It Is": "Wait statistics, index tuning, query hints, and Azure SQL-specific DMVs form the toolkit for evaluating and improving performance. Understanding the running vs waiting dichotomy guides troubleshooting. Query Store hints allow plan shaping without code changes.",
          "Wait Statistics and Common Waits": "**Resource waits:** locks, latches, disk I/O. **Queue waits:** idle threads. **External waits:** linked server, network. DMVs: sys.dm_os_wait_stats (MI), sys.dm_db_wait_stats (SQL DB).<br><br>**Key waits:** RESOURCE_SEMAPHORE (memory), LCK_M_X (blocking), PAGEIOLATCH_SH (storage/missing indexes), SOS_SCHEDULER_YIELD (CPU), CXPACKET (parallelism), PAGEIOLATCH_UP 2:1:1 (TempDB contention). **Azure SQL:** LOG_RATE_GOVERNOR, POOL_LOG_RATE_GOVERNOR, INSTANCE_LOG_GOVERNOR. HADR_SYNC_COMMIT normal for Business Critical. RBIO* for Hyperscale.",
          "Query Hints and Query Store Hints": "**Query hints:** MAXDOP, RECOMPILE, OPTIMIZE FOR, OPTIMIZE FOR UNKNOWN, FAST, LOOP/MERGE/HASH JOIN, USE PLAN.<br><br>**Query Store hints** (sp_query_store_set_hints): Shape plans without modifying app code. Use cases: recompile, limit MAXDOP, force hash join, use compat level 110 for specific query.<br><br>**Azure SQL DMVs:** sys.dm_db_resource_stats (15s snapshots, SQL DB), sys.server_resource_stats (MI), sys.dm_user_db_resource_governance (SQL DB), sys.dm_instance_resource_governance (MI).",
          "Index Tuning and Performance Scenarios": "**Approach:** Evaluate existing usage (sys.dm_db_index_operational_stats, sys.dm_db_index_usage_stats) → eliminate unused → craft for expensive queries → test in nonproduction → implement via change control.<br><br>**Running vs Waiting:** High CPU = running (sys.dm_exec_requests, Query Store top consumers). Waiting = resources (wait stats, sys.dm_os_waiting_tasks).<br><br>**Worker limits:** SQL DB based on service tier. MI uses max worker threads (THREADPOOL waits if exceeded).",
          "Exam Gotchas": "sys.dm_db_resource_stats snapshots every 15 seconds (SQL DB only). sys.server_resource_stats for MI. CXPACKET = parallelism config issue. PAGEIOLATCH_UP on 2:1:1 = TempDB PFS contention — add files. Query Store hints don't require app code changes. Wait stats from instance startup. HADR_SYNC_COMMIT normal for BC tier. Log governance: LOG_RATE_GOVERNOR (SQL DB), POOL_LOG_RATE_GOVERNOR (elastic pool), INSTANCE_LOG_GOVERNOR (MI)."
        }
      }
    },
    "Module 5": {
      "topics": {
        "Automate Database Deployment": {
          "What It Is": "Azure offers multiple deployment models — declarative (ARM templates/Bicep) and imperative (PowerShell/Azure CLI). ARM templates are idempotent JSON documents that orchestrate resource creation order. Bicep provides a cleaner DSL that transpiles to ARM JSON (~60% less verbose). CI/CD via Azure Pipelines enables automated, consistent deployments.",
          "ARM Templates and Bicep": "**ARM templates (JSON):** Declarative, idempotent, orchestrated, modular, exportable from portal. Deploy to Resource Group, Subscription, Management Group, or Tenant. `New-AzResourceGroupDeployment -TemplateUri` (PS) / `az deployment group create --template-file` (CLI). Remote linked templates need SAS token in query-string for relative paths.<br><br>**Bicep:** Concise DSL, transpiles to ARM JSON. `param`, `var`, `resource` keywords. `parent:` for nested resources. Deploy: `New-AzResourceGroupDeployment -TemplateFile ./main.bicep`. Azure CLI cannot deploy remote Bicep directly — must transpile to JSON first.<br><br>**Source control:** Version ARM/Bicep files like application code. Quickstart templates available on GitHub.",
          "PowerShell and Azure CLI": "**PowerShell (Az.Sql):** Verb-noun syntax. `Get-AzSqlServer`, `New-AzSqlDatabase`, `New-AzSqlInstance` (requires SubnetId). Supports environments: PowerShellGet, Cloud Shell, Docker.<br><br>**Azure CLI:** `az <ref> <cmd> --params`. `az sql server create`, `az sql server firewall-rule create`. Cross-platform (Linux/Mac/Win), Cloud Shell, Docker.<br><br>**Comparison:** PS `Connect-AzAccount` vs CLI `az login`. PS `Get-AzSubscription` vs CLI `az account list`. PS `New-AzSqlServer` vs CLI `az sql server create`.",
          "CI/CD and Governance": "**Azure Pipelines:** Deploy ARM templates via PowerShell tasks or dedicated tasks. CI = frequent code changes, automated build/test. CD = automated delivery to infra.<br><br>**Azure Policy:** Region limits, naming standards, resource sizes. Applied at MG/Sub/RG. Grouped into initiatives.<br><br>**Resource tags:** Key-value pairs, up to 15 per resource. Include in billing for cost tracking. Stored as plain text — no sensitive values.",
          "Exam Gotchas": "ARM templates are idempotent. Bicep is ~60% less verbose than JSON. Azure CLI cannot deploy remote Bicep files directly. New-AzSqlInstance requires SubnetId. Tags stored as plain text — no secrets. Azure Policy can block deployment. Bicep transpiles to ARM JSON; not a general-purpose language."
        },
        "Create and Manage SQL Agent Jobs": {
          "What It Is": "SQL Server Agent schedules maintenance tasks like backups, integrity checks, index maintenance, and statistics updates. Maintenance Plans (SSIS packages) create workflows of tasks. Operators, notifications, and alerts enable proactive monitoring via Database Mail.",
          "Maintenance Plan Activities": "**Check DB Integrity:** DBCC CHECKDB. Must align with backup retention.<br><br>**Shrink Database:** NOT recommended for regular maintenance (causes fragmentation).<br><br>**Reorganize/Rebuild Index:** Based on fragmentation. Rebuild updates stats.<br><br>**Update Statistics:** Default sampling sufficient.<br><br>**Backup Database:** Full + Differential + Transaction Log. Restore flow: Full → most recent Diff → Logs since Diff.<br><br>**Cleanup History:** Removes old history from msdb.<br><br>**Maintenance Cleanup:** Removes old backup files (specified folders only, not subfolders).<br><br>Best practice: create separate plans per task type. Backup retention > consistency check window.",
          "Operators, Notifications, and Alerts": "**Operators:** Aliases for individuals/groups (use email distribution groups).<br><br>**Notifications:** Per-job: completion/success/failure. Best practice: notify only on failure.<br><br>**Alerts:** Based on error log (severity ≥ 16), performance conditions (CPU > 90%), or WMI events. Responses: email operator or execute another job.<br><br>Requires Database Mail enabled.",
          "Proxy Accounts and Multiserver": "**Proxy accounts:** Stored credentials for specific job steps (e.g., backup to network share).<br><br>**Job schedules:** Jobs ↔ Schedules = many-to-many. Stored in msdb.<br><br>**Multiserver:** Primary server distributes jobs to target servers. Define once, deploy everywhere.",
          "Exam Gotchas": "Shrink DB NOT recommended — causes fragmentation. Consistency check < backup retention window. Proxy accounts = credentials for specific steps. Jobs ↔ Schedules are many-to-many (msdb). Alerts can notify operator OR execute job. Operators: use email distribution groups. Maintenance Plans = SSIS packages. DBCC CHECKDB is the only way to check full database corruption."
        },
        "Manage Azure PaaS Tasks Using Automation": {
          "What It Is": "Azure SQL Database lacks SQL Agent, so alternatives are needed: Elastic Jobs (T-SQL scheduler for SQL DB), Azure Automation (PowerShell/Python runbooks), and Logic Apps (low-code workflows with connectors). Each has different capabilities and use cases.",
          "Elastic Jobs (Azure SQL DB)": "T-SQL only. Components: Job Agent, Job Database (S1+ recommended), Target Group (servers/pools/dbs), Job (T-SQL steps). Need credential in master for server/elastic pool targets. Least privileges for credentials. Scripts must be idempotent. Auto-retry on failure.<br><br>cmdlets: New-AzSqlElasticJobTargetGroup, Add-AzSqlElasticJobTarget, New-AzSqlElasticJob, Add-AzSqlElasticJobStep, Start-AzSqlElasticJob.<br><br>Monitor: portal, PowerShell (Get-AzSqlElasticJobExecution), T-SQL (jobs.job_executions).",
          "Azure Automation": "Runbooks: PowerShell or Python. Import modules (Az.SQL, Az.Accounts). Use system-managed identity (`Connect-AzAccount -Identity`) with RBAC permissions. Runbooks restart from beginning if interrupted.<br><br>**Hybrid runbooks:** Manage on-prem or Azure VMs.<br><br>**Monitoring:** Activity log (Get-AzLog, filter by `Microsoft.Automation/automationAccounts/jobs/write`). Metric alerts with action groups (email, webhook, runbook). Log Analytics (requires Diagnostic settings configured first).",
          "Logic Apps": "Prebuilt connectors (SQL Server, Office 365). SQL connector supports SQL Server, Azure SQL DB, Azure SQL MI. Triggers return only 1 row. Actions: Get row, Insert, Delete, Execute Query, Run stored proc.<br><br>Built-in connector (Standard): no triggers, only Execute Query. Connection string from portal.",
          "Exam Gotchas": "Elastic Jobs = T-SQL only, auto-retry. Job DB recommended S1 or higher. Target server needs credential in master. Runbooks restart from beginning if interrupted. Import Az.SQL module for SQL cmdlets. System identity needs RBAC. Tags: up to 15, plain text. Log Analytics for Automation needs Diagnostic settings configured. Logic Apps triggers return only 1 row. Built-in connector has no triggers. Azure CLI cannot deploy remote Bicep."
        }
      }
    },
    "Module 6": {
      "topics": {
        "HADR Strategies & Options": {
          "What It Is": "High Availability and Disaster Recovery (HADR) planning starts with defining RTO (max downtime) and RPO (max data loss). IaaS features (FCI, AG, Log Shipping) provide database-centric HA/DR. PaaS has built-in HA (99.99% SLA, ADR) plus active geo-replication and auto-failover groups. Azure platform features (AS, AZ, ASR) supplement SQL features.",
          "RTO, RPO, and HADR Options": "**RTO:** Max time to restore service. Defined at component + app level. Overall RTO = slowest component. **RPO:** Max acceptable data loss. Document and revise periodically. Separate RTO/RPO for HA (local, seconds) vs DR (cross-region, hours).<br><br>**IaaS features:** Always On FCI (instance, shared storage, no data loss, stop/start), Always On AG (database level, no shared storage, listener, readable secondaries), Log Shipping (backup/copy/restore, simplest).<br><br>**Azure platform:** Availability Sets (anti-affinity, 99.95%), Availability Zones (separate DCs, 99.99%), Azure Site Recovery (VM replication, ~2h RTO).",
          "PaaS HADR": "**Built-in HA:** 99.99% SLA, ADR on by default (can't disable), auto page repair. DB state cannot be OFFLINE or EMERGENCY.<br><br>**Active Geo-Replication (SQL DB only):** Async readable secondary, manual failover, same service tier. Cross-subscription available programmatically.<br><br>**Auto-Failover Groups (SQL DB & MI):** Listeners (R/W + R/O), automatic failover (configurable), GracePeriodWithDataLossHours (default 1h). MI supports one failover group only.",
          "Hybrid Solutions": "IaaS-based (PaaS limited). AG secondary in Azure. Requires AD DS + DNS + sufficient bandwidth. ExpressRoute or S2S VPN. Transactional replication on-prem publisher → MI subscriber.",
          "Exam Gotchas": "FCI = instance-level, no data loss, but full stop/start. AG = database-level, no shared storage. AS and AZ cannot be combined. ASR is not SQL-aware — may miss RPO. Active geo-replication = SQL DB only. MI = auto-failover groups only (one per MI). GracePeriodWithDataLossHours default 1h. DB state OFFLINE/EMERGENCY not supported in PaaS. ADR cannot be disabled."
        },
        "Implement IaaS & PaaS HADR": {
          "What It Is": "Deploying WSFC in Azure differs from on-prem: use PowerShell New-Cluster (not wizard), cloud witness recommended, ILB required for AG listeners. Distributed AGs span regions without cross-WSFC. Azure Site Recovery provides VM-level DR. Monitoring uses Azure Status, Service Health, DMVs, and CLI.",
          "WSFC in Azure": "**Cloud witness** recommended (WS 2016+). **Workgroup Cluster** (WS 2016+): AG only, no AD DS needed. **DTC** requires shared disk. IP configured in Azure (not inside VM — shows DHCP). Create with PowerShell `New-Cluster -StaticAddress`. **DNN** default in WS 2019+ for WSFC — no LB needed for FCI with DNN. `Test-Cluster` validates; warnings acceptable if expected.",
          "AG Configuration": "`Enable-SqlAlwaysOn` requires SQL restart. **ILB** required for listener connectivity. Standard LB for AZ. Each listener IP needs unique **probe port** (high port like 59999). Multi-subnet: ILB per subnet/region.<br><br>**Distributed AG** (Ent, SQL 2016+): AG of AGs. Global primary + forwarder. No WSFC between AGs. Each AG maintains own quorum.",
          "Azure Site Recovery Details": "**Mobility extension** on VM. Crash-consistent every 5 min. App-consistent configurable (VSS). Multi-VM consistency affects performance. **Test failover** without impacting production. After failover, replica VMs unprotected — must reprotect. Can protect against ransomware.",
          "Monitoring Availability": "**Azure Status:** Dashboard, RSS feed. **Azure Service Health:** Problems, maintenance, advisories, alerts via email/SMS. **Resource Health:** View unavailability reasons. `sys.dm_database_replica_states` for BC replicas. `az sql mi/db list`, `Get-AzSQLDatabase` for status. System Center Management Pack available.",
          "Exam Gotchas": "WSFC wizard cannot be used in Azure — use PowerShell. DNN default in WS 2019+ for FCI — no LB needed. ILB required for AG listener. Probe port unique per listener. Distributed AG = AG of AGs, Enterprise only. ASR mobility extension. Crash-consistent 5 min. Replicas unprotected after ASR failover. Cluster validation warnings acceptable if expected."
        },
        "Back Up and Restore Databases": {
          "What It Is": "SQL Server backup types: Full, Differential, Transaction Log. Recovery models: FULL, BULK_LOGGED, SIMPLE. Backup to URL uses Azure Blob (SAS for block blob). PaaS backups are automatic (Full weekly, Diff 12h, Log 5-10 min). MI supports COPY_ONLY backup to URL. ADR speeds recovery.",
          "Backup Types and Recovery Models": "**Full:** All pages. **Differential:** Pages since last full. **Log:** Granular PITR, clears log. Requires FULL recovery model. SIMPLE = no log backups, no PITR. COPY_ONLY: doesn't break log chain.<br><br>**Restore flow:** Full → most recent Diff → Logs since Diff (requires NORECOVERY). System DBs (master/msdb) shouldn't be restored across instances.",
          "Backup to URL (IaaS)": "Requires Azure Storage account + container. Path: `https://ACCOUNTNAME.blob.core.windows.net/ContainerName/File.bak`. **SAS** (block blob, preferred SQL 2016+, cheaper, better security). Access key (page blob).<br><br>**Automated backups** via IaaS Agent Extension: Windows-only. **Do not** combine with instance-level log backups (breaks log chain). Azure Backup: SQL-aware VSS backups.",
          "PaaS Backup & Restore": "**Automatic:** Full weekly, Diff 12h, Log 5-10 min. RA-GRS blobs. **PITR:** Default 7 days, max 35 days. LTR up to 10 years.<br><br>**Restore:** Creates new DB (cannot overwrite). Deleted DB restoreable to last available point. **Server deletion = all backups gone permanently.**<br><br>**MI-only:** COPY_ONLY backup to URL. T-SQL RESTORE from URL. Cannot restore MI backups to SQL DB.",
          "Accelerated Database Recovery (ADR)": "Enabled by default in Azure SQL — **cannot be disabled**. Persisted Version Store (PVS) + aggressive log truncation. Instant transaction rollback. Also available in SQL Server 2019+.",
          "Exam Gotchas": "PaaS restore = new DB, cannot overwrite. Server deletion = backups gone forever. COPY_ONLY = MI only. ADR on by default, cannot be disabled. Block blob only from SQL 2016+. Automated backups (IaaS) Windows-only. Don't combine IaaS automated with instance-level log backups. SIMPLE = no log backups. PITR max 35 days. LTR up to 10 years."
        }
      }
    }
  }
};
