var DP700_DATA = {
  title: "Fabric Data Engineer",
  modules: {
    "Module 1": {
      topics: {
        "Dataflows Gen2": {
          core: "Dataflows Gen2 are cloud-based ETL tools using Power Query Online to ingest, transform, and load data into Fabric destinations (Lakehouse, Warehouse, SQL Database) or external targets (Azure SQL Database, Azure Data Explorer, Azure Synapse Analytics), with the dataflow preserving all transformation steps for reuse.",
          tech: "<ul><li>ETL vs. ELT pattern: ETL = Dataflow extracts from source, transforms, then loads to destination. ELT = Pipeline extracts and loads raw data into destination first, then a separate Dataflow Gen2 connects to that data to cleanse and transform.</li><li>Destinations: Lakehouse, Warehouse, SQL Database (Fabric-native); also Azure SQL Database, Azure Data Explorer, Azure Synapse Analytics.</li><li>Adding a destination is optional — dataflow can serve as a data source for data analysts or as a source for pipeline activities.</li><li>Sources: Cloud/on-premises relational databases, Excel/flat files, SharePoint, Salesforce, Spark, Fabric lakehouses.</li><li>Transformations: Filter/Sort, Pivot/Unpivot, Merge/Append, Split/Conditional split, Replace values/Remove duplicates, Add/Rename/Reorder/Delete columns, Rank/Percentage, Top/Bottom N.</li><li>M code: Every transformation generates M code behind the scenes; accessible via Advanced Editor.</li><li>Requirements: Fabric capacity workspace (no RLS support; not a replacement for a data warehouse).</li></ul>",
          archLogic: "Dataflows Gen2 decouple transformation logic from orchestration. The dataflow defines the what (transformations as Power Query M steps), while pipelines define the when and how (sequencing, dependencies, error handling). Use Dataflows Gen2 over raw Copy Data when transformations must be applied during ingestion. Use a Pipeline to wrap a Dataflow when additional orchestration is required.",
          gotchas: "ETL vs. ELT with Dataflows: ETL = Dataflow does Extract, Transform, Load in one step. ELT = Pipeline loads raw data first, then Dataflow transforms. Queries vs. Tables: In the Power Query interface, sources are called queries; once loaded to a destination, they become tables. Destination optional: A dataflow can exist without a configured destination."
        },
        "Data Pipelines": {
          core: "Data pipelines in Fabric (sharing the same architecture as Azure Data Factory) define a sequence of activities — data transformation (Copy Data, Dataflow Gen2, Notebook, Stored procedure, Delete) and control flow (loops, conditionals, variables, parameters) — orchestrated on a visual canvas to automate ETL/ELT processes.",
          tech: "<ul><li>Activity categories: Data transformation activities (Copy Data, Dataflow Gen2, Notebook, Stored procedure, Delete data), Control flow activities (ForEach, Until, If Condition, Set Variable, Wait).</li><li>Copy Data activity: High-performance movement between supported sources and destinations without transformations.</li><li>Parameters: Enable pipeline reusability — provide specific values per run.</li><li>Templates: Predefined activity sequences for common ingestion scenarios.</li><li>Triggers: Manual or scheduled.</li></ul>",
          archLogic: "Pipelines decouple execution logic (sequencing, dependencies, scheduling) from transformation logic (which is handled by activities like Dataflows Gen2, Notebooks, or Stored procedures). This separation allows each activity to be developed, tested, and versioned independently. Use Copy Data over Dataflows Gen2 when moving large volumes of raw data without transformation.",
          gotchas: "Control Flow vs. Data Transformation: Control flow activities manage the execution path; Data transformation activities move/change data. Copy Data vs. Dataflow Gen2: Copy Data is optimized for blind, high-speed raw data movement; Dataflow Gen2 is for low-code visual transformations. Pipeline vs. Dataflow scheduling."
        },
        "Apache Spark": {
          core: "Apache Spark in Microsoft Fabric provides distributed parallel processing via Spark pools (head node driver + worker node executors) for large-scale data analytics, supporting PySpark, Spark SQL, Scala, Spark R, and Java with configurable runtimes, environments, and optimizations.",
          tech: "<ul><li>Spark pool architecture: Head node (runs the driver program), Worker nodes (run executor processes).</li><li>Pool types: Starter pool (default per workspace), Custom pools (specific node configurations).</li><li>Languages: PySpark, Spark SQL, Scala, Spark R, Java.</li><li>Native execution engine: Vectorized processing engine. Enable: spark.native.enabled AND spark.shuffle.manager.</li><li>High concurrency mode: Shares Spark sessions across multiple concurrent users while maintaining code isolation.</li><li>Notebooks vs. Spark Job Definitions: Notebooks (interactive, for exploration), Spark Job Definitions (script-based, for production automation).</li></ul>",
          archLogic: "Spark separates compute (pools) from storage (OneLake), enabling independent scaling of each. The distributed architecture uses a driver program to coordinate work across executor processes. Use notebooks over Spark Job Definitions for iterative development. Use Spark Job Definitions over notebooks for production automation.",
          gotchas: "Driver vs. Executor: The driver is the brain/coordinator; executors process data. Runtime vs. Environment: Runtime is the base software version; Environment is runtime PLUS libraries and configs. Native Execution Engine settings: Must set BOTH spark.native.enabled AND spark.shuffle.manager. High Concurrency Mode: Session shared, state isolated."
        },
        "Spark Dataframes and Spark SQL": {
          core: "Spark Dataframes are distributed collections of data organized into named columns (built on RDDs but with a higher-level API), and Spark SQL provides a SQL interface to query them — together enabling large-scale data manipulation with explicit or inferred schemas, partitioning, and a catalog of managed/external tables and views.",
          tech: "<ul><li>Dataframe: Primary structured data API in Spark. Built on RDDs. Similar to Pandas Dataframes but optimized for distributed processing.</li><li>Loading data: spark.read.load() with format parameter (csv, parquet, delta).</li><li>Schema specification: Inferred (slower, error-prone) vs. Explicit (faster, type-safe).</li><li>Saving data: .write.mode().parquet(), .write.format('delta').saveAsTable().</li><li>Partitioning: .write.partitionBy(). Creates folder hierarchy. Partition pruning: Engine skips irrelevant folders.</li><li>Spark catalog: Temporary views, Managed tables (Fabric manages metadata AND data), External tables (data in external location).</li><li>Spark SQL API: spark.sql(), %%sql magic in notebooks.</li></ul>",
          archLogic: "The dataframe API provides a familiar tabular interface but distributes operations across a cluster, handling partitioning, parallel execution, and fault tolerance transparently. Spark SQL bridges the gap between data engineers (PySpark) and data analysts (SQL). Managed vs. external tables provide flexibility: use managed when Fabric should handle the full lifecycle, external when data must persist independently.",
          gotchas: "Inferred vs. Explicit schema: Inferred requires scan (slower); Explicit skips scan (faster). Managed vs. External tables: Managed = delete table deletes data; External = delete table preserves data. Partitioning anti-pattern: Over-partitioning degrades performance. Delta is the preferred format in Fabric."
        },
        "Eventhouse and KQL": {
          core: "An Eventhouse is a container for one or more KQL databases optimized for high-volume, append-only time-series data with automatic ingestion-time partitioning, supporting Kusto Query Language (KQL) and T-SQL for querying, with sub-second latency on recent data.",
          tech: "<ul><li>Eventhouse: Container housing one or more KQL databases. Automatically creates a default KQL database.</li><li>KQL database: Automatically partitions data by ingestion time, Optimized for immutable, append-only events.</li><li>Data ingestion: Direct (local files, Azure Storage, Amazon S3), Streaming (Azure Event Hubs, Fabric Eventstream), Connectors (Kafka, MQTT, Kinesis, Google Cloud Pub/Sub).</li><li>KQL syntax: Pipeline approach (pipe |), Case-sensitive, Core operators: where, project, take, summarize, sort by, join, limit.</li><li>Materialized views: Precomputed aggregation results that auto-update. Two parts: materialized part + delta.</li><li>Stored functions: Encapsulated KQL queries accepting parameters.</li></ul>",
          archLogic: "Eventhouse/KQL databases implement the digital conveyor belt pattern — events flow in continuously, get automatically organized by ingestion time, and are immediately available for analysis. Automatic time-based partitioning ensures queries for recent data do not scan historical data. Use materialized views when the same aggregation is run repeatedly — trade storage for query speed.",
          gotchas: "KQL case sensitivity: Strictly case-sensitive for ALL identifiers. Pipeline concept: Operations are sequential — each pipe passes the result to the next. Materialized View vs. Standard View: Standard views run the query every time; Materialized views store precomputed results. Time-based filtering is free (indexed). Join order matters: Smaller table first."
        }
      }
    },
    "Module 2": {
      topics: {
        "Platform and Lakehouse": {
          core: "Microsoft Fabric is a unified SaaS analytics platform where all data is stored in a single open format (Delta-Parquet) in OneLake (built on ADLS Gen2), accessible by all compute engines without data movement, with lakehouses providing structured Tables (Delta, SQL-queryable, ACID) and raw Files (any format, no schema enforcement).",
          tech: "<ul><li>OneLake: Built on ADLS Gen2. Single logical lake across regions and clouds without moving/duplicating data.</li><li>Shortcuts: References to files/storage in OneLake or external sources (ADLS Gen2, Amazon S3, Dataverse). No data copying.</li><li>Workspaces: Logical containers for organizing items. Four roles: Admin, Member, Contributor, Viewer.</li><li>OneLake catalog: Searchable discovery. Only see items shared with you.</li><li>Lakehouse structure: Tables folder (Delta Lake tables), Files folder (Raw/semi-structured data). SQL analytics endpoint created automatically.</li><li>Ingestion methods: Upload, Load to Table (CSV/Parquet only), Dataflows Gen2, Notebooks, Data Factory pipelines, Shortcuts.</li><li>Power BI integration: Direct Lake mode — reads Delta Parquet files directly from OneLake.</li></ul>",
          archLogic: "Fabric eliminates the traditional tradeoff between data lakes (flexible/cheap but no ACID) and data warehouses (structured/fast but expensive for diverse data). Lakehouses bridge this by bringing Delta Lake (ACID, schema enforcement, time travel) directly to OneLake storage. The Tables/Files separation lets you maintain raw source data alongside structured analytics tables.",
          gotchas: "Tables vs. Files: Only Tables data is available via SQL analytics endpoint. SQL analytics endpoint is read-only. Load to Table supports CSV and Parquet only. Shortcuts use caller identity. SaaS vs. PaaS: Fabric is SaaS — no need to manually create ADLS Gen2 accounts."
        },
        "Delta Lake": {
          core: "Delta Lake is an open-source storage layer on top of Parquet that brings ACID transactions, schema enforcement, time travel, and batch/streaming unification to data lakes — each Delta table consists of Parquet data files plus a _delta_log folder of JSON transaction logs.",
          tech: "<ul><li>Architecture: Parquet data files + _delta_log folder with JSON transaction logs.</li><li>ACID transactions: Atomicity, Consistency, Isolation, Durability with serializable isolation.</li><li>Schema enforcement: Validates data written matches table schema.</li><li>Time travel: Querying previous versions via versionAsOf or timestampAsOf. View history with DESCRIBE HISTORY.</li><li>OptimizeWrite (enabled by default): Reduces small file problem.</li><li>OPTIMIZE: Compacts small Parquet files into fewer larger files.</li><li>V-Order: Special sorting and compression. Enabled by default. ~15% overhead on write times.</li><li>VACUUM: Removes old Parquet data files. Default: 7 days (168 hours).</li><li>Managed vs. External tables: Managed (delete table deletes data), External (delete table preserves files).</li></ul>",
          archLogic: "Delta Lake solves the small file problem and data corruption risks inherent in raw Parquet lakes. The transaction log makes Parquet files reliable — every write, update, or delete creates a new Parquet file and records it in the log. OptimizeWrite and OPTIMIZE address the small file problem. V-Order specifically optimizes reads for Fabric's Verti-Scan engine.",
          gotchas: "OptimizeWrite enabled by default. V-Order ~15% write overhead. VACUUM default 7 days: Minimum retention enforced; cannot go below 7 days. VACUUM removes files, not transaction logs. Managed vs. External table deletion. Streaming Delta source requires ignoreChanges/ignoreDeletes."
        },
        "Medallion Architecture": {
          core: "The medallion architecture organizes lakehouse data into Bronze (raw/unaltered landing zone), Silver (validated/cleansed/consistent format), and Gold (enriched/star schema/business-level aggregates) layers — a multi-hop design pattern that incrementally improves data quality.",
          tech: "<ul><li>Bronze layer (Raw): Landing zone for all data in original format. No changes made to data.</li><li>Silver layer (Validated): Combine/merge data, enforce validation rules, store in consistent format.</li><li>Gold layer (Enriched): Refinement aligned to specific business/analytics needs. Aggregations, enrichment, dimensional modeling.</li><li>Transformation vs. Orchestration: Data transformation alters structure/content (Dataflows Gen2, Notebooks). Data orchestration coordinates multiple processes (Pipelines).</li><li>Gold layer options: Star schema, Data Warehouse as Gold layer, Power BI Direct Lake mode.</li><li>Security: Different layers in different workspaces. Gold: restrict to read-only. Bronze: restrict to read-only for compliance.</li></ul>",
          archLogic: "The medallion architecture prevents data swamps by forcing incremental quality improvement through defined layers. Each layer has a specific purpose and quality level. Bronze preserves the original data unchanged (compliance, reprocessing). Silver provides organization-wide clean data. Gold models data for specific business consumption.",
          gotchas: "Transformation vs. Orchestration: Transformation changes the data; Orchestration manages the sequence. Multiple Gold layers: Organizations can have multiple Gold layers for different domains. Gold layer as Data Warehouse. Medallion complements, doesn't replace. CI/CD at Gold layer is most critical."
        },
        "Warehouse vs SQL Endpoint": {
          core: "Fabric provides two SQL-based items — a Warehouse with full read-write T-SQL capabilities (DDL, DML, MERGE, ACID) and a read-only SQL analytics endpoint attached to each Lakehouse — and choosing between them depends on whether DML operations are required.",
          tech: "<ul><li>Warehouse: Full read-write T-SQL (DDL and DML), Multi-table ACID compliance, COPY INTO for bulk load, Table clones (zero-copy), Cross-database queries via three-part naming.</li><li>SQL analytics endpoint: Read-only T-SQL queries against Delta tables, supports views, functions, SQL security (RLS, CLS).</li><li>Both support: Views, stored procedures, SQL security (RLS, CLS, DDM).</li><li>Data source: Warehouse = native warehouse tables; Endpoint = lakehouse Delta tables.</li></ul>",
          archLogic: "Use a Warehouse when you need full transactional T-SQL for dimensional modeling, ETL/ELT with DML, and MERGE-based upserts. Use the SQL analytics endpoint when you already have lakehouse Delta tables and only need read-only SQL access.",
          gotchas: "SQL analytics endpoint cannot write. Both support views and stored procedures. Both support SQL security (RLS, CLS, DDM)."
        }
      }
    },
    "Module 3": {
      topics: {
        "Real-Time Intelligence": {
          core: "Real-Time Intelligence is an integrated set of Fabric components (Eventstreams, Eventhouse/KQL databases, Real-Time Hub, KQL Querysets, Real-Time Dashboards, Activator) that ingest, process, store, analyze, and act on streaming data within seconds to minutes of event occurrence.",
          tech: "<ul><li>Events vs. Streams: An event is a single digital record. A stream is an ordered sequence of events.</li><li>Real-Time Hub: Central catalog for discovering and managing all data-in-motion.</li><li>Components: Eventstreams (capture, transform, route), Eventhouse (KQL databases), KQL Queryset (run/manage queries), Real-Time Dashboards (auto-refreshing), Activator (event detection and rules).</li><li>Copilot for Real-Time Intelligence: AI-based KQL query generation.</li></ul>",
          archLogic: "Real-Time Intelligence is designed for latency-sensitive workloads where data value decreases rapidly with time. Unlike batch pipelines that process on schedules, RTI operates on continuous data flows. Each component handles a specific stage — capture, store, analyze, visualize, act.",
          gotchas: "Event vs. Stream: Each event is a single record; a stream is the ordered sequence. Batch vs. Real-Time: Batch processing = scheduled intervals; RTI = continuous flows. Real-Time Hub is a catalog, not storage."
        },
        "Eventstream": {
          core: "A visual no-code engine (drag-and-drop canvas) that captures events from streaming data sources, applies optional in-flight transformations, and routes processed data to one or more destinations — the primary ingestion pipeline for Real-Time Intelligence.",
          tech: "<ul><li>Sources: Microsoft sources (Azure Event Hubs, IoT Hub, Service Bus, CDC), Azure events (Blob Storage), Fabric events, External sources (Kafka, Google Cloud Pub/Sub, MQTT).</li><li>Transformations: Filter, Manage fields, Aggregate, Group by (tumbling/sliding windows), Union, Join, Expand.</li><li>Destinations: Eventhouse (KQL database), Lakehouse (Delta Lake format), Derived stream, Fabric Activator, Custom endpoint.</li></ul>",
          archLogic: "Eventstreams serve as the ingestion and transformation layer before data reaches storage. Content-based routing via derived streams lets different subsets of the same stream go to different destinations. Multiple destinations on the same stream means you can store raw and transformed data simultaneously without duplication.",
          gotchas: "Eventstream transformations vs. KQL Update Policies: Eventstream transforms in-flight before storage; KQL Update Policies run after data is written. Derived streams are destinations that become sources. Union drops non-matching fields. Aggregate vs. Group by."
        },
        "Eventhouse and KQL Databases": {
          core: "An Eventhouse is a container that houses one or more KQL databases, each optimized for storing and analyzing high-velocity, append-only time-series data. Data is automatically partitioned by ingestion time.",
          tech: "<ul><li>Architecture: Automatic partitioning by ingestion time. Time-series data is immutable. Append-only pattern.</li><li>KQL: Pipeline-based language using pipe (|) to flow data. Case-sensitive for everything.</li><li>Query optimization: Filter early (especially time-based), Reduce columns early, Smaller table first in joins.</li><li>Materialized views: Precomputed aggregation results that auto-update. Always returns current data.</li><li>Stored functions: Encapsulate query logic as reusable parameterized functions.</li><li>OneLake availability: Enable per KQL database or table for cross-workload access.</li></ul>",
          archLogic: "KQL databases are optimized for the unique characteristics of time-series data — immutable, append-only, timestamp-centric. Automatic ingestion-time partitioning means recent data is isolated from historical data. Materialized views solve the problem of recalculating aggregations over billions of rows on every query.",
          gotchas: "KQL is case-sensitive. Filter order matters: time filters first because they leverage the time index. Smaller table first in joins. Materialized views always return current data. Materialized vs. regular view. Stored functions vs. views. Database shortcuts vs. OneLake availability."
        },
        "Real-Time Dashboards": {
          core: "A visual monitoring interface composed of tiles, each displaying a KQL query result that refreshes automatically as new data arrives in the connected KQL database — purpose-built for continuous data tracking.",
          tech: "<ul><li>Structure: One or more tiles per dashboard. Multiple pages organize related tiles.</li><li>Authorization: Pass-through identity (user's own permissions) or Dashboard editor's identity (creator's permissions).</li><li>Tiles: Each tile displays results of a KQL query. Interactive: drill into data, filter, aggregate.</li><li>Parameters: User-driven filters with underscore-prefixed variable names.</li><li>Auto refresh: Editors set default rate. Viewers can adjust. Editors set minimum refresh rate.</li><li>Base queries: Shared query definitions reusable across multiple tiles.</li></ul>",
          archLogic: "Real-Time Dashboards differ from Power BI reports in their data refresh model. Dashboards connect directly to KQL databases and refresh tiles continuously — there is no scheduled import. Base queries improve maintainability by centralizing common data retrieval logic.",
          gotchas: "Base queries vs. individual tile queries. Parameter underscore prefix. Pass-through vs. editor identity. Auto refresh minimum rate. Tiles render as tables initially."
        },
        "Activator": {
          core: "Activator is Fabric's event detection and rules engine within Real-Time Intelligence — it continuously monitors streaming data against user-defined conditions and triggers automated actions when conditions are met.",
          tech: "<ul><li>Core object model: Events (individual records), Objects (entities being monitored), Properties (attributes), Rules (conditions triggering actions).</li><li>Rule definition: Monitor section (Attribute, Summarization: Average/Min/Max/Count/Total, Timing: Window size and Step size), Condition section (Threshold, Change detection, Range, Missing data, Occurrence behavior), Property filter (up to 3 conditions).</li><li>Actions: Email, Teams, Power Automate, Fabric item actions (execute pipelines/notebooks).</li><li>Alternative approaches: Dashboard alerts, System event alerts, Query alerts.</li></ul>",
          archLogic: "Activator's business object model enables stateful monitoring of individual entities rather than stateless stream-level checks. Instead of asking does any row have Temperature > 68F, you ask does Package001 maintain Temperature > 68F over a sustained period — this requires tracking per-object state across multiple events. Summarization distinguishes transient spikes from sustained problems.",
          gotchas: "Business Objects vs. Simple Alerts: Business objects track state per-entity; Simple alerts check conditions against any row. Window size vs. Step size: Window = how far back; Step = how often to recalculate. Summarization prevents alert fatigue. Missing data detection. Up to 3 property filters."
        }
      }
    },
    "Module 4": {
      topics: {
        "Warehouse vs SQL Analytics Endpoint": {
          core: "Fabric provides two SQL-based items serving different purposes — a Warehouse with full read-write T-SQL capabilities and a read-only SQL analytics endpoint attached to each Lakehouse.",
          tech: "<ul><li>Warehouse: Full read-write T-SQL (DDL, DML, MERGE, ACID), COPY INTO for bulk load, Table clones (zero-copy), Cross-database queries via three-part naming.</li><li>SQL analytics endpoint: Read-only T-SQL queries against Delta tables, supports views, functions, SQL security.</li><li>Both support: Views, stored procedures, SQL security.</li></ul>",
          archLogic: "Use a Warehouse when you need full transactional T-SQL. Use the SQL analytics endpoint when you already have lakehouse Delta tables and only need read-only SQL access.",
          gotchas: "SQL analytics endpoint cannot write. Both support views and stored procedures. Both support SQL security."
        },
        "Dimensional Modeling": {
          core: "Data warehouses organize data into fact tables (quantitative measures of business events) and dimension tables (descriptive attributes providing context), typically structured as a star schema or snowflake schema.",
          tech: "<ul><li>Fact tables: Numerical measures (SalesAmount, Quantity). Large row counts. Foreign keys to dimension tables.</li><li>Dimension tables: Descriptive attributes. Contain surrogate key (DW-generated integer) and alternate key (source-system business key).</li><li>Star schema: Fact table relates directly to each dimension. Denormalized dimensions.</li><li>Snowflake schema: Dimensions normalized into related tables. Multiple joins required.</li><li>SCD (Slowly Changing Dimensions): Type 0, Type 1, Type 2 (add new row), Type 3, Type 4, Type 5, Type 6.</li><li>Staging tables: Temporary holding area mirroring source data structure.</li><li>Scalar approximate count: APPROX_COUNT_DISTINCT(column) uses HyperLogLog algorithm. Maximum 2% error rate.</li></ul>",
          archLogic: "The dimensional model (star/snowflake) optimizes for analytical queries over transactional ones. Dimension denormalization (star) prioritizes query performance by minimizing joins at the cost of storage. SCD Type 2 is the most common approach for tracking historical changes — it preserves full history but increases dimension table size.",
          gotchas: "Surrogate key is DW-internal: Never expose to end users. Alternate key is source-internal: Always preserve for traceability. Type 2 SCD requires change detection. Fact tables loaded after dimensions. Staging vs final tables."
        },
        "Fabric Warehouse Architecture": {
          core: "A Fabric data warehouse is a fully managed, enterprise-scale relational database built on OneLake with full transactional T-SQL capabilities, ACID compliance, automatic compute scaling independent of storage, and Delta format storage accessible by all Fabric workloads.",
          tech: "<ul><li>Storage: All warehouse data stored in open Delta Parquet format on OneLake.</li><li>Compute: Scales automatically and independently from storage.</li><li>T-SQL support: Full DDL (CREATE, ALTER, DROP), DML (INSERT, UPDATE, DELETE, MERGE), query capabilities.</li><li>MERGE: Supports upsert scenarios (INSERT + UPDATE + DELETE in single statement).</li><li>Cross-database querying: Three-part naming (database.schema.table) to query across warehouses and lakehouses in the same workspace.</li><li>Table clones: Zero-copy clones using CREATE TABLE AS CLONE OF.</li><li>Ingestion methods: COPY INTO (bulk load), OPENROWSET (query files directly), CTAS, INSERT...SELECT, Data pipelines, Dataflows Gen2.</li></ul>",
          archLogic: "The Fabric warehouse decouples compute from storage — queries consume compute resources that auto-scale independently of the underlying Delta Parquet files in OneLake. Cross-database querying using 3-part naming eliminates data duplication between warehouses and lakehouses in the same workspace. Table clones provide instant point-in-time copies without storage overhead.",
          gotchas: "COPY INTO requires CREDENTIAL: Must specify SAS or Storage Account Key. Cross-database requires same workspace. Table clones are zero-copy. CTAS vs INSERT...SELECT. Entra ID only — no SQL auth. Port 1433 must be open."
        },
        "Querying the Warehouse": {
          core: "Query a Fabric warehouse using T-SQL (SQL query editor with IntelliSense and Copilot) or no-code visual query editor (drag-drop canvas with auto-generated T-SQL), supporting full analytical patterns including ranking functions, approximate counts, and window functions.",
          tech: "<ul><li>SQL query editor: IntelliSense, code completion, syntax highlighting, client-side parsing. Results preview capped at 10,000 rows.</li><li>Visual query editor: Drag tables onto canvas. Right-click for Merge queries. View SQL button to inspect auto-generated T-SQL.</li><li>Ranking functions with PARTITION BY: ROW_NUMBER(), RANK(), DENSE_RANK(), NTILE(N).</li><li>Snowflake schema querying: Requires multiple JOINs through the normalization chain.</li></ul>",
          archLogic: "The SQL query editor and visual query editor serve different audiences — T-SQL developers get IntelliSense, Copilot, and full syntax control; citizen developers get drag-drop with automatic query generation. Ranking functions enable complex analytical patterns in single queries without self-joins or subqueries.",
          gotchas: "Visualize results does not support ORDER BY. SSMS requires explicit database name. Port 1433 requirement. Entra ID authentication only. RANK vs DENSE_RANK. ROW_NUMBER is non-deterministic for ties."
        },
        "Data Modeling and Semantic Layer": {
          core: "Preparing warehouse data for consumption involves cleaning up the model view (hiding staging/internal objects, renaming columns, adding descriptions), defining relationships, standardizing access through views and DAX measures, and publishing semantic models using Direct Lake mode.",
          tech: "<ul><li>Model view actions: Hide objects, Rename columns, Add descriptions (critical for Copilot).</li><li>Relationships: Cardinality (typically many-to-one), Cross-filter direction (single direction standard).</li><li>Views: Standardize access for T-SQL consumers. Encapsulate join logic, filters, column selection.</li><li>DAX Measures: Reusable calculations defined in the warehouse model view.</li><li>Semantic model: Created from warehouse using Direct Lake mode. Reads Delta Parquet files directly from OneLake.</li></ul>",
          archLogic: "Data modeling in the warehouse exists to bridge the gap between the technical schema (optimized for ETL) and the consumer schema (optimized for analysis). Hiding staging artifacts, renaming columns, and adding descriptions make the warehouse self-documenting. Relationships replace manual JOIN knowledge with encoded connections.",
          gotchas: "Hiding vs deleting: Hiding removes from consumer view but does not drop the object. Renaming in model view is cosmetic. Direct Lake vs Import. Relationships inform Copilot/data agents."
        },
        "Copilot for Data Warehouse": {
          core: "AI-powered assistant integrated into the SQL query editor providing code completion, chat-based natural language to T-SQL generation, and quick actions (Explain, Fix) — requiring F2/P1+ capacity and well-structured schema for best results.",
          tech: "<ul><li>Prerequisites: Copilot enabled in tenant settings. Paid SKU (F2 or higher). Warehouse created in workspace.</li><li>Code completion: Ghost text suggestions as you type.</li><li>Comments to guide Copilot: Use -- comments to describe intent.</li><li>Copilot chat pane: /generate-sql, /explain, /fix, /question, /help. Session context retained.</li><li>Quick actions: Explain (adds summary and inline comments), Fix (auto-resolves errors - only enabled after running a query that returned an error).</li></ul>",
          archLogic: "Copilot uses the warehouse schema (table names, column names, relationships, descriptions) as grounding context for T-SQL generation. The quality of generated queries correlates directly with schema quality — descriptive names and defined relationships produce accurate joins and filters.",
          gotchas: "Fix button only activates after error. Trial SKUs do not support Copilot. English language only. Code completion requires explicit enable. Session context retained."
        },
        "Monitoring a Warehouse": {
          core: "Monitor warehouse activity through three mechanisms: the Fabric Capacity Metrics app (CU consumption trends), dynamic management views (real-time connections, sessions, requests), and query insights views (historical aggregated query performance with 30-day retention).",
          tech: "<ul><li>Fabric Capacity Metrics app: Installed by admin. Monitor CU consumption trends, identify throttling.</li><li>DMVs (real-time monitoring): sys.dm_exec_connections, sys.dm_exec_sessions, sys.dm_exec_requests. KILL command requires workspace Admin role.</li><li>Query insights views (historical, 30-day retention): queryinsights.exec_requests_history, queryinsights.long_running_queries, queryinsights.frequently_run_queries. Latency: Up to 15 minutes.</li></ul>",
          archLogic: "DMVs and query insights serve different monitoring timeframes. DMVs show what is happening right now — useful for identifying a runaway query. Query insights show what happened over the past 30 days — useful for identifying performance trends and optimization targets.",
          gotchas: "DMVs vs query insights: DMVs = real-time; Query insights = historical (30-day retention, up to 15-min delay). KILL requires Admin. Parameterized dedup."
        },
        "Warehouse Security": {
          core: "Multi-layered security: workspace roles (broad access control), item permissions (granular sharing), and T-SQL-based granular security (DDM, RLS, CLS, object-level permissions) — all enforced regardless of how data is accessed.",
          tech: "<ul><li>Workspace roles: Admin, Member, Contributor, Viewer.</li><li>Item permissions: Read, ReadData, ReadAll.</li><li>Dynamic Data Masking (DDM): default(), email(), partial(), random(). Applied per-column via ALTER TABLE.</li><li>Row-Level Security (RLS): Two-step: create filter predicate function, then create security policy.</li><li>Column-Level Security (CLS): GRANT SELECT on entire table, then DENY SELECT on specific column.</li><li>SQL granular permissions: GRANT, REVOKE, DENY on tables and views.</li></ul>",
          archLogic: "Security is layered so that each layer addresses a different scope: workspace roles control who can access the workspace at all, item permissions control who can access a specific warehouse, and T-SQL granular security controls what data within the warehouse each user can see or modify. The DENY permission always overrides GRANT.",
          gotchas: "DDM does not change physical data. DDM side-channel risk. RLS requires both function + policy. RLS INSERT is not affected. DENY overrides GRANT. CLS vs views choice. Separate schema for RLS objects."
        }
      }
    },
    "Module 5": {
      topics: {
        "CI/CD: Git Integration and Deployment Pipelines": {
          core: "Fabric lifecycle management uses Git integration (GitHub/Azure DevOps) for version control and continuous integration, Fabric deployment pipelines for staged promotion (Dev → Test → Production), and Fabric REST APIs for automation — collectively enabling CI/CD for Fabric items.",
          tech: "<ul><li>Git integration (CI): Workspace-level connection to GitHub or Azure DevOps repositories. Branch support enables isolated development.</li><li>Deployment pipelines (CD): Create pipeline with 2-3 stages (Dev, Test, Production). Assign a workspace to each stage.</li><li>Combined Git + deployment pipelines: Common approach: connect only the Development workspace to Git.</li><li>Fabric REST APIs for CI/CD: Git APIs (commit, sync, status), Deployment pipeline APIs (list, deploy).</li><li>Branching workflow (isolated workspace): Connect dev workspace to main branch, Branch out to new workspace, Make changes, Commit to isolated branch, Create PR to merge.</li></ul>",
          archLogic: "CI/CD separates development from production to prevent breaking changes and enable collaboration. Git provides version history, branching, and pull request workflows for safe code integration. Deployment pipelines handle the infrastructure-level promotion of entire workspace contents between environments. The recommended combined approach uses Git only on the Development workspace to avoid synchronization conflicts.",
          gotchas: "Git integration is at workspace level. Deployment pipeline copies ALL content. Only Development workspace connected to Git in combined approach. Branch out creates both new branch and new workspace. CI = Git; CD = Deployment pipelines."
        },
        "Monitoring Hub": {
          core: "The Monitor Hub is a centralized visualization tool that collects and aggregates execution data from Fabric activities (pipelines, dataflows, semantic model refreshes, Spark jobs, Eventstreams) into a single interface — providing job status, 30-day history, drill-down error investigation, and filterable views.",
          tech: "<ul><li>Access: Monitor icon in Fabric navigation pane. Users see only items they have permission to view.</li><li>Monitored activities: Pipeline execution history, dataflow executions, semantic model refreshes, Spark job execution history, Eventstream ingestion status.</li><li>View capabilities: Status per activity (Running, Succeeded, Failed), 30-day history, Filter by: status, item type, start time, submitting user, workspace.</li><li>Drill-down actions: Open activity, Retry, View details, View historical runs.</li></ul>",
          archLogic: "The Monitor Hub solves the problem of fragmented monitoring across different Fabric item types. Instead of checking pipeline runs in Data Factory, notebook runs in Data Engineering, and refresh history in Power BI separately, the hub aggregates all activity metadata into one view. The 30-day retention provides trend analysis context.",
          gotchas: "Monitor Hub is reactive, not proactive: Shows what happened. Proactive alerting requires Activator. 30-day retention. User-specific visibility. Activity detail is type-specific."
        },
        "OneLake Security Roles": {
          core: "OneLake security uses a role-based access control (RBAC) model that restricts access to specific tables or folders within a lakehouse — enforced consistently across all Fabric compute engines (Spark, SQL, and OneLake APIs).",
          tech: "<ul><li>When to use: Users with Admin, Member, or Contributor workspace roles already have full read/write access. Use OneLake roles for Viewer role users or users with only Read item permission.</li><li>Role components: Data, Permission (Read/ReadWrite), Members, Constraints.</li><li>DefaultReader role: Every new lakehouse automatically includes a DefaultReader role. Users shared with Read all Apache Spark are added to it.</li><li>Creation permissions: Only workspace Admin and Member roles can create or modify OneLake security roles.</li><li>Consistency: OneLake security roles apply across ALL compute engines — Spark notebooks, SQL analytics endpoint, and OneLake APIs.</li></ul>",
          archLogic: "OneLake security fills the gap between workspace-level access and SQL-level granular permissions. Workspace roles grant all-or-nothing access to lakehouse data. T-SQL permissions only control what users see through the SQL analytics endpoint. OneLake security applies consistently across all access methods, ensuring a user restricted from certain tables in the SQL endpoint cannot bypass the restriction by querying through Spark.",
          gotchas: "OneLake security grants access, does not restrict. DefaultReader removal is critical. OneLake security vs. T-SQL security. Constraints not available at role creation. ReadWrite permission. Creation limited to Admin/Member."
        },
        "Fabric Administration": {
          core: "Five-level platform hierarchy (Tenant → Capacity → Domain → Workspace → Item) with a four-tier admin delegation model (Fabric admin, Capacity admin, Domain admin, Workspace admin), managed through the Fabric admin portal for tenant settings, capacity management, domain governance, license assignment, and monitoring.",
          tech: "<ul><li>Hierarchy: Tenant, Capacity, Domain, Workspace, Item.</li><li>Admin roles: Fabric admin (entire tenant), Capacity admin (specific capacity), Domain admin (specific domain), Workspace admin (specific workspace).</li><li>Tenant settings: Enable/disable features for entire org or specific security groups. Changes propagate within 15 minutes. NOT security measures.</li><li>Domains: Logical grouping. Domain assignment does NOT change item visibility or access control. Subdomains: nested governance boundaries.</li><li>Capacity management: CU consumption, Scale up (increase F SKU size), Scale out (move workspaces to separate capacity), Pause capacity.</li><li>Licensing: Fabric Free, Power BI Pro, Power BI Premium Per User (PPU), F64 threshold (Free users can view Power BI content on F64+).</li><li>Sharing patterns: Workspace apps (read-only reports for large audiences), Workspace roles (direct workspace access).</li><li>Audit logs: Capture who viewed/exported reports, shared content externally, modified workspace permissions, deleted Fabric items.</li></ul>",
          archLogic: "The admin model follows a centrally governed, decentrally managed pattern. The Fabric admin sets tenant-wide policies and delegates operational management to domain admins and capacity admins. Domains organize governance boundaries without interfering with the existing workspace role and item permission access control model. The F64 threshold is a critical architectural design point: it determines whether Free users can view Power BI content.",
          gotchas: "Tenant settings are NOT security: Disabling Export to Excel removes the UI button but does not prevent data export via API. Domains do NOT control access. F64 threshold changes license requirements. Fabric admin = Power BI Administrator in Entra ID. License assignment is M365 task. Capacity pause makes all content unavailable. DefaultReader role is auto-created. Endorsement: Promoted vs Certified."
        }
      }
    },
    "Module 6": {
      topics: {
        "Activator": {
          core: "Activator is Fabric's event detection and rules engine within Real-Time Intelligence — it monitors streaming data against user-defined conditions and triggers automated actions (email, Teams, Power Automate, Fabric item actions) when conditions are met, turning passive monitoring into active response.",
          tech: "<ul><li>Core object model: Events (individual data records), Objects (real-world entities being monitored), Properties (data attributes), Rules (conditions triggering actions).</li><li>Rule definition: Monitor section (Attribute, Summarization, Timing: Window size and Step size), Condition section (Threshold, Change detection, Range, Missing data, Occurrence behavior), Property filter (up to 3 conditions).</li><li>Actions: Email (detailed notification), Teams (immediate message), Power Automate (multi-step business process automation), Fabric item actions (execute data pipelines or notebooks).</li><li>Alternative alerting approaches: Dashboard alerts, System event alerts, Query alerts — simpler paths to the same engine.</li></ul>",
          archLogic: "Activator's business object model enables stateful monitoring of individual entities — tracking each package's temperature over time, not just checking if any row exceeds a threshold. Summarization (window + step) distinguishes transient spikes from sustained problems, preventing alert fatigue. The property filter section focuses rules on relevant subsets.",
          gotchas: "Business Objects vs. Simple Alerts: Business objects track per-entity state; Simple alerts check conditions against any row. Window size vs. Step size. Summarization prevents alert fatigue. Missing data detection. Up to 3 property filters. 'Every time' vs. 'When it has been true for'."
        }
      }
    }
  }
};
