// Module 4: Query Performance Optimization, Database Design & Evaluation
(function() {
  var questions = [
  // === Query Performance Optimization ===
  {
    "text": "When a query is submitted to SQL Server, what is the correct order of processing steps in the query processor?",
    "options": [
      "Optimize, Parse, Algebrizer, Execute",
      "Parse, Algebrizer, Check plan cache, Optimize, Execute",
      "Algebrizer, Parse, Execute, Cache",
      "Parse, Optimize, Algebrizer, Execute"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The correct flow is: Parse (check syntax, generate parse tree) → Algebrizer (binding, validate objects) → Check plan cache (query_hash match) → Optimize (cost-based if no cached plan) → Execute."
  },
  {
    "text": "Which type of execution plan is generated without executing the query and shows only estimated row counts?",
    "options": [
      "Actual execution plan",
      "Estimated execution plan",
      "Live Query Statistics",
      "Query Store plan"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The Estimated Execution Plan is generated by the query optimizer without executing the query. Use SET SHOWPLAN_ALL ON to see it in text format. The query does not run and no results are returned."
  },
  {
    "text": "What is the approximate maximum overhead of lightweight query profiling in SQL Server 2019 and Azure SQL?",
    "options": [
      "75%",
      "25%",
      "2%",
      "10%"
    ],
    "correct": 2,
    "module": 4,
    "explanation": "Lightweight profiling has a maximum overhead of approximately 2%, compared to the legacy profiling which could produce up to 75% overhead. It is enabled by default in SQL Server 2019, Azure SQL Database, and Azure SQL Managed Instance."
  },
  {
    "text": "Which hint should be added to a query to enable lightweight profiling at the individual query level?",
    "options": [
      "OPTION (RECOMPILE)",
      "OPTION (USE HINT ('QUERY_PLAN_PROFILE'))",
      "OPTION (MAXDOP 1)",
      "OPTION (OPTIMIZE FOR UNKNOWN)"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The USE HINT with QUERY_PLAN_PROFILE enables lightweight profiling at the query level. When a query with this hint completes, a query_plan_profile extended event is generated providing an actual execution plan."
  },
  {
    "text": "What are the three stores that make up the SQL Server Query Store?",
    "options": [
      "Plan store, Index store, Wait stats store",
      "Plan store, Runtime stats store, Wait stats store",
      "Cache store, Statistics store, Plan store",
      "Query store, Execution store, Wait store"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The Query Store consists of three internal stores: the Plan store (estimated execution plans), the Runtime stats store (execution statistics), and the Wait stats store (wait statistics)."
  },
  {
    "text": "Which stored procedure is used to force a specific query plan in the Query Store?",
    "options": [
      "sp_query_store_force_plan",
      "sp_force_plan",
      "sp_set_plan",
      "sp_plan_force"
    ],
    "correct": 0,
    "module": 4,
    "explanation": "The stored procedure sp_query_store_force_plan is used to force a specific plan for a query. It takes @query_id and @plan_id as parameters. Example: EXEC sp_query_store_force_plan @query_id=73, @plan_id=79."
  },
  {
    "text": "Which of the following predicates is SARGable and allows SQL Server to consider an index seek?",
    "options": [
      "WHERE LEFT(City, 1) = 'M'",
      "WHERE City LIKE 'M%'",
      "WHERE City LIKE '%M%'",
      "WHERE CONVERT(CHAR(10), CreateDate, 121) = '2020-03-22'"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "WHERE City LIKE 'M%' is SARGable because the wildcard is not at the beginning — SQL Server can perform an index seek. Non-SARGable predicates include functions on columns (LEFT, CONVERT) and leading wildcards (LIKE '%M%')."
  },
  {
    "text": "At what threshold does SQL Server escalate multiple row locks to a single table lock?",
    "options": [
      "1,000 rows",
      "5,000 rows",
      "10,000 rows",
      "50,000 rows"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "If more than 5,000 rows on a single object need to be locked in a single statement, SQL Server escalates the multiple row locks to a single table lock. This balances concurrency with the memory cost of managing many individual locks."
  },
  {
    "text": "When a deadlock occurs, how does SQL Server choose which transaction to terminate as the deadlock victim?",
    "options": [
      "The transaction that has performed the most work",
      "The transaction that has performed the least amount of work that needs to be rolled back",
      "The transaction that started first",
      "Both transactions are terminated"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "SQL Server detects deadlocks and kills the transaction that has performed the least amount of work that needs to be rolled back. This minimizes the overall impact of the deadlock resolution."
  },
  {
    "text": "Where are deadlock events recorded by default in SQL Server?",
    "options": [
      "SQL Server error log",
      "system_health extended event session",
      "Windows Application Event Log",
      "Query Store"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "Deadlocks are recorded in the system_health extended event session, which is enabled by default in SQL Server. This session captures various system health information including deadlock graphs."
  },
  // === Database Design ===
  {
    "text": "A table contains ProductID, Color1, Color2, and Color3 columns. Which normal form does this violate?",
    "options": [
      "First normal form (1NF) — contains repeating groups",
      "Second normal form (2NF) — partial dependency on composite key",
      "Third normal form (3NF) — transitive dependency",
      "It is fully normalized"
    ],
    "correct": 0,
    "module": 4,
    "explanation": "This violates first normal form because it has repeating groups (multiple color columns). 1NF requires eliminating repeating groups and creating a separate table. The correct design would have a ProductColor table with ProductID and Color columns."
  },
  {
    "text": "A table has a composite primary key on ProductID and Color, and includes a Price column that depends only on ProductID. Which normal form does this violate?",
    "options": [
      "First normal form",
      "Second normal form",
      "Third normal form",
      "It satisfies all normal forms"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "This violates second normal form (2NF). When a table has a composite key, all attributes must depend on the complete key. Since Price depends only on ProductID (not on Color), there is a partial dependency. Price should be in a separate table with ProductID as the key."
  },
  {
    "text": "Which schema design uses normalized dimensions and requires more joins but saves storage space?",
    "options": [
      "Star schema",
      "Snowflake schema",
      "Galaxy schema",
      "Constellation schema"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The snowflake schema uses a set of more normalized tables for a single business entity, saving storage space but requiring more joins which increases complexity and can decrease performance compared to a star schema."
  },
  {
    "text": "What is the minimum number of rows required for a bulk insert operation to load directly into the compressed columnstore index (rather than the delta store)?",
    "options": [
      "10,000",
      "102,400",
      "1,024,000",
      "500,000"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The minimum number of rows to load directly into a compressed columnstore rowgroup is 102,400 rows. For smaller loads, the data goes into a delta store (b-tree structure) and is later moved asynchronously by the tuple mover."
  },
  {
    "text": "What is the maximum size of a compressed columnstore rowgroup?",
    "options": [
      "102,400 rows",
      "524,000 rows",
      "1,024,000 rows",
      "Unlimited"
    ],
    "correct": 2,
    "module": 4,
    "explanation": "A compressed columnstore rowgroup can contain up to approximately 1,024,000 rows. Having fewer but fuller rowgroups makes SELECT queries more efficient because fewer rowgroups need to be scanned."
  },
  {
    "text": "Which data types are NOT supported in a clustered columnstore index?",
    "options": [
      "INT, BIGINT, and DECIMAL",
      "XML, CLR, and sql_variant",
      "VARCHAR and NVARCHAR",
      "DATE and DATETIME"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "Clustered columnstore indexes do not support data types such as XML, CLR, sql_variant, ntext, text, and image. For these types, you must use a nonclustered columnstore index or a b-tree index."
  },
  {
    "text": "What is the function of the tuple mover in a columnstore index?",
    "options": [
      "It creates new rowgroups in the columnstore",
      "It asynchronously moves data from the delta store into the compressed columnstore",
      "It updates statistics for the columnstore index",
      "It drops unused segments from the columnstore"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The tuple mover is an asynchronous process that moves data from the delta store (b-tree structure for small loads) into the compressed columnstore index. This happens in the background without user intervention."
  },
  {
    "text": "Which T-SQL option should be used with ALTER INDEX to force delta store data to be compressed into the columnstore?",
    "options": [
      "REBUILD",
      "REORGANIZE WITH (COMPRESS_ALL_ROW_GROUPS = ON)",
      "ALTER COLUMNSTORE",
      "SET COMPRESSION = ON"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "Using REORGANIZE with the COMPRESS_ALL_ROW_GROUPS option forces all delta stores to be added and compressed into the columnstore indexes. This is useful when you want to ensure all data is in the compressed columnstore format."
  },
  {
    "text": "What is the requirement for using resumable index operations in SQL Server?",
    "options": [
      "The index must be nonclustered",
      "The ONLINE option must be set to ON",
      "The database must be in FULL recovery model",
      "The index must be on a columnstore table"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "Resumable index operations are only supported with ONLINE=ON. The RESUMABLE=ON option can be combined with ONLINE=ON to allow index operations to be paused and resumed. Check status via sys.index_resumable_operations."
  },
  {
    "text": "Which DMV should be queried to check the current execution status of a resumable online index operation?",
    "options": [
      "sys.dm_db_index_physical_stats",
      "sys.index_resumable_operations",
      "sys.dm_exec_index_status",
      "sys.dm_os_wait_stats"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The sys.index_resumable_operations system view shows the current execution status for a resumable online index operation, including how far along the rebuild or creation has progressed."
  },
  // === Evaluate Performance ===
  {
    "text": "Which wait type indicates that queries are waiting for memory to become available, often due to excessive memory grants?",
    "options": [
      "PAGEIOLATCH_SH",
      "RESOURCE_SEMAPHORE",
      "LCK_M_X",
      "SOS_SCHEDULER_YIELD"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "RESOURCE_SEMAPHORE indicates that queries are waiting for memory to become available, often due to excessive memory grants to certain queries. This can be caused by out-of-date statistics, missing indexes, or high query concurrency."
  },
  {
    "text": "A high occurrence of PAGEIOLATCH_UP waits on data page 2:1:1 indicates which issue?",
    "options": [
      "Storage subsystem performance problem",
      "TempDB contention on PFS (Page Free Space) data pages",
      "CPU pressure due to excessive parallelism",
      "Memory grant waits"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "PAGEIOLATCH_UP on data pages 2:1:1 indicates TempDB contention on PFS (Page Free Space) data pages. This is typically caused by having only one TempDB data file. Best practice is to use one file per CPU core, up to eight files."
  },
  {
    "text": "Which wait type is commonly associated with high CPU utilization and often correlates with large scans and missing indexes?",
    "options": [
      "CXPACKET",
      "PAGEIOLATCH_SH",
      "SOS_SCHEDULER_YIELD",
      "LCK_M_X"
    ],
    "correct": 2,
    "module": 4,
    "explanation": "SOS_SCHEDULER_YIELD indicates high CPU utilization, which correlates with large scans, missing indexes, and often with high numbers of CXPACKET waits. It means threads are yielding the scheduler voluntarily."
  },
  {
    "text": "Which DMV should be used for Azure SQL Database to view CPU, memory, and I/O resource usage with snapshots every 15 seconds?",
    "options": [
      "sys.dm_os_wait_stats",
      "sys.dm_db_resource_stats",
      "sys.server_resource_stats",
      "sys.dm_exec_query_stats"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "sys.dm_db_resource_stats provides CPU, memory, and I/O resource usage for Azure SQL Database, with snapshots taken every 15 seconds. For SQL Managed Instance, use sys.server_resource_stats instead."
  },
  {
    "text": "Which wait type is expected and normal for the Business Critical service tier in Azure SQL Database?",
    "options": [
      "PAGEIOLATCH_SH",
      "HADR_SYNC_COMMIT",
      "RESOURCE_SEMAPHORE",
      "LCK_M_X"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "HADR_SYNC_COMMIT is a normal wait type for the Business Critical service tier because it uses Always On Availability Group technology to implement its SLA and availability features. These waits are expected and don't necessarily indicate a problem."
  },
  {
    "text": "Which log governance wait type is specific to Azure SQL Managed Instance?",
    "options": [
      "LOG_RATE_GOVERNOR",
      "POOL_LOG_RATE_GOVERNOR",
      "INSTANCE_LOG_GOVERNOR",
      "HADR_THROTTLE_LOG_RATE"
    ],
    "correct": 2,
    "module": 4,
    "explanation": "INSTANCE_LOG_GOVERNOR is the wait type for log rate governance on Azure SQL Managed Instance. LOG_RATE_GOVERNOR is for SQL Database, POOL_LOG_GOVERNOR is for elastic pools."
  },
  {
    "text": "Which DMV should you query to find live wait statistics for currently executing queries?",
    "options": [
      "sys.dm_os_wait_stats",
      "sys.dm_os_waiting_tasks",
      "sys.dm_exec_session_wait_stats",
      "sys.dm_db_wait_stats"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "sys.dm_os_waiting_tasks contains live wait stats for currently executing tasks. sys.dm_os_wait_stats aggregates wait statistics over time since instance startup. sys.dm_exec_session_wait_stats shows waits by session."
  },
  {
    "text": "Which feature allows shaping query plans without modifying application code by using query_id and hint strings?",
    "options": [
      "Plan Guides",
      "Query Store hints (sp_query_store_set_hints)",
      "Query hints with OPTION clause",
      "Database scoped configurations"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "Query Store hints via sp_query_store_set_hints allow shaping query plans without modifying application code. Identify the query_id via Query Store views, then execute sp_query_store_set_hints with the query_id and hint string. This is useful when application code cannot be changed."
  },
  {
    "text": "Which query hint causes SQL Server to generate a new plan each time a query executes and discards it immediately after execution?",
    "options": [
      "OPTION (MAXDOP 1)",
      "OPTION (RECOMPILE)",
      "OPTION (OPTIMIZE FOR UNKNOWN)",
      "OPTION (FAST 10)"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "The RECOMPILE query hint creates a new, temporary plan for the query and discards it immediately after the query is executed. This ensures the plan is recompiled based on the current parameter values every time."
  },
  {
    "text": "In the Query Store hints feature, which stored procedure is used to apply hints to a specific query?",
    "options": [
      "sp_query_store_set_hints",
      "sp_query_store_force_plan",
      "sp_set_query_hints",
      "sp_apply_hints"
    ],
    "correct": 0,
    "module": 4,
    "explanation": "sp_query_store_set_hints is used to apply query hints via the Query Store. It takes @query_id and @query_hints parameters. Example: EXEC sp_query_store_set_hints @query_id=42, @query_hints = N'OPTION(RECOMPILE, MAXDOP 1)'."
  },
  {
    "text": "Which DMV is used to view the actual configuration and capacity settings used by resource governance mechanisms for Azure SQL Database?",
    "options": [
      "sys.dm_instance_resource_governance",
      "sys.dm_user_db_resource_governance",
      "sys.dm_db_resource_stats",
      "sys.dm_os_wait_stats"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "sys.dm_user_db_resource_governance returns the actual configuration and capacity settings used by resource governance mechanisms in the current Azure SQL Database or elastic pool. For SQL Managed Instance, use sys.dm_instance_resource_governance."
  },
  {
    "text": "A query with a LIKE predicate using '%term' at the beginning is considered non-SARGable. What type of index operation will the optimizer likely use?",
    "options": [
      "Index Seek",
      "Index Scan or Table Scan",
      "Key Lookup",
      "Hash Join"
    ],
    "correct": 1,
    "module": 4,
    "explanation": "Non-SARGable predicates with a leading wildcard (LIKE '%term') prevent the optimizer from considering an Index Seek. The optimizer will likely perform an Index Scan or Table Scan instead, reading more data than necessary. The absence of a SARG means the optimizer won't evaluate a seek."
  }
  ];
  
  if (typeof window.__dp300 === 'undefined') {
    window.__dp300 = { modules: [], questions: [] };
  }
  
  window.__dp300.questions = window.__dp300.questions.concat(questions);
  
  if (window.__dp300.modules.length < 4) {
    window.__dp300.modules[3] = "Module 4: Query Performance Optimization, Database Design & Evaluation";
  }
})();
